# Generated by Django 4.1.4 on 2023-11-08 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bmm_template_msgs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="bmm_template_msgs",
            table="bmm_template_msgs",
        ),
    ]
