# Generated by Django 4.1.4 on 2025-03-07 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ger_empresas", "0038_ger_unidade"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="vagas",
            fields=[
                ("job_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                ("jobstatus", models.CharField(max_length=50, null=True)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("dicadastro", models.DateTimeField(null=True)),
                ("dialetracao", models.DateTimeField(null=True)),
                ("dicordasao", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField(default=200, null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
                (
                    "unidade_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ger_empresas.ger_unidade",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "vagas",
            },
        ),
    ]
