# Generated by Django 4.1.4 on 2025-03-11 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0039_alter_ger_unidade_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recrutamento", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidates",
            fields=[
                ("candidate_id", models.AutoField(primary_key=True, serialize=False)),
                ("candidate", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "registration_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "sex",
                    models.CharField(blank=True, default="M", max_length=1, null=True),
                ),
                ("status_id", models.IntegerField(blank=True, null=True)),
                ("dtcadastro", models.DateTimeField(blank=True, null=True)),
                ("dtalteracao", models.DateTimeField(blank=True, null=True)),
                ("dtexclusao", models.DateTimeField(blank=True, null=True)),
                ("situacao_id", models.IntegerField(blank=True, null=True)),
                ("cpf", models.CharField(blank=True, max_length=50, null=True)),
                ("chave_edi", models.CharField(blank=True, max_length=50, null=True)),
                ("dtiniciopreenchimento", models.DateTimeField(blank=True, null=True)),
                ("dtultimopreenchimento", models.DateTimeField(blank=True, null=True)),
                ("dtenvioflow", models.DateTimeField(blank=True, null=True)),
                (
                    "photo_candidate",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("notasinternas", models.TextField(blank=True, null=True)),
                (
                    "fonterecurtamento",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                (
                    "tokencandidate",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("dtConfirmacaoGed", models.DateTimeField(blank=True, null=True)),
                ("dtConfirmacaoCPF", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "candidates",
            },
        ),
        migrations.CreateModel(
            name="DocumentReasons",
            fields=[
                (
                    "document_reasons_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("document_reasons", models.CharField(max_length=50)),
                ("dtcadastro", models.DateTimeField(auto_now_add=True)),
                ("dtalteracao", models.DateTimeField(null=True)),
                ("dtexclusao", models.DateTimeField(null=True)),
                ("situacao_id", models.IntegerField(default=200)),
                (
                    "unidade",
                    models.ForeignKey(
                        db_column="unidade_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ger_empresas.ger_unidade",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "document_reasons",
            },
        ),
        migrations.CreateModel(
            name="Documents",
            fields=[
                ("document_id", models.AutoField(primary_key=True, serialize=False)),
                ("file_path", models.CharField(max_length=400, null=True)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("document_status", models.IntegerField(default=0)),
                ("dtaprocacao", models.DateTimeField(null=True)),
                ("dtcadastro", models.DateTimeField(null=True)),
                ("dtalteracao", models.DateTimeField(null=True)),
                ("dtexclusao", models.DateTimeField(null=True)),
                ("situacao_id", models.IntegerField(default=200)),
                ("document_complement", models.CharField(max_length=100, null=True)),
                ("document_side", models.CharField(default="Frente", max_length=100)),
                ("document_obs", models.TextField(null=True)),
                ("chave_edi", models.CharField(max_length=100, null=True)),
                ("informacaoprincipal", models.CharField(max_length=200, null=True)),
                ("imageoriginal", models.CharField(max_length=400, null=True)),
                ("ged_token", models.CharField(max_length=50, null=True)),
                ("ged_status", models.CharField(default="A", max_length=1)),
                ("tokendocument", models.CharField(max_length=50, null=True)),
                ("ged_update", models.DateTimeField(null=True)),
                ("verImage", models.IntegerField(default=0)),
                ("dtConfirmacaoDocGed", models.DateTimeField(null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        db_column="candidate_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recrutamento.candidates",
                    ),
                ),
                (
                    "document_reasons",
                    models.ForeignKey(
                        db_column="document_reasons_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recrutamento.documentreasons",
                    ),
                ),
            ],
            options={
                "db_table": "documents",
            },
        ),
        migrations.CreateModel(
            name="DocumentTypes",
            fields=[
                (
                    "document_type_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("type_description", models.CharField(max_length=60)),
                ("help_text", models.TextField(null=True)),
                ("docobrigatorio", models.CharField(default="N", max_length=1)),
                ("docorder", models.CharField(default="0000", max_length=4)),
                ("dtcadastro", models.DateTimeField(null=True)),
                ("dtalteracao", models.DateTimeField(null=True)),
                ("dtexclusao", models.DateTimeField(null=True)),
                ("situacao_id", models.IntegerField(default=200)),
                ("short_description", models.CharField(max_length=45, null=True)),
                ("tokenged", models.CharField(max_length=50, null=True)),
                ("agendamento", models.CharField(default="N", max_length=1)),
                ("tokentypedoc", models.CharField(max_length=50, null=True)),
                ("flow_id", models.CharField(max_length=50, null=True)),
            ],
            options={
                "db_table": "document_types",
            },
        ),
        migrations.RenameField(
            model_name="vagas",
            old_name="dialetracao",
            new_name="dtalteracao",
        ),
        migrations.RenameField(
            model_name="vagas",
            old_name="dicadastro",
            new_name="dtexclusao",
        ),
        migrations.RemoveField(
            model_name="vagas",
            name="dicordasao",
        ),
        migrations.AddField(
            model_name="vagas",
            name="dtcadastro",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterModelTable(
            name="vagas",
            table="jobs",
        ),
        migrations.CreateModel(
            name="UnitConfig",
            fields=[
                (
                    "unidade",
                    models.OneToOneField(
                        db_column="unidade_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="ger_empresas.ger_unidade",
                    ),
                ),
                ("cnpj", models.CharField(max_length=20, null=True)),
                ("tokenempresa_ged", models.CharField(max_length=100, null=True)),
                ("boomerangue_url", models.CharField(max_length=100, null=True)),
                (
                    "boomerangue_empresa_token",
                    models.CharField(max_length=100, null=True),
                ),
                ("boomerangue_apikey", models.CharField(max_length=100, null=True)),
                ("event_bemvindo_id", models.IntegerField(null=True)),
                ("event_mensagem_id", models.IntegerField(null=True)),
                ("event_reenvio_id", models.IntegerField(null=True)),
                ("event_finalizou_id", models.IntegerField(null=True)),
                ("dtcadastro", models.DateTimeField(null=True)),
                ("dtalteracao", models.DateTimeField(null=True)),
                ("dtexclusao", models.DateTimeField(null=True)),
                ("situacao_id", models.IntegerField(default=200)),
                ("event_agendamento", models.IntegerField(null=True)),
                ("chavebot", models.CharField(max_length=50, null=True)),
                ("tokenthinkhire", models.CharField(max_length=50, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "unit_config",
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                ("template_id", models.AutoField(primary_key=True, serialize=False)),
                ("template", models.CharField(max_length=50)),
                ("template_json", models.JSONField(null=True)),
                ("template_ativo", models.CharField(default="S", max_length=1)),
                ("chave_edi", models.CharField(max_length=50, null=True)),
                ("dtcadastro", models.DateTimeField(null=True)),
                ("dtalteracao", models.DateTimeField(null=True)),
                ("dtexclusao", models.DateTimeField(null=True)),
                ("situacao_id", models.IntegerField(default=200)),
                ("template_msg", models.TextField(null=True)),
                ("templateusavar", models.CharField(default="N", max_length=1)),
                (
                    "unidade",
                    models.ForeignKey(
                        db_column="unidade_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ger_empresas.ger_unidade",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "template",
            },
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                ("process_id", models.AutoField(primary_key=True, serialize=False)),
                ("type_process_id", models.CharField(default="MOU", max_length=3)),
                ("modelo", models.CharField(max_length=100, null=True)),
                ("texto", models.TextField(null=True)),
                ("dtcadastro", models.DateTimeField(auto_now_add=True)),
                ("dtalteracao", models.DateTimeField(auto_now=True)),
                ("dtexclusao", models.DateTimeField(null=True)),
                ("situacao_id", models.IntegerField(null=True)),
                ("chave_edi", models.CharField(max_length=50, null=True)),
                ("dtprocessamento", models.DateTimeField(null=True)),
                ("status_processamento", models.CharField(default="P", max_length=1)),
                ("status_anterior", models.IntegerField(null=True)),
                ("status_novo", models.IntegerField(null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        db_column="candidate_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recrutamento.candidates",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        db_column="unidade_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ger_empresas.ger_unidade",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "process",
            },
        ),
        migrations.CreateModel(
            name="OperationLogs",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                ("operation_date", models.DateTimeField(auto_now_add=True)),
                ("operation_type", models.CharField(max_length=50)),
                ("description", models.TextField(null=True)),
                ("ip_address", models.CharField(max_length=45, null=True)),
                ("register", models.IntegerField(null=True)),
                ("flow_id", models.CharField(max_length=100, null=True)),
                ("template_id", models.CharField(max_length=100, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        db_column="candidate_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recrutamento.candidates",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        db_column="unidade_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ger_empresas.ger_unidade",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "operation_logs",
            },
        ),
        migrations.CreateModel(
            name="MessageStatus",
            fields=[
                (
                    "message_status_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("message_description", models.CharField(max_length=255)),
                ("dtcadastro", models.DateTimeField(null=True)),
                ("dtalteracao", models.DateTimeField(null=True)),
                ("dtexclusao", models.DateTimeField(null=True)),
                ("situacao_id", models.IntegerField(default=200)),
                (
                    "unidade",
                    models.ForeignKey(
                        db_column="unidade_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ger_empresas.ger_unidade",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "message_status",
            },
        ),
        migrations.CreateModel(
            name="Messages",
            fields=[
                ("message_id", models.AutoField(primary_key=True, serialize=False)),
                ("fluxo", models.CharField(default="IN", max_length=2)),
                ("message_content", models.TextField(null=True)),
                ("send_date", models.DateTimeField(auto_now_add=True)),
                ("msg_lida", models.BooleanField(default=False)),
                ("dtcadastro", models.DateTimeField(null=True)),
                ("dtalteracao", models.DateTimeField(null=True)),
                ("dtexclusao", models.DateTimeField(null=True)),
                ("situacao_id", models.IntegerField(default=200)),
                ("dtenviomensagem", models.DateTimeField(null=True)),
                ("template_id", models.CharField(max_length=100, null=True)),
                ("flow_id", models.CharField(max_length=100, null=True)),
                ("enviardestinatario", models.CharField(default="N", max_length=1)),
                ("phonedestino", models.CharField(max_length=100, null=True)),
                ("tp_message", models.CharField(default="NORMAL", max_length=20)),
                ("var01", models.CharField(max_length=50, null=True)),
                ("var02", models.CharField(max_length=50, null=True)),
                ("var03", models.CharField(max_length=50, null=True)),
                ("usavar", models.CharField(default="N", max_length=1)),
                ("flow01", models.CharField(max_length=100, null=True)),
                ("flow02", models.CharField(max_length=100, null=True)),
                ("flow03", models.CharField(max_length=100, null=True)),
                ("phoneanterior", models.CharField(max_length=45, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        db_column="candidate_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recrutamento.candidates",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        db_column="document_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recrutamento.documents",
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        db_column="document_type_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_type",
                        to="recrutamento.documenttypes",
                    ),
                ),
                (
                    "document_type_reenvio",
                    models.ForeignKey(
                        db_column="document_type_reenvio_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reenvio_document_type",
                        to="recrutamento.documenttypes",
                    ),
                ),
                (
                    "message_status",
                    models.ForeignKey(
                        db_column="message_status_id",
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recrutamento.messagestatus",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        db_column="unidade_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ger_empresas.ger_unidade",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages_as_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="usuario_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages_as_usuario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "messages",
            },
        ),
        migrations.CreateModel(
            name="JobsDocumentTypes",
            fields=[
                (
                    "jobs_document_types_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("docobg", models.CharField(default="N", max_length=1)),
                ("docorder", models.CharField(default="0000", max_length=4)),
                ("dtCadastro", models.DateTimeField(auto_now_add=True)),
                ("dtAlteracao", models.DateTimeField(null=True)),
                ("dtExclusao", models.DateTimeField(null=True)),
                ("situacao_id", models.IntegerField(default=200)),
                (
                    "document_type",
                    models.ForeignKey(
                        db_column="document_types_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recrutamento.documenttypes",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        db_column="job_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recrutamento.vagas",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="usuario_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "jobs_document_types",
            },
        ),
        migrations.CreateModel(
            name="Flow",
            fields=[
                ("flow_id", models.AutoField(primary_key=True, serialize=False)),
                ("flow", models.CharField(max_length=50)),
                ("flow_json", models.JSONField(null=True)),
                ("chave_edi", models.CharField(max_length=50, null=True)),
                ("flow_ativo", models.CharField(default="S", max_length=1)),
                ("dtcadastro", models.DateTimeField(null=True)),
                ("dtalteracao", models.DateTimeField(null=True)),
                ("dtexclusao", models.DateTimeField(null=True)),
                ("situacao_id", models.IntegerField(default=200)),
                (
                    "unidade",
                    models.ForeignKey(
                        db_column="unidade_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ger_empresas.ger_unidade",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "flow",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("eventos_id", models.AutoField(primary_key=True, serialize=False)),
                ("eventos", models.CharField(max_length=50)),
                ("telefone", models.CharField(max_length=50)),
                ("usa_template", models.CharField(default="S", max_length=1)),
                ("evento_ativo", models.CharField(default="S", max_length=1)),
                ("dtcadastro", models.DateTimeField(null=True)),
                ("dtalteracao", models.DateTimeField(null=True)),
                ("dtexclusao", models.DateTimeField(null=True)),
                ("situacao_id", models.IntegerField(default=200)),
                (
                    "flow",
                    models.ForeignKey(
                        db_column="flow_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recrutamento.flow",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        db_column="template_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recrutamento.template",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        db_column="unidade_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ger_empresas.ger_unidade",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "event",
            },
        ),
        migrations.CreateModel(
            name="DocumentTypeStd",
            fields=[
                (
                    "document_type_std_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("document_type_std", models.CharField(max_length=50)),
                ("processo", models.CharField(default="R", max_length=1)),
                ("dtcadastro", models.DateTimeField(null=True)),
                ("dtalteracao", models.DateTimeField(null=True)),
                ("dtexclusao", models.DateTimeField(null=True)),
                ("situacao_id", models.IntegerField(default=200)),
                ("column_9", models.IntegerField(null=True)),
                (
                    "unidade",
                    models.ForeignKey(
                        db_column="unidade_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ger_empresas.ger_unidade",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "document_type_std",
            },
        ),
        migrations.CreateModel(
            name="DocumentTypesFields",
            fields=[
                (
                    "document_types_field_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("fieldsearch", models.CharField(max_length=100)),
                ("fieldobg", models.CharField(default="N", max_length=1)),
                ("fieldorder", models.CharField(default="0000", max_length=4)),
                ("dtCadastro", models.DateTimeField(auto_now_add=True)),
                ("dtAlteracao", models.DateTimeField(null=True)),
                ("dtExclusao", models.DateTimeField(null=True)),
                ("situacao_id", models.IntegerField(default=200)),
                ("tokenged_tipodoc", models.CharField(max_length=100, null=True)),
                ("tokenfield", models.CharField(max_length=50, null=True)),
                (
                    "document_type",
                    models.ForeignKey(
                        db_column="document_type_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recrutamento.documenttypes",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="usuario_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "document_types_fields",
            },
        ),
        migrations.AddField(
            model_name="documenttypes",
            name="document_type_std",
            field=models.ForeignKey(
                db_column="document_type_std_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="recrutamento.documenttypestd",
            ),
        ),
        migrations.AddField(
            model_name="documenttypes",
            name="unidade",
            field=models.ForeignKey(
                db_column="unidade_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ger_empresas.ger_unidade",
            ),
        ),
        migrations.AddField(
            model_name="documenttypes",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="DocumentStatus",
            fields=[
                (
                    "document_status_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("document_status", models.CharField(max_length=50)),
                ("dtcadastro", models.DateTimeField(null=True)),
                ("dtalteracao", models.DateTimeField(null=True)),
                ("dtexclusao", models.DateTimeField(null=True)),
                ("situacao_id", models.IntegerField(default=200)),
                ("document_status_short", models.CharField(max_length=20, null=True)),
                (
                    "unidade",
                    models.ForeignKey(
                        db_column="unidade_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ger_empresas.ger_unidade",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "document_status",
            },
        ),
        migrations.AddField(
            model_name="documents",
            name="document_type",
            field=models.ForeignKey(
                db_column="document_type_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recrutamento.documenttypes",
            ),
        ),
        migrations.AddField(
            model_name="documents",
            name="unidade",
            field=models.ForeignKey(
                db_column="unidade_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ger_empresas.ger_unidade",
            ),
        ),
        migrations.AddField(
            model_name="documents",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="DocumentFields",
            fields=[
                (
                    "document_fields_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("conteudo", models.CharField(max_length=500, null=True)),
                ("dtCadastro", models.DateTimeField(auto_now_add=True)),
                ("dtAlteracao", models.DateTimeField(null=True)),
                ("dtExclusao", models.DateTimeField(null=True)),
                ("situacao_id", models.IntegerField(default=200)),
                (
                    "document",
                    models.ForeignKey(
                        db_column="document_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recrutamento.documents",
                    ),
                ),
                (
                    "document_types_field",
                    models.ForeignKey(
                        db_column="document_types_field_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recrutamento.documenttypesfields",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="usuario_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "document_fields",
            },
        ),
        migrations.CreateModel(
            name="CandidateStatus",
            fields=[
                ("status_id", models.AutoField(primary_key=True, serialize=False)),
                ("status_description", models.CharField(max_length=255)),
                ("dtcadastro", models.DateTimeField(auto_now_add=True, null=True)),
                ("dtalteracao", models.DateTimeField(blank=True, null=True)),
                ("dtexclusao", models.DateTimeField(blank=True, null=True)),
                ("situacao_id", models.IntegerField(default=200, null=True)),
                (
                    "status_description_short",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "corkankan",
                    models.CharField(default="&000000", max_length=10, null=True),
                ),
                (
                    "status_agrupado",
                    models.CharField(default="padrao", max_length=40, null=True),
                ),
                ("ordemcandstatus", models.IntegerField(null=True)),
                (
                    "unidade",
                    models.ForeignKey(
                        db_column="unidade_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_empresas.ger_unidade",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "candidate_status",
            },
        ),
        migrations.AddField(
            model_name="candidates",
            name="job_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recrutamento.vagas",
            ),
        ),
        migrations.AddField(
            model_name="candidates",
            name="recrutador_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidates_as_recruiter",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="candidates",
            name="unidade_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ger_empresas.ger_unidade",
            ),
        ),
        migrations.AddField(
            model_name="candidates",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidates_as_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="CandidateInfo",
            fields=[
                (
                    "candidate_info_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("document_id", models.IntegerField(blank=True, null=True)),
                ("document_type_id", models.IntegerField(blank=True, null=True)),
                ("message_id", models.IntegerField(blank=True, null=True)),
                ("eventos_id", models.IntegerField(blank=True, null=True)),
                ("template_id", models.IntegerField(blank=True, null=True)),
                ("flow_id", models.IntegerField(blank=True, null=True)),
                (
                    "candidate_info",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("candidate_data", models.TextField(blank=True, null=True)),
                ("Origem_inro", models.CharField(blank=True, max_length=10, null=True)),
                ("chave_edi", models.CharField(blank=True, max_length=100, null=True)),
                ("dtcadastro", models.DateTimeField(blank=True, null=True)),
                ("dtalteracao", models.DateTimeField(blank=True, null=True)),
                ("dtexclusao", models.DateTimeField(blank=True, null=True)),
                (
                    "situacao_id",
                    models.IntegerField(blank=True, default=200, null=True),
                ),
                (
                    "candidate_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="recrutamento.candidates",
                    ),
                ),
                (
                    "unidade_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ger_empresas.ger_unidade",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "candidate_info",
            },
        ),
        migrations.CreateModel(
            name="Applications",
            fields=[
                ("application_id", models.AutoField(primary_key=True, serialize=False)),
                ("application_status", models.CharField(max_length=50, null=True)),
                ("application_date", models.DateTimeField(auto_now_add=True)),
                ("dtcadastro", models.DateTimeField(auto_now_add=True, null=True)),
                ("dtalteracao", models.DateTimeField(null=True)),
                ("dtexclusao", models.DateTimeField(null=True)),
                ("situacao_id", models.IntegerField(default=200)),
                (
                    "candidate",
                    models.ForeignKey(
                        db_column="candidate_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recrutamento.candidates",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        db_column="job_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recrutamento.vagas",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        db_column="unidade_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ger_empresas.ger_unidade",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "applications",
            },
        ),
        migrations.AddIndex(
            model_name="messages",
            index=models.Index(
                fields=[
                    "enviardestinatario",
                    "tp_message",
                    "dtenviomensagem",
                    "document",
                ],
                name="idx_msg_dest_status",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documents",
            unique_together={
                ("candidate", "document_type", "document_side", "document_complement")
            },
        ),
        migrations.AddIndex(
            model_name="applications",
            index=models.Index(fields=["job"], name="idx_applications_job_id"),
        ),
        migrations.AddIndex(
            model_name="applications",
            index=models.Index(
                fields=["candidate"], name="idx_applications_candidate_id"
            ),
        ),
    ]
