# Generated by Django 4.1.4 on 2025-03-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recrutamento", "0003_applications_empresa_candidates_empresa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidates",
            name="dtcadastro",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
