# Generated by Django 4.1.4 on 2025-03-11 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recrutamento", "0004_alter_candidates_dtcadastro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidates",
            name="status_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recrutamento.candidatestatus",
            ),
        ),
    ]
