# Generated by Django 4.1.4 on 2025-03-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recrutamento", "0005_alter_candidates_status_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentstatus",
            name="dtcadastro",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
