# Generated by Django 4.1.4 on 2025-04-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recrutamento", "0006_alter_documentstatus_dtcadastro"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatestatus",
            name="icon",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
