# Generated by Django 4.1.4 on 2025-04-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recrutamento", "0007_candidatestatus_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatestatus",
            name="status_description",
            field=models.CharField(db_collation="utf8mb4_unicode_ci", max_length=255),
        ),
    ]
