# Generated by Django 4.1.4 on 2023-11-07 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ger_empresas", "0006_rename_empresa_id_ger_empresa_b2b_empresa_and_more"),
        ("bot_provedor", "0004_rename_empresa_id_bot_provedor_empresa_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="bot_canal",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("canal", models.CharField(blank=True, max_length=45, unique=True)),
                ("canal_ativo", models.CharField(default="S", max_length=1)),
                ("cadastro_dt", models.DateTimeField(auto_now=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField(default=200)),
                (
                    "empresa",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
                (
                    "provedor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot_provedor.bot_provedor",
                    ),
                ),
            ],
            options={
                "db_table": "bot_canal",
            },
        ),
    ]
