# Generated by Django 4.1.4 on 2024-03-14 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot_canal", "0002_alter_bot_canal_empresa_alter_bot_canal_provedor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bot_canal",
            name="provedor",
        ),
    ]
