# Generated by Django 4.1.4 on 2024-04-13 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("campaign", "0062_bmm_boomeranguelog_usuario"),
        ("ger_empresas", "0030_ger_empresas_max_tokens_ia"),
    ]

    operations = [
        migrations.CreateModel(
            name="ger_empresas_log",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("DataLog", models.DateTimeField(auto_now_add=True)),
                ("acao_id", models.CharField(max_length=25, null=True)),
                ("descricao", models.CharField(max_length=100, null=True)),
                (
                    "campanha",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="campaign.bmm_campanha",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="campaign.bmm_template",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
