# Generated by Django 4.1.4 on 2023-10-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="wpp_templatebuttons",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("component_id", models.IntegerField()),
                (
                    "button_type",
                    models.CharField(
                        choices=[
                            ("QUICK_REPLY", "QUICK_REPLY"),
                            ("CALL_TO_ACTION", "CALL_TO_ACTION"),
                        ],
                        max_length=20,
                    ),
                ),
                ("button_text", models.CharField(max_length=255)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True)),
                ("exclusao_dt", models.DateTimeField(blank=True, null=True)),
                ("statusregistro_id", models.IntegerField()),
            ],
        ),
    ]
