# Generated by Django 4.1.4 on 2023-11-07 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templatebuttons", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="wpp_templatebuttons",
            table="wpp_templatebuttons",
        ),
    ]
