# Generated by Django 4.1.4 on 2023-11-08 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "wpp_templatescomponents",
            "0003_alter_wpp_templatescomponents_statusregistro_id",
        ),
        ("wpp_templatebuttons", "0002_alter_wpp_templatebuttons_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wpp_templatebuttons",
            name="component_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wpp_templatescomponents.wpp_templatescomponents",
            ),
        ),
        migrations.AlterField(
            model_name="wpp_templatebuttons",
            name="statusregistro_id",
            field=models.IntegerField(default=200),
        ),
    ]
