# Generated by Django 4.1.4 on 2023-10-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="wpp_templatelistitems",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("component_id", models.IntegerField()),
                ("item_title", models.CharField(max_length=255)),
                ("item_description", models.TextField(blank=True, null=True)),
                ("button_id", models.IntegerField(blank=True, null=True)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True)),
                ("exclusao_dt", models.DateTimeField(blank=True, null=True)),
                ("statusregistro_id", models.IntegerField()),
            ],
        ),
    ]
