# Generated by Django 4.1.4 on 2023-11-08 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "wpp_templatescomponents",
            "0003_alter_wpp_templatescomponents_statusregistro_id",
        ),
        (
            "wpp_templatelistitems",
            "0002_alter_wpp_templatelistitems_statusregistro_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="wpp_templatelistitems",
            name="component_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wpp_templatescomponents.wpp_templatescomponents",
            ),
        ),
    ]
