# Generated by Django 4.1.4 on 2024-09-09 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        # migrations.CreateModel(
        #     name="PixRequest",
        #     fields=[
        #         (
        #             "id",
        #             models.CharField(max_length=36, primary_key=True, serialize=False),
        #         ),
        #         ("transaction_id", models.CharField(max_length=255)),
        #         ("pix_key", models.CharField(max_length=255)),
        #         ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
        #         ("txid", models.CharField(blank=True, max_length=255, null=True)),
        #         (
        #             "status",
        #             models.CharField(
        #                 choices=[
        #                     ("PENDING", "Pendente"),
        #                     ("COMPLETED", "Concluído"),
        #                     ("EXPIRED", "Expirado"),
        #                     ("CANCELLED", "Cancelado"),
        #                 ],
        #                 max_length=9,
        #             ),
        #         ),
        #         ("created_at", models.DateTimeField(auto_now_add=True)),
        #         ("updated_at", models.DateTimeField(auto_now=True)),
        #         ("data_expiracao", models.DateTimeField(blank=True, null=True)),
        #         ("data_tx", models.DateTimeField(blank=True, null=True)),
        #         ("cpf", models.CharField(blank=True, max_length=11, null=True)),
        #         (
        #             "nome_pagador",
        #             models.CharField(blank=True, max_length=255, null=True),
        #         ),
        #         ("empresa", models.IntegerField()),
        #     ],
        #     options={
        #         "db_table": "pix_requests",
        #     },
        # ),
        # migrations.CreateModel(
        #     name="PixEvent",
        #     fields=[
        #         (
        #             "id",
        #             models.CharField(max_length=36, primary_key=True, serialize=False),
        #         ),
        #         ("event_type", models.CharField(max_length=255)),
        #         ("event_description", models.TextField()),
        #         ("event_timestamp", models.DateTimeField()),
        #         ("teste", models.CharField(default="teste", max_length=1)),
        #         (
        #             "request",
        #             models.ForeignKey(
        #                 on_delete=django.db.models.deletion.CASCADE,
        #                 related_name="events",
        #                 to="pix_database.pixrequest",
        #             ),
        #         ),
        #     ],
        #     options={
        #         "db_table": "pix_events",
        #     },
        # ),
    ]
