# Generated by Django 4.1.4 on 2024-09-09 20:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("pix_database", "0001_initial"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="pixrequest",
        #     name="boomerangue",
        #     field=models.IntegerField(null=True),
        # ),
        # migrations.AddField(
        #     model_name="pixrequest",
        #     name="campanha",
        #     field=models.ImageField(null=True, upload_to=""),
        # ),
        # migrations.AlterField(
        #     model_name="pixrequest",
        #     name="cpf",
        #     field=models.CharField(blank=True, max_length=20, null=True),
        # ),
        # migrations.AlterField(
        #     model_name="pixrequest",
        #     name="id",
        #     field=models.CharField(
        #         default=uuid.uuid4,
        #         editable=False,
        #         max_length=36,
        #         primary_key=True,
        #         serialize=False,
        #         unique=True,
        #     ),
        # ),
        # migrations.AlterField(
        #     model_name="pixrequest",
        #     name="pix_key",
        #     field=models.CharField(max_length=255, null=True),
        # ),
        # migrations.AlterField(
        #     model_name="pixrequest",
        #     name="transaction_id",
        #     field=models.CharField(max_length=255, null=True),
        # ),
    ]
