# Generated by Django 4.1.4 on 2024-09-09 21:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("pix_database", "0002_pixrequest_boomerangue_pixrequest_campanha_and_more"),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name="pixevent",
        #     name="id",
        #     field=models.CharField(
        #         default=uuid.uuid4,
        #         editable=False,
        #         max_length=36,
        #         primary_key=True,
        #         serialize=False,
        #         unique=True,
        #     ),
        # ),
    ]
