# Generated by Django 4.1.4 on 2024-09-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pix_database", "0003_alter_pixevent_id"),
    ]

    operations = [
    #    migrations.AlterField(
    #         model_name="pixevent",
    #         name="event_timestamp",
    #         field=models.DateTimeField(auto_now_add=True),
    #     ), 
    ]
