# Generated by Django 4.1.4 on 2024-09-09 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pix_database", "0004_alter_pixevent_event_timestamp"),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name="pixevent",
        #     name="request",
        #     field=models.ForeignKey(
        #         null=True,
        #         on_delete=django.db.models.deletion.CASCADE,
        #         related_name="events",
        #         to="pix_database.pixrequest",
        #     ),
        # ),
    ]
