# Generated by Django 4.1.4 on 2024-09-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pix_database", "0005_alter_pixevent_request"),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name="pixevent",
        #     name="teste",
        #     field=models.CharField(default="teste", max_length=1, null=True),
        # ),
    ]
