# Generated by Django 4.1.4 on 2024-09-09 23:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pix_database", "0006_alter_pixevent_teste"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="pixevent",
        #     name="teste",
        # ),
    ]
