# Generated by Django 4.1.4 on 2024-09-10 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pix_database", "0007_remove_pixevent_teste"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="pixevent",
        #     name="teste",
        # ),
        # migrations.AlterField(
        #     model_name="pixevent",
        #     name="request",
        #     field=models.ForeignKey(
        #         null=True,
        #         on_delete=django.db.models.deletion.CASCADE,
        #         to="pix_database.pixrequest",
        #     ),
        # ),
    ]
