# Generated by Django 4.1.4 on 2024-09-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pix_database", "0008_remove_pixevent_teste_alter_pixevent_request"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="pixevent",
        #     name="teste",
        # ),
        # migrations.AlterField(
        #     model_name="pixevent",
        #     name="request",
        #     field=models.CharField(max_length=100, null=True),
        # ),
    ]
