# Generated by Django 4.1.4 on 2024-12-02 20:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pix_database", "0009_remove_pixevent_teste_alter_pixevent_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="PixEvent",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("request", models.CharField(max_length=100, null=True)),
                ("event_type", models.CharField(max_length=255)),
                ("event_description", models.TextField()),
                ("event_timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "pix_events",
            },
        ),
        migrations.CreateModel(
            name="PixRequest",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("transaction_id", models.CharField(max_length=255, null=True)),
                ("pix_key", models.CharField(max_length=255, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("txid", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("COMPLETED", "Concluído"),
                            ("EXPIRED", "Expirado"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        max_length=9,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data_expiracao", models.DateTimeField(blank=True, null=True)),
                ("data_tx", models.DateTimeField(blank=True, null=True)),
                ("cpf", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "nome_pagador",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("empresa", models.IntegerField()),
                ("boomerangue", models.IntegerField(null=True)),
                ("campanha", models.ImageField(null=True, upload_to="")),
            ],
            options={
                "db_table": "pix_requests",
            },
        ),
    ]
