# Generated by Django 4.1.4 on 2023-10-05 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ger_empresas", "__first__"),
        ("ger_produtos", "__first__"),
        ("ger_dadosgerais", "__first__"),
        ("ger_entidades", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="bmm_boomerangue",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("campanha_nome", models.CharField(max_length=50, null=True)),
                ("prefixo", models.CharField(max_length=50)),
                ("edi_integracao", models.CharField(max_length=50, null=True)),
                ("cod_puxada", models.CharField(max_length=20, null=True)),
                ("chave_busca", models.CharField(max_length=150, null=True)),
                ("sai_relatorio", models.CharField(max_length=1, null=True)),
                ("identificacao_relatorio", models.CharField(max_length=50, null=True)),
                ("token_bm", models.CharField(max_length=50, null=True)),
                ("short_url", models.CharField(max_length=200, null=True)),
                ("telefone_bm", models.CharField(max_length=20, null=True)),
                ("data_inicio_campanha", models.DateTimeField(null=True)),
                ("data_final_campanha", models.DateTimeField(null=True)),
                ("hora_inicio_envio", models.CharField(max_length=5, null=True)),
                ("hora_final_envio", models.CharField(max_length=5, null=True)),
                ("usar_desconto_geral", models.CharField(max_length=1, null=True)),
                ("extra_info_4", models.CharField(max_length=300, null=True)),
                ("mensagem_personalizada", models.CharField(max_length=300, null=True)),
                ("usar_status_envio_bm", models.CharField(max_length=1, null=True)),
                ("nro_envios_reforcos", models.CharField(max_length=1, null=True)),
                ("data_criacao_bm", models.DateTimeField(auto_now_add=True)),
                ("data_programada_bm", models.DateTimeField(null=True)),
                ("data_limite_envio_bm", models.DateTimeField(null=True)),
                ("data_pri_envio", models.DateTimeField(null=True)),
                ("data_ult_envio", models.DateTimeField(null=True)),
                ("data_entrega", models.DateTimeField(null=True)),
                ("data_optin", models.DateTimeField(null=True)),
                ("data_leitura", models.DateTimeField(null=True)),
                ("data_resposta_wz", models.DateTimeField(null=True)),
                ("data_pri_click_link", models.DateTimeField(null=True)),
                ("data_ult_click_link", models.DateTimeField(null=True)),
                ("data_pri_open_web", models.DateTimeField(null=True)),
                ("data_ult_open_web", models.DateTimeField(null=True)),
                ("data_aceite_bm", models.DateTimeField(null=True)),
                ("data_encerramento_bm", models.DateTimeField(null=True)),
                ("data_proximo_repic", models.DateTimeField(null=True)),
                ("data_proximo_repic_enviado", models.DateTimeField(null=True)),
                ("data_prevista_repic1", models.DateTimeField(null=True)),
                ("data_prevista_repic2", models.DateTimeField(null=True)),
                ("data_prevista_repic3", models.DateTimeField(null=True)),
                ("data_repic_forcado", models.DateTimeField(null=True)),
                ("data_repic_forcado_envio", models.DateTimeField(null=True)),
                ("bm_data_limite_repic", models.DateTimeField(null=True)),
                ("envia_boomerangue", models.CharField(max_length=1, null=True)),
                ("bm_enviado", models.IntegerField(null=True)),
                ("bm_foi_entregue", models.IntegerField(null=True)),
                ("bm_optin_enviado", models.CharField(default="N", max_length=1)),
                ("bm_optin_aceito", models.CharField(default="S", max_length=1)),
                ("bm_foi_lido", models.IntegerField(null=True)),
                ("bm_resposta_wz", models.IntegerField(null=True)),
                ("bm_click_link", models.IntegerField(null=True)),
                ("bm_open_web", models.IntegerField(null=True)),
                ("bm_aceito", models.CharField(max_length=1, null=True)),
                ("bm_encerrado", models.CharField(default="N", max_length=1)),
                ("bm_ativo", models.CharField(default="S", max_length=1)),
                ("bm_modo_teste", models.CharField(max_length=1, null=True)),
                ("bm_com_erro", models.CharField(max_length=1, null=True)),
                ("bm_mensagem_status", models.CharField(max_length=200, null=True)),
                ("bm_enviado_reforco1", models.CharField(max_length=1, null=True)),
                ("bm_enviado_reforco2", models.CharField(max_length=1, null=True)),
                ("bm_enviado_reforco3", models.CharField(max_length=1, null=True)),
                ("data_instalacao_pwa", models.DateTimeField(null=True)),
                ("data_instalacao_ult_pwa", models.DateTimeField(null=True)),
                ("nro_instalacoes_pwa", models.IntegerField(null=True)),
                ("titulo_boomerangue", models.CharField(max_length=255)),
                ("lista_oferta", models.CharField(max_length=50, null=True)),
                (
                    "condicoes_pagamento_escolhe",
                    models.CharField(max_length=1, null=True),
                ),
                ("transportadora_escolhe", models.CharField(max_length=1, null=True)),
                ("dia_entrega_escolhe", models.CharField(max_length=1, null=True)),
                ("nro_itens", models.IntegerField(null=True)),
                (
                    "compra_minima_vlr",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "compra_minima_qtd",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "desconto_promocional",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "valor_original",
                    models.DecimalField(decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "valor_atual",
                    models.DecimalField(decimal_places=2, max_digits=18, null=True),
                ),
                ("dt_primeira_compra", models.DateTimeField(null=True)),
                ("dt_ultima_compra", models.DateTimeField(null=True)),
                ("aciona_api_partner", models.CharField(max_length=1, null=True)),
                ("chave_bot", models.CharField(max_length=15, null=True)),
                ("nome_bot", models.CharField(max_length=50, null=True)),
                ("data_bot", models.DateTimeField(null=True)),
                ("nome_bot_repique", models.CharField(max_length=50, null=True)),
                ("data_bot_repique", models.DateTimeField(null=True)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True, null=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField(default=200)),
            ],
            options={
                "db_table": "bmm_boomerangue",
            },
        ),
        migrations.CreateModel(
            name="bmm_boomerangueitens",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("edi_integracao_item", models.CharField(max_length=50)),
                ("produto_original_id", models.CharField(max_length=50)),
                (
                    "quantidade_sugerida",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "quantidade_minima",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "quantidade_maxima",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "quantidade_disponivel",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "multiplo_boomerangue",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "multiplo_pague",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "valor_item_original",
                    models.DecimalField(decimal_places=6, max_digits=18),
                ),
                ("valor_atacado", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=6, max_digits=18),
                ),
                (
                    "valor_unitario_calculado",
                    models.DecimalField(decimal_places=6, max_digits=18),
                ),
                (
                    "valor_total_item",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "valor_sem_desconto",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "percentual_desconto",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                ("item_ativo", models.CharField(max_length=1)),
                ("ordem", models.CharField(max_length=4)),
                ("obrigatorio_compra", models.CharField(max_length=1)),
                ("unidade_caixa", models.CharField(max_length=10)),
                ("unidade_venda", models.CharField(max_length=10)),
                ("tipo_item_boomerangue_id", models.CharField(max_length=2, null=True)),
                ("produto_bloqueado", models.CharField(max_length=1)),
                ("complemento1", models.CharField(max_length=100, null=True)),
                (
                    "boomerangue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaign.bmm_boomerangue",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_produtos.ger_produtos",
                    ),
                ),
            ],
            options={
                "db_table": "bmm_boomerangueitens",
            },
        ),
        migrations.CreateModel(
            name="bmm_campanha",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("Campanha", models.CharField(max_length=45, null=True)),
                ("CampanhaTag", models.CharField(max_length=45, null=True)),
                ("EdiCampanha", models.CharField(max_length=50, null=True)),
                ("NroLeads", models.IntegerField(default=0)),
                ("TextoHeader", models.CharField(max_length=200, null=True)),
                ("TextoFooter", models.CharField(max_length=200, null=True)),
                (
                    "TextoPromocional",
                    models.CharField(default="Pedido Express", max_length=100),
                ),
                ("LinkFooter", models.CharField(max_length=400, null=True)),
                (
                    "ImageBannerPC",
                    models.ImageField(max_length=400, null=True, upload_to="media/"),
                ),
                (
                    "ImageBannerMobile",
                    models.ImageField(max_length=400, null=True, upload_to="media/"),
                ),
                (
                    "ImageInicialPC",
                    models.ImageField(max_length=400, null=True, upload_to=""),
                ),
                (
                    "ImageInicialMobile",
                    models.ImageField(max_length=400, null=True, upload_to=""),
                ),
                (
                    "ImagemCabecalhoPC",
                    models.ImageField(max_length=400, null=True, upload_to=""),
                ),
                (
                    "ImagemCabecalhoMobile",
                    models.ImageField(max_length=400, null=True, upload_to=""),
                ),
                (
                    "ImagemMarketingPC",
                    models.ImageField(max_length=400, null=True, upload_to=""),
                ),
                (
                    "ImagemMarketingMobile",
                    models.ImageField(max_length=400, null=True, upload_to=""),
                ),
                ("LinkMarketing", models.CharField(max_length=400, null=True)),
                ("CampanhaAtiva", models.CharField(default="N", max_length=1)),
            ],
            options={
                "db_table": "bmm_campanha",
            },
        ),
        migrations.CreateModel(
            name="bmm_regra",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("regraenvio", models.CharField(max_length=20)),
                ("regraintegracao", models.CharField(max_length=20)),
                ("regrausuario", models.CharField(max_length=20)),
                ("naolistaquantidade", models.CharField(max_length=1)),
                ("salvarlog", models.CharField(max_length=1)),
                ("UtilizaOptin", models.CharField(max_length=1)),
                ("nromaximoleads", models.IntegerField(default=0)),
                ("solicitarconfirmacao", models.CharField(max_length=1)),
                ("enviarlink", models.CharField(max_length=1)),
                ("prefixoboomerangue", models.CharField(max_length=30)),
                ("dominioboomerangue", models.CharField(max_length=100)),
                ("Dominiohttps", models.CharField(max_length=1)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
            ],
            options={
                "db_table": "bmm_regra",
            },
        ),
        migrations.CreateModel(
            name="bmm_template",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome_template", models.CharField(max_length=100, null=True)),
                ("chave_campanha", models.CharField(max_length=100, null=True)),
                ("edi_campanha_template", models.CharField(max_length=50, null=True)),
                ("template_master_id", models.CharField(max_length=45, null=True)),
                ("texto_header", models.CharField(max_length=200, null=True)),
                ("texto_footer", models.CharField(max_length=200, null=True)),
                (
                    "texto_promocional",
                    models.CharField(default="Pedido Express", max_length=100),
                ),
                ("link_footer", models.CharField(max_length=400, null=True)),
                (
                    "image_banner_pc",
                    models.ImageField(
                        max_length=400, null=True, upload_to="media/banner_pc/"
                    ),
                ),
                (
                    "image_banner_mobile",
                    models.ImageField(
                        max_length=400, null=True, upload_to="media/banner_mobile/"
                    ),
                ),
                (
                    "image_inicial_pc",
                    models.ImageField(max_length=400, null=True, upload_to=""),
                ),
                (
                    "image_inicial_mobile",
                    models.ImageField(max_length=400, null=True, upload_to=""),
                ),
                (
                    "imagem_cabecalho_pc",
                    models.ImageField(max_length=400, null=True, upload_to=""),
                ),
                (
                    "imagem_cabecalho_mobile",
                    models.ImageField(max_length=400, null=True, upload_to=""),
                ),
                (
                    "imagem_marketing_pc",
                    models.ImageField(max_length=400, null=True, upload_to=""),
                ),
                (
                    "imagem_marketing_mobile",
                    models.ImageField(max_length=400, null=True, upload_to=""),
                ),
                ("link_marketing", models.CharField(max_length=400, null=True)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField(default=200)),
                (
                    "empresa",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
            ],
            options={
                "db_table": "bmm_template",
            },
        ),
        migrations.CreateModel(
            name="bmm_regra_eventos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("evento", models.CharField(max_length=100)),
                ("eventopadrao", models.CharField(max_length=20)),
                ("acionaapiterceiros", models.CharField(default="N", max_length=1)),
                ("urlapi", models.CharField(max_length=100, null=True)),
                ("urlapiauth", models.CharField(max_length=100, null=True)),
                ("urlpayload", models.TextField(null=True)),
                ("acionarotinainterna", models.CharField(default="N", max_length=1)),
                ("Rotinainterna", models.CharField(max_length=20)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                (
                    "regra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaign.bmm_regra",
                    ),
                ),
            ],
            options={
                "db_table": "bmm_regra_eventos",
            },
        ),
        migrations.AddField(
            model_name="bmm_regra",
            name="templateconfirmacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="campaign.bmm_template"
            ),
        ),
        migrations.CreateModel(
            name="bmm_campanhaidentificadores",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("identificador", models.CharField(max_length=50, null=True)),
                ("identificador_ativo", models.CharField(default="S", max_length=1)),
                (
                    "campanha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaign.bmm_campanha",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaign.bmm_template",
                    ),
                ),
            ],
            options={
                "db_table": "bmm_campanhaidentificadores",
            },
        ),
        migrations.AddField(
            model_name="bmm_campanha",
            name="template_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="campaign.bmm_template",
            ),
        ),
        migrations.CreateModel(
            name="bmm_boomeranguelog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tipolog_id", models.CharField(max_length=1)),
                ("origemlog_id", models.CharField(max_length=1)),
                ("boomerangueimportacao_id", models.IntegerField()),
                ("entidade_id", models.BigIntegerField()),
                ("acao_id", models.CharField(max_length=25)),
                ("acaoenviada_id", models.CharField(max_length=25)),
                ("Token", models.CharField(max_length=100)),
                ("Template", models.CharField(max_length=25)),
                ("DataLog", models.DateTimeField()),
                ("Telefone", models.CharField(max_length=25)),
                ("Complemento1", models.CharField(max_length=100)),
                ("Complemento2", models.CharField(max_length=400)),
                ("Complemento3", models.CharField(max_length=100)),
                ("TempoLog", models.IntegerField()),
                ("VerApiLog", models.CharField(max_length=3)),
                (
                    "boomerangue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaign.bmm_boomerangue",
                    ),
                ),
                (
                    "boomerangueitem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaign.bmm_boomerangueitens",
                    ),
                ),
            ],
            options={
                "db_table": "bmm_boomeranguelog",
            },
        ),
        migrations.CreateModel(
            name="bmm_boomerangueimportado",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("NomeArquivo", models.CharField(max_length=200)),
                ("DataHora", models.DateTimeField()),
                ("statusarquivo_id", models.CharField(max_length=1)),
                (
                    "campanha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaign.bmm_campanha",
                    ),
                ),
            ],
            options={
                "db_table": "bmm_boomerangueimportado",
            },
        ),
        migrations.CreateModel(
            name="bmm_boomerangueevento",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tipoevento_id", models.CharField(max_length=20)),
                ("origemevento_id", models.CharField(max_length=1)),
                ("DataGeracao", models.DateTimeField()),
                ("ProtocoloGeracao", models.CharField(max_length=50)),
                ("DataProgramada", models.DateTimeField()),
                ("statusevento_id", models.CharField(max_length=1)),
                ("ChaveBot", models.CharField(max_length=15)),
                ("NomeBot", models.CharField(max_length=50)),
                ("DataBot", models.DateTimeField()),
                (
                    "boomerangue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaign.bmm_boomerangue",
                    ),
                ),
            ],
            options={
                "db_table": "bmm_boomerangueevento",
            },
        ),
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="campanha",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="campaign.bmm_campanha"
            ),
        ),
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="condicoes_pagamento_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ger_empresas.ger_condicoespagamento",
            ),
        ),
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ger_empresas.ger_empresas",
            ),
        ),
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="entidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ger_entidades.ger_entidade",
            ),
        ),
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="campaign.bmm_template"
            ),
        ),
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="transportadora",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ger_dadosgerais.ger_transportadora",
            ),
        ),
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="vendedor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ger_dadosgerais.ger_vendedores",
            ),
        ),
        migrations.AddIndex(
            model_name="bmm_regra_eventos",
            index=models.Index(fields=["regra"], name="fk_bmm_regra_ev"),
        ),
        migrations.AddIndex(
            model_name="bmm_regra",
            index=models.Index(fields=["empresa"], name="ixEmpresa"),
        ),
        migrations.AddIndex(
            model_name="bmm_boomeranguelog",
            index=models.Index(fields=["boomerangue"], name="iLista"),
        ),
        migrations.AddIndex(
            model_name="bmm_boomeranguelog",
            index=models.Index(fields=["boomerangueitem"], name="ilistitem"),
        ),
        migrations.AddIndex(
            model_name="bmm_boomeranguelog",
            index=models.Index(fields=["DataLog"], name="datalog"),
        ),
        migrations.AddIndex(
            model_name="bmm_boomeranguelog",
            index=models.Index(fields=["entidade_id"], name="ientidade_id"),
        ),
        migrations.AddIndex(
            model_name="bmm_boomeranguelog",
            index=models.Index(fields=["Complemento1", "boomerangue"], name="Comp1"),
        ),
        migrations.AddIndex(
            model_name="bmm_boomeranguelog",
            index=models.Index(fields=["acao_id"], name="iAcao"),
        ),
        migrations.AddIndex(
            model_name="bmm_boomeranguelog",
            index=models.Index(fields=["acaoenviada_id"], name="IACAOLOG"),
        ),
        migrations.AddIndex(
            model_name="bmm_boomerangueitens",
            index=models.Index(
                fields=[
                    "boomerangue",
                    "produto_original_id",
                    "tipo_item_boomerangue_id",
                    "unidade_venda",
                ],
                name="idListaOferta",
            ),
        ),
        migrations.AddIndex(
            model_name="bmm_boomerangueitens",
            index=models.Index(
                fields=["boomerangue"], name="bmm_boomera_boomera_688008_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bmm_boomerangueitens",
            index=models.Index(
                fields=["boomerangue", "produto_original_id"],
                name="bmm_boomera_boomera_137b89_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bmm_boomerangueitens",
            index=models.Index(
                fields=["produto_original_id", "edi_integracao_item"], name="ixEDIBUSCA"
            ),
        ),
        migrations.AddIndex(
            model_name="bmm_boomerangueitens",
            index=models.Index(fields=["produto_bloqueado"], name="ixProdutoBloqueado"),
        ),
        migrations.AddIndex(
            model_name="bmm_boomerangueitens",
            index=models.Index(
                fields=["produto_original_id"], name="ixProdutoOriginal"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bmm_boomerangueitens",
            unique_together={
                (
                    "boomerangue",
                    "produto_original_id",
                    "tipo_item_boomerangue_id",
                    "unidade_venda",
                )
            },
        ),
        migrations.AddIndex(
            model_name="bmm_boomerangueimportado",
            index=models.Index(fields=["DataHora"], name="idxDataHora"),
        ),
        migrations.AddIndex(
            model_name="bmm_boomerangueimportado",
            index=models.Index(fields=["campanha", "NomeArquivo"], name="IXBUSCA"),
        ),
        migrations.AddIndex(
            model_name="bmm_boomerangueevento",
            index=models.Index(
                fields=["boomerangue", "tipoevento_id", "ProtocoloGeracao"],
                name="iStatus",
            ),
        ),
        migrations.AddIndex(
            model_name="bmm_boomerangueevento",
            index=models.Index(fields=["DataGeracao"], name="iDataGeracao"),
        ),
        migrations.AddIndex(
            model_name="bmm_boomerangueevento",
            index=models.Index(fields=["ProtocoloGeracao"], name="iProtocoloGeracao"),
        ),
        migrations.AddIndex(
            model_name="bmm_boomerangueevento",
            index=models.Index(fields=["NomeBot"], name="ixComp1"),
        ),
        migrations.AddIndex(
            model_name="bmm_boomerangueevento",
            index=models.Index(
                fields=["tipoevento_id", "statusevento_id", "NomeBot"],
                name="itipoevento_id",
            ),
        ),
        migrations.AddIndex(
            model_name="bmm_boomerangueevento",
            index=models.Index(fields=["statusevento_id"], name="Istatusevento"),
        ),
    ]
