# Generated by Django 4.1.4 on 2023-10-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bmm_boomerangueimportado",
            name="DataHora",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
