# Generated by Django 4.1.4 on 2023-10-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0002_alter_bmm_boomerangueimportado_datahora"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_boomerangueimportado",
            name="Caminho",
            field=models.FileField(null=True, upload_to="media/csvs_importados/"),
        ),
    ]
