# Generated by Django 4.1.4 on 2023-10-16 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0003_alter_ger_condicoespagamento_empresa"),
        ("campaign", "0004_bmm_campanha_empresa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bmm_boomerangue",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ger_empresas.ger_empresas",
            ),
        ),
    ]
