# Generated by Django 4.1.4 on 2023-11-06 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0005_alter_bmm_boomerangue_empresa"),
    ]

    operations = [
        migrations.CreateModel(
            name="bmm_templateimportado",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("NomeArquivo", models.CharField(max_length=200)),
                (
                    "Caminho",
                    models.FileField(null=True, upload_to="media/csvs_importados/"),
                ),
                ("DataHora", models.DateTimeField(auto_now=True)),
                ("statusarquivo_id", models.CharField(max_length=1)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaign.bmm_template",
                    ),
                ),
            ],
            options={
                "db_table": "bmm_templateimportado",
            },
        ),
        migrations.AddIndex(
            model_name="bmm_templateimportado",
            index=models.Index(fields=["DataHora"], name="idDataHora"),
        ),
        migrations.AddIndex(
            model_name="bmm_templateimportado",
            index=models.Index(fields=["template", "NomeArquivo"], name="IDBUSCA"),
        ),
    ]
