# Generated by Django 4.1.4 on 2023-11-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0006_bmm_templateimportado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bmm_boomerangueimportado",
            name="Caminho",
            field=models.FileField(null=True, upload_to="media/arq_campanhas/"),
        ),
        migrations.AlterField(
            model_name="bmm_templateimportado",
            name="Caminho",
            field=models.FileField(null=True, upload_to="media/arq_templates/"),
        ),
    ]
