# Generated by Django 4.1.4 on 2023-11-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0007_alter_bmm_boomerangueimportado_caminho_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_campanha",
            name="agendamento_clinica",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bmm_campanha",
            name="agendamento_dentista",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bmm_campanha",
            name="agendamento_hospital",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bmm_campanha",
            name="agendamento_medico",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bmm_campanha",
            name="distribuidora_caixa",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bmm_campanha",
            name="distribuidora_combo",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bmm_campanha",
            name="distribuidora_unitario",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bmm_campanha",
            name="doacoes",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bmm_campanha",
            name="industria_caixa",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bmm_campanha",
            name="industria_combo",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bmm_campanha",
            name="industria_unitario",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
