# Generated by Django 4.1.4 on 2023-11-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0008_bmm_campanha_agendamento_clinica_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_campanha",
            name="periodicidade",
            field=models.CharField(
                choices=[
                    ("MA", "Manual"),
                    ("D", "Diário"),
                    ("S", "Semanal"),
                    ("Q", "Quinzenal"),
                    ("ME", "Mensal"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
