# Generated by Django 4.1.4 on 2023-11-07 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0009_bmm_campanha_periodicidade"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bmm_campanha",
            old_name="template_id",
            new_name="template",
        ),
    ]
