# Generated by Django 4.1.4 on 2023-11-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0010_rename_template_id_bmm_campanha_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_campanha",
            name="tipo_campanha",
            field=models.CharField(max_length=5, null=True),
        ),
    ]
