# Generated by Django 4.1.4 on 2023-11-08 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0007_alter_ger_condicoespagamento_condicaopadrao_and_more"),
        ("ger_entidades", "0005_alter_ger_categoriaentidade_empresa_and_more"),
        (
            "ger_produtos",
            "0003_ger_produtos_alteracao_dt_ger_produtos_cadastro_dt_and_more",
        ),
        ("campaign", "0010_rename_template_id_bmm_campanha_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bmm_boomerangue",
            name="campanha",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="campaign.bmm_campanha"
            ),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangue",
            name="condicoes_pagamento_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_empresas.ger_condicoespagamento",
            ),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangue",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_empresas.ger_empresas",
            ),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangue",
            name="entidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_entidades.ger_entidade",
            ),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangue",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="campaign.bmm_template"
            ),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueevento",
            name="boomerangue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="campaign.bmm_boomerangue",
            ),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueimportado",
            name="campanha",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="campaign.bmm_campanha"
            ),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens",
            name="boomerangue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="campaign.bmm_boomerangue",
            ),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens",
            name="produto",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_produtos.ger_produtos",
            ),
        ),
        migrations.AlterField(
            model_name="bmm_boomeranguelog",
            name="boomerangue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="campaign.bmm_boomerangue",
            ),
        ),
        migrations.AlterField(
            model_name="bmm_boomeranguelog",
            name="boomerangueitem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="campaign.bmm_boomerangueitens",
            ),
        ),
        migrations.AlterField(
            model_name="bmm_campanha",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_empresas.ger_empresas",
            ),
        ),
        migrations.AlterField(
            model_name="bmm_campanhaidentificadores",
            name="campanha",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="campaign.bmm_campanha"
            ),
        ),
        migrations.AlterField(
            model_name="bmm_regra",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_empresas.ger_empresas",
            ),
        ),
        migrations.AlterField(
            model_name="bmm_regra",
            name="templateconfirmacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="campaign.bmm_template"
            ),
        ),
        migrations.AlterField(
            model_name="bmm_regra_eventos",
            name="regra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="campaign.bmm_regra"
            ),
        ),
        migrations.AlterField(
            model_name="bmm_template",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_empresas.ger_empresas",
            ),
        ),
        migrations.AlterField(
            model_name="bmm_templateimportado",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="campaign.bmm_template"
            ),
        ),
    ]
