# Generated by Django 4.1.4 on 2023-11-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0011_bmm_campanha_tipo_campanha"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_campanha",
            name="data_fim",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="bmm_campanha",
            name="data_inicio",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="bmm_campanha",
            name="status_campanha",
            field=models.CharField(
                choices=[
                    ("AG", "Aguardando"),
                    ("EA", "Em Andamento"),
                    ("EC", "Encerrado"),
                ],
                default="AG",
                max_length=2,
            ),
        ),
    ]
