# Generated by Django 4.1.4 on 2023-11-08 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0012_bmm_campanha_data_fim_bmm_campanha_data_inicio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bmm_campanha",
            name="agendamento_clinica",
        ),
        migrations.RemoveField(
            model_name="bmm_campanha",
            name="agendamento_dentista",
        ),
        migrations.RemoveField(
            model_name="bmm_campanha",
            name="agendamento_hospital",
        ),
        migrations.RemoveField(
            model_name="bmm_campanha",
            name="agendamento_medico",
        ),
        migrations.RemoveField(
            model_name="bmm_campanha",
            name="distribuidora_caixa",
        ),
        migrations.RemoveField(
            model_name="bmm_campanha",
            name="distribuidora_combo",
        ),
        migrations.RemoveField(
            model_name="bmm_campanha",
            name="distribuidora_unitario",
        ),
        migrations.RemoveField(
            model_name="bmm_campanha",
            name="doacoes",
        ),
        migrations.RemoveField(
            model_name="bmm_campanha",
            name="industria_caixa",
        ),
        migrations.RemoveField(
            model_name="bmm_campanha",
            name="industria_combo",
        ),
        migrations.RemoveField(
            model_name="bmm_campanha",
            name="industria_unitario",
        ),
    ]
