# Generated by Django 4.1.4 on 2023-11-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0013_remove_bmm_campanha_agendamento_clinica_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_campanha",
            name="horario_fim",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="bmm_campanha",
            name="horario_inicio",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="bmm_campanha",
            name="data_fim",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="bmm_campanha",
            name="data_inicio",
            field=models.DateField(null=True),
        ),
    ]
