# Generated by Django 4.1.4 on 2023-11-08 20:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0011_alter_bmm_boomerangue_campanha_and_more"),
        (
            "campaign",
            "0014_bmm_campanha_horario_fim_bmm_campanha_horario_inicio_and_more",
        ),
    ]

    operations = []
