# Generated by Django 4.1.4 on 2023-11-09 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "ger_produtos",
            "0003_ger_produtos_alteracao_dt_ger_produtos_cadastro_dt_and_more",
        ),
        ("campaign", "0015_merge_20231108_2012"),
    ]

    operations = [
        migrations.CreateModel(
            name="bmm_boomerangueitens_templates",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("edi_integracao_item", models.CharField(max_length=50)),
                ("produto_original_id", models.CharField(max_length=50)),
                (
                    "quantidade_sugerida",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "quantidade_minima",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "quantidade_maxima",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "quantidade_disponivel",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "multiplo_boomerangue",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "multiplo_pague",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "valor_item_original",
                    models.DecimalField(decimal_places=6, max_digits=18),
                ),
                ("valor_atacado", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=6, max_digits=18),
                ),
                (
                    "valor_unitario_calculado",
                    models.DecimalField(decimal_places=6, max_digits=18),
                ),
                (
                    "valor_total_item",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "valor_sem_desconto",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "percentual_desconto",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                ("item_ativo", models.CharField(max_length=1)),
                ("ordem", models.CharField(max_length=4)),
                ("obrigatorio_compra", models.CharField(max_length=1)),
                ("unidade_caixa", models.CharField(max_length=10)),
                ("unidade_venda", models.CharField(max_length=10)),
                ("tipo_item_boomerangue_id", models.CharField(max_length=2, null=True)),
                ("produto_bloqueado", models.CharField(max_length=1)),
                ("complemento1", models.CharField(max_length=100, null=True)),
                (
                    "boomerangue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="campaign.bmm_boomerangue",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_produtos.ger_produtos",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="campaign.bmm_template",
                    ),
                ),
            ],
            options={
                "db_table": "bmm_boomerangueitens_templates",
            },
        ),
    ]
