# Generated by Django 4.1.4 on 2023-11-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0016_bmm_boomerangueitens_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bmm_boomerangueitens",
            name="edi_integracao_item",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens",
            name="item_ativo",
            field=models.CharField(default="S", max_length=1),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens",
            name="multiplo_boomerangue",
            field=models.DecimalField(decimal_places=4, default=1, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens",
            name="multiplo_pague",
            field=models.DecimalField(decimal_places=4, default=1, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens",
            name="obrigatorio_compra",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens",
            name="ordem",
            field=models.CharField(default=0.0, max_length=4),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens",
            name="percentual_desconto",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens",
            name="produto_bloqueado",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens",
            name="produto_original_id",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens",
            name="quantidade_disponivel",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens",
            name="quantidade_maxima",
            field=models.DecimalField(decimal_places=4, default=999999, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens",
            name="quantidade_minima",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens",
            name="quantidade_sugerida",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens",
            name="tipo_item_boomerangue_id",
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens",
            name="unidade_caixa",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens",
            name="unidade_venda",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens",
            name="valor_atacado",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens",
            name="valor_item_original",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens",
            name="valor_sem_desconto",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens",
            name="valor_total_item",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens",
            name="valor_unitario",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens",
            name="valor_unitario_calculado",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens_templates",
            name="edi_integracao_item",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens_templates",
            name="item_ativo",
            field=models.CharField(default="S", max_length=1),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens_templates",
            name="multiplo_boomerangue",
            field=models.DecimalField(decimal_places=4, default=1, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens_templates",
            name="multiplo_pague",
            field=models.DecimalField(decimal_places=4, default=1, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens_templates",
            name="obrigatorio_compra",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens_templates",
            name="ordem",
            field=models.CharField(default=0.0, max_length=4),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens_templates",
            name="percentual_desconto",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens_templates",
            name="produto_bloqueado",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens_templates",
            name="produto_original_id",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens_templates",
            name="quantidade_disponivel",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens_templates",
            name="quantidade_maxima",
            field=models.DecimalField(decimal_places=4, default=999999, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens_templates",
            name="quantidade_minima",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens_templates",
            name="quantidade_sugerida",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens_templates",
            name="tipo_item_boomerangue_id",
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens_templates",
            name="unidade_caixa",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens_templates",
            name="unidade_venda",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens_templates",
            name="valor_atacado",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens_templates",
            name="valor_item_original",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens_templates",
            name="valor_sem_desconto",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens_templates",
            name="valor_total_item",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens_templates",
            name="valor_unitario",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens_templates",
            name="valor_unitario_calculado",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
    ]
