# Generated by Django 4.1.4 on 2023-11-09 00:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0017_alter_bmm_boomerangueitens_edi_integracao_item_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="bmm_boomerangueitens_templates",
        ),
    ]
