# Generated by Django 4.1.4 on 2023-11-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0019_bmm_template_itens"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_templateimportado",
            name="tipo_arquivo",
            field=models.CharField(default="A Validar", max_length=20),
        ),
    ]
