# Generated by Django 4.1.4 on 2023-11-09 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0020_bmm_templateimportado_tipo_arquivo"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_template_itens",
            name="templateimportado",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="campaign.bmm_templateimportado",
            ),
        ),
    ]
