# Generated by Django 4.1.4 on 2023-11-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0021_bmm_template_itens_templateimportado"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_templateimportado",
            name="dtProcessamento",
            field=models.DateTimeField(null=True),
        ),
    ]
