# Generated by Django 4.1.4 on 2023-11-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0022_bmm_templateimportado_dtprocessamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_templateimportado",
            name="retorno_arquivo",
            field=models.TextField(max_length=100, null=True),
        ),
    ]
