# Generated by Django 4.1.4 on 2023-11-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0023_bmm_templateimportado_retorno_arquivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bmm_campanha",
            name="status_campanha",
            field=models.CharField(
                choices=[
                    ("AG", "Aguardando"),
                    ("EA", "Em Andamento"),
                    ("EC", "Encerrado"),
                    ("PA", "Pausada"),
                ],
                default="AG",
                max_length=2,
            ),
        ),
    ]
