# Generated by Django 4.1.4 on 2023-11-13 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_entidades", "0005_alter_ger_categoriaentidade_empresa_and_more"),
        ("campaign", "0025_bmm_templateimportado_alteracao_dt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bmm_boomeranguelog",
            name="entidade_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_entidades.ger_entidade",
            ),
        ),
    ]
