# Generated by Django 4.1.4 on 2023-11-14 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0026_alter_bmm_boomeranguelog_entidade_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_boomerangueitens",
            name="produto",
            field=models.ForeignKey(to='ger_produtos.ger_produtos', 
                                      on_delete=django.db.models.deletion.PROTECT, 
                                      null=True),
        ),
    ]
