# Generated by Django 4.1.4 on 2023-11-14 18:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0027_remove_bmm_boomerangueitens_produto_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="bmm_template_itens",
            table="bmm_template_itens",
        ),
    ]
