# Generated by Django 4.1.4 on 2023-11-14 18:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0028_alter_bmm_template_itens_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="bmm_template_itens",
            table="bmm_templateitens",
        ),
    ]
