# Generated by Django 4.1.4 on 2023-11-14 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0007_alter_ger_condicoespagamento_condicaopadrao_and_more"),
        (
            "ger_produtos",
            "0004_rename_edi_integracao_ger_produtos_edi_integracao_and_more",
        ),
        ("campaign", "0029_alter_bmm_template_itens_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bmm_boomerangue",
            old_name="condicoes_pagamento_id",
            new_name="condicoes_pagamento",
        ),
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="pedido",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="status_bot",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="status_bot_repique",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="tipo_frete",
            field=models.CharField(default="F", max_length=1),
        ),
        migrations.AddField(
            model_name="bmm_boomerangueimportado",
            name="dtProcessamento",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="bmm_boomerangueimportado",
            name="retorno_arquivo",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="bmm_boomerangueimportado",
            name="tipo_arquivo",
            field=models.CharField(default="A Validar", max_length=20),
        ),
        migrations.AddField(
            model_name="bmm_boomerangueitens",
            name="MultiploCaixa",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name="bmm_boomerangueitens",
            name="QuantidadeCompradaCX",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="bmm_boomerangueitens",
            name="QuantidadeCompradaUN",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="bmm_boomerangueitens",
            name="ValorMultimplicadorCompra",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="bmm_boomerangueitens",
            name="ValorTotalCompra",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="bmm_boomerangueitens",
            name="campanha",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="campaign.bmm_campanha",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bmm_boomerangueitens",
            name="pedido_item",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="bmm_template_itens",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_empresas.ger_empresas",
            ),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangue",
            name="bm_aceito",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangue",
            name="bm_com_erro",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangue",
            name="bm_modo_teste",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangue",
            name="compra_minima_qtd",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangue",
            name="compra_minima_vlr",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangue",
            name="desconto_promocional",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangue",
            name="dia_entrega_escolhe",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangue",
            name="nro_itens",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangue",
            name="prefixo",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangue",
            name="transportadora_escolhe",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangue",
            name="valor_atual",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangue",
            name="valor_original",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens",
            name="ordem",
            field=models.CharField(default="0000", max_length=4),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_produtos.ger_produtos",
            ),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens",
            name="quantidade_maxima",
            field=models.DecimalField(decimal_places=4, default=9999999, max_digits=18),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangueitens",
            name="tipo_item_boomerangue_id",
            field=models.CharField(default="UN", max_length=2),
        ),
        migrations.AlterField(
            model_name="bmm_campanha",
            name="tipo_campanha",
            field=models.CharField(
                choices=[
                    ("DUN", "Distribuidora Unitário"),
                    ("DCX", "Distribuidora Caixa"),
                    ("DCO", "Distribuidora Combo"),
                ],
                default="DUN",
                max_length=5,
            ),
        ),
        migrations.AddIndex(
            model_name="bmm_template_itens",
            index=models.Index(
                fields=["edi_integracao_item", "empresa"], name="bmm_upsert"
            ),
        ),
    ]
