# Generated by Django 4.1.4 on 2023-11-17 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "campaign",
            "0030_rename_condicoes_pagamento_id_bmm_boomerangue_condicoes_pagamento_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="bmm_boomerangueitens",
            old_name="pedido_item",
            new_name="pedidoitem_id",
        ),
    ]
