# Generated by Django 4.1.4 on 2023-11-20 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0031_rename_pedido_item_bmm_boomerangueitens_pedidoitem_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="TelefoneOriginal",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="boomerangueimportado_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="campaign.bmm_boomerangueimportado",
            ),
        ),
        migrations.AddField(
            model_name="bmm_boomerangueevento",
            name="campanha",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="campaign.bmm_campanha",
            ),
        ),
        migrations.AddField(
            model_name="bmm_campanha",
            name="EmFaseHomologacaoAteDt",
            field=models.DateField(null=True),
        ),
    ]
