# Generated by Django 4.1.4 on 2023-11-20 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0032_bmm_boomerangue_telefoneoriginal_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bmm_boomerangue",
            old_name="boomerangueimportado_id",
            new_name="boomerangueimportado",
        ),
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="TelefoneOriginal",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="bmm_boomerangueevento",
            name="campanha",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="campaign.bmm_campanha",
            ),
        ),
    ]
