# Generated by Django 4.1.4 on 2023-11-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "campaign",
            "0033_rename_boomerangueimportado_id_bmm_boomerangue_boomerangueimportado_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bmm_campanha",
            name="EmFaseHomologacaoAteDt",
            field=models.DateTimeField(null=True),
        ),
    ]
