# Generated by Django 4.1.4 on 2023-11-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0034_alter_bmm_campanha_emfasehomologacaoatedt"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_boomerangueimportado",
            name="alteracao_dt",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="bmm_boomerangueimportado",
            name="cadastro_dt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="bmm_boomerangueimportado",
            name="exclusao_dt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="bmm_boomerangueimportado",
            name="statusregistro_id",
            field=models.IntegerField(default=200),
        ),
    ]
