# Generated by Django 4.1.4 on 2023-11-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0035_bmm_boomerangueimportado_alteracao_dt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="bmstatus",
            field=models.CharField(max_length=1, null=True),
        ),
    ]
