# Generated by Django 4.1.4 on 2023-11-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0036_bmm_boomerangue_bmstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_boomerangueitens",
            name="valor_total_compra",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
