# Generated by Django 4.1.4 on 2023-11-24 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0037_bmm_boomerangueitens_valor_total_compra"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bmm_boomerangueitens",
            name="valor_total_compra",
        ),
    ]
