# Generated by Django 4.1.4 on 2023-11-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0038_remove_bmm_boomerangueitens_valor_total_compra"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="dt_integracao",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="status_integracao",
            field=models.CharField(default=0, max_length=1),
        ),
    ]
