# Generated by Django 4.1.4 on 2023-11-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0039_bmm_boomerangue_dt_integracao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_boomerangueitens",
            name="alteracao_dt",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="bmm_boomerangueitens",
            name="cadastro_dt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="bmm_boomerangueitens",
            name="exclusao_dt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="bmm_boomerangueitens",
            name="statusregistro_id",
            field=models.IntegerField(default=200),
        ),
    ]
