# Generated by Django 4.1.4 on 2023-11-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0040_bmm_boomerangueitens_alteracao_dt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_boomerangueitens",
            name="MaiorQuantidade",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bmm_boomerangueitens",
            name="ValorUnitarioOriginal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="bmm_boomerangueitens",
            name="dataintegracaoitem",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="bmm_boomerangueitens",
            name="dtPrimeiroAcesso",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="bmm_boomerangueitens",
            name="dtUltimoAcesso",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="bmm_boomerangueitens",
            name="pdComissaoItem",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="bmm_boomerangueitens",
            name="statusintegracaoitem",
            field=models.CharField(default=0, max_length=1),
        ),
    ]
