# Generated by Django 4.1.4 on 2023-11-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0041_bmm_boomerangueitens_maiorquantidade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="ComissaoPD",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="ComissaoProdutos",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="ComissaoValor",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="TotalAcrescimo",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="TotalBoomerangue",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="TotalCupom",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="TotalDesconto",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="TotalFidelidade",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="TotalFrete",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="TotalProdutos",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="TotalQuantidade",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="TotalServicos",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
