# Generated by Django 4.1.4 on 2023-11-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0042_bmm_boomerangue_comissaopd_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_boomerangueitens",
            name="pdComissaoItemVlr",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
