# Generated by Django 4.1.4 on 2023-11-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0043_bmm_boomerangueitens_pdcomissaoitemvlr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bmm_boomeranguelog",
            name="Complemento1",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="bmm_boomeranguelog",
            name="Complemento2",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="bmm_boomeranguelog",
            name="Complemento3",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="bmm_boomeranguelog",
            name="DataLog",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="bmm_boomeranguelog",
            name="Telefone",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="bmm_boomeranguelog",
            name="Template",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="bmm_boomeranguelog",
            name="TempoLog",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="bmm_boomeranguelog",
            name="Token",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="bmm_boomeranguelog",
            name="acao_id",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="bmm_boomeranguelog",
            name="acaoenviada_id",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="bmm_boomeranguelog",
            name="boomerangueimportacao_id",
            field=models.IntegerField(null=True),
        ),
    ]
