# Generated by Django 4.1.4 on 2023-11-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0044_alter_bmm_boomeranguelog_complemento1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bmm_boomeranguelog",
            name="VerApiLog",
            field=models.CharField(max_length=3, null=True),
        ),
    ]
