# Generated by Django 4.1.4 on 2023-11-28 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0045_alter_bmm_boomeranguelog_verapilog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bmm_boomeranguelog",
            name="boomerangueitem",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="campaign.bmm_boomerangueitens",
            ),
        ),
        migrations.AlterField(
            model_name="bmm_boomeranguelog",
            name="origemlog_id",
            field=models.CharField(max_length=1, null=True),
        ),
    ]
