# Generated by Django 4.1.4 on 2023-12-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0046_alter_bmm_boomeranguelog_boomerangueitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_template",
            name="image_footer",
            field=models.ImageField(
                max_length=400, null=True, upload_to="media/image_footer/"
            ),
        ),
    ]
