# Generated by Django 4.1.4 on 2023-12-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0047_bmm_template_image_footer"),
    ]

    operations = [
        migrations.CreateModel(
            name="ger_opcoes_padrao",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "imagem_footer_padrao",
                    models.ImageField(
                        max_length=400, null=True, upload_to="media/image_footer/"
                    ),
                ),
                ("link_footer_padrao", models.CharField(max_length=400, null=True)),
            ],
        ),
    ]
