# Generated by Django 4.1.4 on 2023-12-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0048_ger_opcoes_padrao"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_opcoes_padrao",
            name="alteracao_dt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_opcoes_padrao",
            name="cadastro_dt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_opcoes_padrao",
            name="exclusao_dt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ger_opcoes_padrao",
            name="statusregistro_id",
            field=models.IntegerField(default=200),
        ),
    ]
