# Generated by Django 4.1.4 on 2023-12-04 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0007_alter_ger_condicoespagamento_condicaopadrao_and_more"),
        ("campaign", "0049_ger_opcoes_padrao_alteracao_dt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_opcoes_padrao",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_empresas.ger_empresas",
            ),
        ),
    ]
