# Generated by Django 4.1.4 on 2023-12-05 22:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0050_ger_opcoes_padrao_empresa"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="ger_opcoes_padrao",
            table="ger_opcoes_padrao",
        ),
    ]
