# Generated by Django 4.1.4 on 2023-12-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0051_alter_ger_opcoes_padrao_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_template",
            name="ItensNoTemplate",
            field=models.CharField(default="N", max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="bmm_template",
            name="LeadNoTemplate",
            field=models.CharField(default="N", max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="bmm_template",
            name="UsaSugestaoIA",
            field=models.CharField(default="N", max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="bmm_template",
            name="template_regra_id",
            field=models.CharField(
                choices=[("PD", "Padrao")], default="PD", max_length=10, null=True
            ),
        ),
    ]
