# Generated by Django 4.1.4 on 2024-01-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0052_bmm_template_itensnotemplate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_template",
            name="Ativo",
            field=models.CharField(default="S", max_length=1, null=True),
        ),
    ]
