# Generated by Django 4.1.4 on 2024-01-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0053_bmm_template_ativo"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="bm_status",
            field=models.CharField(default="W", max_length=1),
        ),
    ]
