# Generated by Django 4.1.4 on 2024-01-16 18:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0054_bmm_boomerangue_bm_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bmm_campanha",
            name="tipo_campanha",
        ),
    ]
