# Generated by Django 4.1.4 on 2024-01-16 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0019_select_tipo_campanha"),
        ("campaign", "0055_remove_bmm_campanha_tipo_campanha"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_campanha",
            name="tipo_campanha",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ger_empresas.select_tipo_campanha",
            ),
        ),
    ]
