# Generated by Django 4.1.4 on 2024-04-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0056_bmm_campanha_tipo_campanha"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_boomerangueimportado",
            name="envio_msg",
            field=models.CharField(default="N", max_length=1),
        ),
    ]
