# Generated by Django 4.1.4 on 2024-04-08 19:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0057_bmm_boomerangueimportado_envio_msg"),
        ("campaign", "0057_bmm_campanha_carrinhoabandonado_and_more"),
    ]

    operations = []
