# Generated by Django 4.1.4 on 2024-04-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0058_merge_20240408_1944"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bmm_boomerangueevento",
            name="DataGeracao",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
