# Generated by Django 4.1.4 on 2024-04-12 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0059_alter_bmm_boomerangueevento_datageracao"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_boomeranguelog",
            name="campanha",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="campaign.bmm_campanha",
            ),
        ),
        migrations.AddField(
            model_name="bmm_boomeranguelog",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="campaign.bmm_template",
            ),
        ),
        migrations.AlterField(
            model_name="bmm_boomeranguelog",
            name="boomerangue",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="campaign.bmm_boomerangue",
            ),
        ),
    ]
