# Generated by Django 4.1.4 on 2024-04-12 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_entidades", "0008_ger_entidade_dataconfirmacaowp_and_more"),
        ("campaign", "0060_bmm_boomeranguelog_campanha_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bmm_boomeranguelog",
            name="entidade_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_entidades.ger_entidade",
            ),
        ),
    ]
