# Generated by Django 4.1.4 on 2024-04-12 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("campaign", "0061_alter_bmm_boomeranguelog_entidade_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_boomeranguelog",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
