# Generated by Django 4.1.4 on 2024-04-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0062_bmm_boomeranguelog_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_template",
            name="campanha_motivo",
            field=models.CharField(
                choices=[
                    ("VDP", "Vendas de Produtos"),
                    ("VDS", "Vendas de Serviço"),
                    ("MKT", "Campanha de Marketing"),
                ],
                default="VDP",
                max_length=3,
                null=True,
            ),
        ),
    ]
