# Generated by Django 4.1.4 on 2024-04-30 19:02

import boomerangue.apps.campaign.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0063_bmm_template_campanha_motivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bmm_template",
            name="image_footer",
            field=models.FileField(
                max_length=400,
                null=True,
                upload_to="media/image_footer/",
                validators=[boomerangue.apps.campaign.models.ValidateSVG()],
            ),
        ),
        migrations.AlterField(
            model_name="ger_opcoes_padrao",
            name="imagem_footer_padrao",
            field=models.FileField(
                max_length=400,
                null=True,
                upload_to="media/image_footer/",
                validators=[boomerangue.apps.campaign.models.ValidateSVG()],
            ),
        ),
    ]
