# Generated by Django 4.1.4 on 2024-05-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0064_alter_bmm_template_image_footer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_campanha",
            name="ultimo_cnpj_processado",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
