# Generated by Django 4.1.4 on 2024-05-31 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "gateway_pagamento",
            "0003_gateway_pagamento_certificados_senhas_url_and_more",
        ),
        ("campaign", "0065_bmm_campanha_ultimo_cnpj_processado"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_campanha",
            name="gateway_pagamento",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gateway_pagamento.gateway_pagamento",
            ),
        ),
    ]
