# Generated by Django 4.1.4 on 2024-07-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0066_bmm_campanha_gateway_pagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_campanha",
            name="statusregistro_id",
            field=models.IntegerField(default=200),
        ),
    ]
