# Generated by Django 4.1.4 on 2024-07-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0067_bmm_campanha_statusregistro_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_campanha",
            name="cadastro_dt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="bmm_campanha",
            name="status_validacao",
            field=models.CharField(default="N", max_length=1),
        ),
    ]
