# Generated by Django 4.1.4 on 2024-07-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0068_bmm_campanha_cadastro_dt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_campanha",
            name="custo_total",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="bmm_campanha",
            name="desvio_padrao",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="bmm_campanha",
            name="mensagens_enviadas",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bmm_campanha",
            name="mensagens_reenviadas",
            field=models.IntegerField(default=0),
        ),
    ]
