# Generated by Django 4.1.4 on 2024-07-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "campaign",
            "0069_bmm_campanha_custo_total_bmm_campanha_desvio_padrao_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_campanha",
            name="NroLeadsValidos",
            field=models.IntegerField(null=True),
        ),
    ]
