# Generated by Django 4.1.4 on 2024-07-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0070_bmm_campanha_nroleadsvalidos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bmm_campanha",
            name="NroLeadsValidos",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
