# Generated by Django 4.1.4 on 2024-08-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0071_alter_bmm_campanha_nroleadsvalidos"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_boomeranguelog",
            name="valor",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
