# Generated by Django 4.1.4 on 2024-09-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0072_bmm_boomeranguelog_valor"),
    ]

    operations = [
        migrations.CreateModel(
            name="agendamento",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("confirma_whatsapp", models.DateTimeField(null=True)),
                ("data_consulta", models.DateTimeField()),
                ("medico", models.IntegerField(null=True)),
                ("paciente", models.IntegerField()),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField(default=200)),
            ],
            options={
                "db_table": "agendamento",
            },
        ),
    ]
