# Generated by Django 4.1.4 on 2024-09-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0073_agendamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="data_consulta",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="hora_consulta",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="nome_medico",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
