# Generated by Django 4.1.4 on 2024-09-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0074_bmm_boomerangue_data_consulta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="bm_tipo",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
