# Generated by Django 4.1.4 on 2024-10-03 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0075_bmm_boomerangue_bm_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bmm_boomerangue",
            name="campanha",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="campaign.bmm_campanha",
            ),
        ),
        migrations.AlterField(
            model_name="bmm_boomerangue",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="campaign.bmm_template",
            ),
        ),
    ]
