# Generated by Django 4.1.4 on 2024-10-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0076_alter_bmm_boomerangue_campanha_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bmm_boomerangue",
            name="edi_integracao",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
