# Generated by Django 4.1.4 on 2024-10-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0077_alter_bmm_boomerangue_edi_integracao"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="data_limite_consulta",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="bmm_boomerangue",
            name="hora_limite_consulta",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
