# Generated by Django 4.1.4 on 2024-11-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0078_bmm_boomerangue_data_limite_consulta_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bmm_boomeranguelog",
            name="valor",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=18, null=True
            ),
        ),
    ]
