# Generated by Django 4.1.4 on 2023-10-05 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ger_empresas", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="ger_cidade",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("Cidade", models.CharField(max_length=100)),
                ("CodIBGE", models.CharField(max_length=10, null=True)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True, null=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True, null=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField(default=200)),
            ],
            options={
                "db_table": "ger_cidade",
            },
        ),
        migrations.CreateModel(
            name="ger_dadosgerais",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("grupo", models.CharField(max_length=255)),
                ("texto", models.CharField(max_length=255)),
                ("valornumerico", models.IntegerField(null=True)),
                (
                    "valorfinanceiro",
                    models.DecimalField(decimal_places=6, max_digits=18, null=True),
                ),
                ("valortexto", models.CharField(max_length=255, null=True)),
                ("ordem", models.IntegerField()),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField()),
            ],
            options={
                "db_table": "ger_dadosgerais",
            },
        ),
        migrations.CreateModel(
            name="ger_marcas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("EDI_Integracao", models.CharField(max_length=50, null=True)),
                ("Marca", models.CharField(max_length=50)),
                ("Site", models.CharField(max_length=100)),
                ("LogoMarca", models.CharField(max_length=200)),
                ("MarcaPadrao", models.CharField(max_length=1)),
                ("OrdemMarca", models.CharField(max_length=4)),
                ("Sincronizado", models.CharField(max_length=1)),
                ("dtSincronizacao", models.DateTimeField()),
                ("verSincronizador", models.CharField(max_length=12)),
                ("idSincronizador", models.IntegerField()),
            ],
            options={
                "db_table": "ger_marcas",
            },
        ),
        migrations.CreateModel(
            name="ger_mesoregiao",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("MesoRegiao", models.CharField(max_length=50)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField(default=200)),
            ],
            options={
                "db_table": "ger_mesoregiao",
            },
        ),
        migrations.CreateModel(
            name="ger_pais",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("Pais", models.CharField(max_length=50)),
                ("moeda_id", models.IntegerField(default=1)),
                ("SiglaPais", models.CharField(max_length=3, null=True)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField(default=200)),
            ],
            options={
                "db_table": "ger_pais",
            },
        ),
        migrations.CreateModel(
            name="ger_regiao",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("Regiao", models.CharField(max_length=50)),
                ("RegiaoReduzida", models.CharField(max_length=20)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField(default=200)),
                (
                    "pais_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_dadosgerais.ger_pais",
                    ),
                ),
            ],
            options={
                "db_table": "ger_regiao",
            },
        ),
        migrations.CreateModel(
            name="ger_tabelaprecos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("TabelaPreco", models.CharField(max_length=100)),
                ("TabelaAtiva", models.CharField(default="S", max_length=1)),
                ("TabelaPadrao", models.CharField(default="S", max_length=1)),
                ("ExportaTabelaPreco", models.CharField(default="S", max_length=1)),
                ("EDI_Integracao", models.CharField(max_length=50, null=True)),
                ("Sincronizado", models.CharField(default="S", max_length=1)),
                ("dtSincronizacao", models.DateTimeField(null=True)),
                (
                    "Sincronizador_ver",
                    models.CharField(default="00.0000.0000", max_length=12),
                ),
                ("Sincronizador_id", models.IntegerField(null=True)),
                (
                    "empresa_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
            ],
            options={
                "db_table": "ger_tabelaprecos",
            },
        ),
        migrations.CreateModel(
            name="ger_transportadora",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("EDI_Integracao", models.CharField(max_length=50, null=True)),
                ("Transportadora", models.CharField(max_length=100)),
                ("TransportadoraAtivo", models.CharField(default="S", max_length=1)),
                ("TransportadoraPadrao", models.CharField(default="N", max_length=1)),
                ("Sincronizado", models.CharField(default="S", max_length=1)),
                ("dtSincronizacao", models.DateTimeField(null=True)),
                (
                    "Sincronizador_ver",
                    models.CharField(default="00.0000.0000", max_length=12),
                ),
                ("Sincronizador_id", models.IntegerField(null=True)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True, null=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True, null=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField(default=200)),
                (
                    "empresa_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
            ],
            options={
                "db_table": "ger_transportadora",
            },
        ),
        migrations.CreateModel(
            name="ger_vendedores",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("CodigoVendedor", models.CharField(max_length=25, null=True)),
                ("Vendedor", models.CharField(max_length=50)),
                ("VendedorBM", models.CharField(max_length=50, null=True)),
                ("VendedorOriginal", models.CharField(max_length=50, null=True)),
                ("Apelido", models.CharField(max_length=40)),
                (
                    "LegendaVendedor",
                    models.CharField(default="Seu Vendedor", max_length=50),
                ),
                ("TelefoneVendedor", models.CharField(max_length=25)),
                ("VendedorPadrao", models.CharField(default="N", max_length=1)),
                ("Integracao_EDI", models.CharField(max_length=50, null=True)),
                ("Integracao_EDI2", models.CharField(max_length=50, null=True)),
                (
                    "ComissaoVenda",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=18),
                ),
                ("MarcaPadrao", models.CharField(max_length=50, null=True)),
                ("Sincronizado", models.CharField(default="S", max_length=1)),
                ("dtSincronizacao", models.DateTimeField(null=True)),
                (
                    "Sincronizador_ver",
                    models.CharField(default="00.0000.0000", max_length=12),
                ),
                ("Sincronizador_id", models.IntegerField(null=True)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True, null=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True, null=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField(default=200)),
                (
                    "CondicaoPgtoPadrao_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_empresas.ger_condicoespagamento",
                    ),
                ),
                (
                    "TabelaPrecoPadrao_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_dadosgerais.ger_tabelaprecos",
                    ),
                ),
                (
                    "TransportadoraPadrao_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_dadosgerais.ger_transportadora",
                    ),
                ),
                (
                    "empresa_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
            ],
            options={
                "db_table": "ger_vendedores",
            },
        ),
        migrations.CreateModel(
            name="ger_unidademedida",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("EDI_Integracao", models.CharField(max_length=50, null=True)),
                ("UnidadeMedida", models.CharField(max_length=50)),
                ("Sigla", models.CharField(max_length=50)),
                ("Sincronizado", models.CharField(max_length=1)),
                ("dtSincronizacao", models.DateTimeField()),
                ("verSincronizador", models.CharField(max_length=12)),
                ("idSincronizador", models.IntegerField()),
                (
                    "empresa_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
            ],
            options={
                "db_table": "ger_unidademedida",
            },
        ),
        migrations.CreateModel(
            name="ger_uf",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uf", models.CharField(max_length=50)),
                ("sigla", models.CharField(max_length=10)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField(default=200)),
                (
                    "pais_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_dadosgerais.ger_pais",
                    ),
                ),
                (
                    "regiao_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_dadosgerais.ger_regiao",
                    ),
                ),
            ],
            options={
                "db_table": "ger_uf",
            },
        ),
        migrations.CreateModel(
            name="ger_rotavenda",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("RotaVenda", models.CharField(max_length=50)),
                ("RotaPadrao", models.CharField(default="S", max_length=1)),
                ("RotaAtiva", models.CharField(default="S", max_length=1)),
                ("DiaEntrega_id", models.SmallIntegerField(default=0)),
                ("Integracao_EDI", models.CharField(max_length=50, null=True)),
                ("Sincronizado", models.CharField(default="S", max_length=1)),
                ("dtSincronizacao", models.DateTimeField(null=True)),
                (
                    "Sincronizador_ver",
                    models.CharField(default="00.0000.0000", max_length=12),
                ),
                ("Sincronizador_id", models.IntegerField(null=True)),
                (
                    "empresa_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
            ],
            options={
                "db_table": "ger_rotavenda",
            },
        ),
        migrations.CreateModel(
            name="ger_parceiros",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=40)),
                ("parceiro_apelido", models.CharField(max_length=20)),
                ("parceiro_ativo", models.CharField(default="S", max_length=1)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField(default=200)),
                (
                    "cidade_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_dadosgerais.ger_cidade",
                    ),
                ),
            ],
            options={
                "db_table": "ger_parceiros",
            },
        ),
        migrations.AddIndex(
            model_name="ger_pais",
            index=models.Index(fields=["Pais"], name="idx_pais_unique"),
        ),
        migrations.AddField(
            model_name="ger_mesoregiao",
            name="uf_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="ger_dadosgerais.ger_uf"
            ),
        ),
        migrations.AddField(
            model_name="ger_marcas",
            name="empresa_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_empresas.ger_empresas",
            ),
        ),
        migrations.AddIndex(
            model_name="ger_dadosgerais",
            index=models.Index(fields=["grupo"], name="ger_dadosge_grupo_7cd4a4_idx"),
        ),
        migrations.AddIndex(
            model_name="ger_dadosgerais",
            index=models.Index(
                fields=["grupo", "texto"], name="ger_dadosge_grupo_20b468_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ger_dadosgerais",
            index=models.Index(
                fields=["grupo", "valornumerico"], name="ger_dadosge_grupo_566f8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ger_dadosgerais",
            index=models.Index(
                fields=["grupo", "valorfinanceiro"], name="ger_dadosge_grupo_3852f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ger_dadosgerais",
            index=models.Index(
                fields=["grupo", "valortexto"], name="ger_dadosge_grupo_a7048b_idx"
            ),
        ),
        migrations.AddField(
            model_name="ger_cidade",
            name="MesoRegiao_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_dadosgerais.ger_mesoregiao",
            ),
        ),
        migrations.AddField(
            model_name="ger_cidade",
            name="pais_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_dadosgerais.ger_pais",
            ),
        ),
        migrations.AddField(
            model_name="ger_cidade",
            name="uf_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="ger_dadosgerais.ger_uf"
            ),
        ),
        migrations.AddIndex(
            model_name="ger_vendedores",
            index=models.Index(fields=["id"], name="ger_vendedo_id_8161ec_idx"),
        ),
        migrations.AddIndex(
            model_name="ger_vendedores",
            index=models.Index(fields=["empresa_id", "Integracao_EDI"], name="EDI1"),
        ),
        migrations.AddIndex(
            model_name="ger_vendedores",
            index=models.Index(fields=["empresa_id", "Integracao_EDI2"], name="EDI2"),
        ),
        migrations.AddIndex(
            model_name="ger_vendedores",
            index=models.Index(fields=["empresa_id", "id"], name="EDI3"),
        ),
        migrations.AddIndex(
            model_name="ger_unidademedida",
            index=models.Index(fields=["id"], name="ger_unidade_id_35cc2f_idx"),
        ),
        migrations.AddIndex(
            model_name="ger_unidademedida",
            index=models.Index(
                fields=["empresa_id"], name="ger_unidade_empresa_d51852_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ger_unidademedida",
            index=models.Index(fields=["empresa_id", "EDI_Integracao"], name="ixEdi"),
        ),
        migrations.AddIndex(
            model_name="ger_unidademedida",
            index=models.Index(fields=["UnidadeMedida"], name="ixUnidadeMedida"),
        ),
        migrations.AddIndex(
            model_name="ger_uf",
            index=models.Index(fields=["id"], name="ger_uf_id_ac25c4_idx"),
        ),
        migrations.AddIndex(
            model_name="ger_transportadora",
            index=models.Index(fields=["id"], name="ger_transpo_id_6c6b2b_idx"),
        ),
        migrations.AddIndex(
            model_name="ger_transportadora",
            index=models.Index(fields=["empresa_id", "EDI_Integracao"], name="ixEDI"),
        ),
        migrations.AddIndex(
            model_name="ger_transportadora",
            index=models.Index(fields=["Transportadora", "empresa_id"], name="ixNome"),
        ),
        migrations.AddIndex(
            model_name="ger_tabelaprecos",
            index=models.Index(
                fields=["empresa_id"], name="ger_tabelap_empresa_25c7fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ger_tabelaprecos",
            index=models.Index(fields=["id"], name="ger_tabelap_id_6843b8_idx"),
        ),
        migrations.AddIndex(
            model_name="ger_tabelaprecos",
            index=models.Index(
                fields=["empresa_id", "ExportaTabelaPreco"],
                name="ger_tabelap_empresa_277377_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ger_tabelaprecos",
            index=models.Index(
                fields=["ExportaTabelaPreco"], name="ger_tabelap_Exporta_cb5df9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ger_tabelaprecos",
            index=models.Index(
                fields=["empresa_id", "TabelaPreco"],
                name="ger_tabelap_empresa_bda266_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ger_rotavenda",
            index=models.Index(
                fields=["empresa_id"], name="ger_rotaven_empresa_ed2b38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ger_rotavenda",
            index=models.Index(fields=["id"], name="ger_rotaven_id_84d159_idx"),
        ),
        migrations.AddIndex(
            model_name="ger_regiao",
            index=models.Index(fields=["id"], name="ger_regiao_id_83296f_idx"),
        ),
        migrations.AddIndex(
            model_name="ger_parceiros",
            index=models.Index(fields=["id"], name="ger_parceir_id_8e70c9_idx"),
        ),
        migrations.AddIndex(
            model_name="ger_mesoregiao",
            index=models.Index(fields=["id"], name="ger_mesoreg_id_738265_idx"),
        ),
        migrations.AddIndex(
            model_name="ger_marcas",
            index=models.Index(fields=["id"], name="ger_marcas_id_90e499_idx"),
        ),
        migrations.AddIndex(
            model_name="ger_marcas",
            index=models.Index(fields=["empresa_id", "EDI_Integracao"], name="UMARCA"),
        ),
        migrations.AddIndex(
            model_name="ger_marcas",
            index=models.Index(fields=["Marca"], name="IMARCAS1"),
        ),
        migrations.AddIndex(
            model_name="ger_cidade",
            index=models.Index(fields=["id"], name="ger_cidade_id_00598f_idx"),
        ),
        migrations.AddIndex(
            model_name="ger_cidade",
            index=models.Index(
                fields=["CodIBGE"], name="ger_cidade_CodIBGE_ea1878_idx"
            ),
        ),
    ]
