# Generated by Django 4.1.4 on 2023-11-07 13:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ger_dadosgerais", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ger_cidade",
            old_name="MesoRegiao_id",
            new_name="MesoRegiao",
        ),
        migrations.RenameField(
            model_name="ger_cidade",
            old_name="pais_id",
            new_name="pais",
        ),
        migrations.RenameField(
            model_name="ger_cidade",
            old_name="uf_id",
            new_name="uf",
        ),
        migrations.RenameField(
            model_name="ger_marcas",
            old_name="empresa_id",
            new_name="empresa",
        ),
        migrations.RenameField(
            model_name="ger_mesoregiao",
            old_name="uf_id",
            new_name="uf",
        ),
        migrations.RenameField(
            model_name="ger_parceiros",
            old_name="cidade_id",
            new_name="cidade",
        ),
        migrations.RenameField(
            model_name="ger_regiao",
            old_name="pais_id",
            new_name="pais",
        ),
        migrations.RenameField(
            model_name="ger_rotavenda",
            old_name="empresa_id",
            new_name="empresa",
        ),
        migrations.RenameField(
            model_name="ger_tabelaprecos",
            old_name="empresa_id",
            new_name="empresa",
        ),
        migrations.RenameField(
            model_name="ger_transportadora",
            old_name="empresa_id",
            new_name="empresa",
        ),
        migrations.RenameField(
            model_name="ger_uf",
            old_name="pais_id",
            new_name="pais",
        ),
        migrations.RenameField(
            model_name="ger_uf",
            old_name="regiao_id",
            new_name="regiao",
        ),
        migrations.RenameField(
            model_name="ger_unidademedida",
            old_name="empresa_id",
            new_name="empresa",
        ),
        migrations.RenameField(
            model_name="ger_vendedores",
            old_name="empresa_id",
            new_name="empresa",
        ),
        migrations.RenameIndex(
            model_name="ger_rotavenda",
            new_name="ger_rotaven_empresa_9585c1_idx",
            old_name="ger_rotaven_empresa_ed2b38_idx",
        ),
        migrations.RenameIndex(
            model_name="ger_tabelaprecos",
            new_name="ger_tabelap_empresa_0f94b3_idx",
            old_name="ger_tabelap_empresa_25c7fa_idx",
        ),
        migrations.RenameIndex(
            model_name="ger_tabelaprecos",
            new_name="ger_tabelap_empresa_8a980a_idx",
            old_name="ger_tabelap_empresa_277377_idx",
        ),
        migrations.RenameIndex(
            model_name="ger_tabelaprecos",
            new_name="ger_tabelap_empresa_e8440f_idx",
            old_name="ger_tabelap_empresa_bda266_idx",
        ),
        migrations.RenameIndex(
            model_name="ger_unidademedida",
            new_name="ger_unidade_empresa_d34e07_idx",
            old_name="ger_unidade_empresa_d51852_idx",
        ),
    ]
