# Generated by Django 4.1.4 on 2023-11-07 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ger_dadosgerais", "0002_rename_mesoregiao_id_ger_cidade_mesoregiao_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ger_vendedores",
            old_name="CondicaoPgtoPadrao_id",
            new_name="CondicaoPgtoPadrao",
        ),
        migrations.RenameField(
            model_name="ger_vendedores",
            old_name="TabelaPrecoPadrao_id",
            new_name="TabelaPrecoPadrao",
        ),
        migrations.RenameField(
            model_name="ger_vendedores",
            old_name="TransportadoraPadrao_id",
            new_name="TransportadoraPadrao",
        ),
    ]
