# Generated by Django 4.1.4 on 2023-11-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ger_dadosgerais",
            "0003_rename_condicaopgtopadrao_id_ger_vendedores_condicaopgtopadrao_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_vendedores",
            name="ComissaoVenda",
            field=models.DecimalField(
                decimal_places=4, default=0.0, max_digits=18, null=True
            ),
        ),
    ]
