# Generated by Django 4.1.4 on 2023-11-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_dadosgerais", "0004_alter_ger_vendedores_comissaovenda"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_vendedores",
            name="ComissaoVenda",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=18),
        ),
    ]
