# Generated by Django 4.1.4 on 2023-11-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_dadosgerais", "0005_alter_ger_vendedores_comissaovenda"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_marcas",
            name="alteracao_dt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_marcas",
            name="cadastro_dt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_marcas",
            name="exclusao_dt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ger_marcas",
            name="statusregistro_id",
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name="ger_rotavenda",
            name="alteracao_dt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_rotavenda",
            name="cadastro_dt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_rotavenda",
            name="exclusao_dt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ger_rotavenda",
            name="statusregistro_id",
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name="ger_tabelaprecos",
            name="alteracao_dt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_tabelaprecos",
            name="cadastro_dt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_tabelaprecos",
            name="exclusao_dt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ger_tabelaprecos",
            name="statusregistro_id",
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name="ger_unidademedida",
            name="alteracao_dt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_unidademedida",
            name="cadastro_dt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_unidademedida",
            name="exclusao_dt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ger_unidademedida",
            name="statusregistro_id",
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name="ger_marcas",
            name="LogoMarca",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="ger_marcas",
            name="MarcaPadrao",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="ger_marcas",
            name="OrdemMarca",
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="ger_marcas",
            name="Sincronizado",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="ger_marcas",
            name="Site",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ger_marcas",
            name="dtSincronizacao",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="ger_marcas",
            name="idSincronizador",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ger_marcas",
            name="verSincronizador",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="ger_rotavenda",
            name="Sincronizado",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="ger_rotavenda",
            name="Sincronizador_ver",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="ger_tabelaprecos",
            name="Sincronizado",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="ger_tabelaprecos",
            name="Sincronizador_ver",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="ger_transportadora",
            name="Sincronizado",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="ger_transportadora",
            name="Sincronizador_ver",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="ger_unidademedida",
            name="Sincronizado",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="ger_unidademedida",
            name="dtSincronizacao",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="ger_unidademedida",
            name="idSincronizador",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ger_unidademedida",
            name="verSincronizador",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="ger_vendedores",
            name="Sincronizado",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="ger_vendedores",
            name="Sincronizador_ver",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="ger_vendedores",
            name="TelefoneVendedor",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
