# Generated by Django 4.1.4 on 2023-11-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ger_dadosgerais",
            "0006_ger_marcas_alteracao_dt_ger_marcas_cadastro_dt_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ger_distribuidor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("distribuidor", models.CharField(max_length=200, null=True)),
                ("cod_puxada", models.CharField(max_length=20, null=True)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True, null=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True, null=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField(default=200)),
            ],
        ),
    ]
