# Generated by Django 4.1.4 on 2023-11-30 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ger_dadosgerais", "0007_ger_distribuidor"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="ger_distribuidor",
            table="ger_distribuidor",
        ),
    ]
