# Generated by Django 4.1.4 on 2024-11-18 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_dadosgerais", "0008_alter_ger_distribuidor_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="ger_dados_cep",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cep", models.CharField(max_length=200, null=True)),
                ("logradouro", models.CharField(max_length=200, null=True)),
                ("complemento", models.CharField(max_length=200, null=True)),
                ("localidade", models.CharField(max_length=200, null=True)),
                ("unidade", models.CharField(max_length=200, null=True)),
                ("ibge", models.CharField(max_length=200, null=True)),
                ("gia", models.CharField(max_length=200, null=True)),
                (
                    "uf",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ger_dadosgerais.ger_uf",
                    ),
                ),
            ],
            options={
                "db_table": "ger_dados_cep",
            },
        ),
        migrations.AddIndex(
            model_name="ger_dados_cep",
            index=models.Index(fields=["id"], name="ger_dados_c_id_413913_idx"),
        ),
        migrations.AddIndex(
            model_name="ger_dados_cep",
            index=models.Index(fields=["cep"], name="ger_dados_c_cep_96ed81_idx"),
        ),
    ]
