# Generated by Django 4.1.4 on 2024-11-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_dadosgerais", "0009_ger_dados_cep_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_dados_cep",
            name="bairro",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
