# Generated by Django 4.1.4 on 2023-10-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ger_grade",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("empresa_id", models.PositiveIntegerField()),
                ("EDI_Integracao", models.CharField(max_length=50)),
                ("Grade", models.CharField(max_length=50)),
                ("Caracteristica_id", models.BigIntegerField()),
                ("NroInicial", models.SmallIntegerField()),
                ("NroFinal", models.SmallIntegerField()),
                ("Grade01", models.CharField(blank=True, max_length=50)),
                ("Grade02", models.CharField(blank=True, max_length=50)),
                ("Grade03", models.CharField(blank=True, max_length=50)),
                ("Grade04", models.CharField(blank=True, max_length=50)),
                ("Grade05", models.CharField(blank=True, max_length=50)),
                ("Grade06", models.CharField(blank=True, max_length=50)),
                ("Grade07", models.CharField(blank=True, max_length=50)),
                ("Grade08", models.CharField(blank=True, max_length=50)),
                ("Grade09", models.CharField(blank=True, max_length=50)),
                ("Grade10", models.CharField(blank=True, max_length=50)),
                ("Grade11", models.CharField(blank=True, max_length=50)),
                ("Grade12", models.CharField(blank=True, max_length=50)),
                ("Grade13", models.CharField(blank=True, max_length=50)),
                ("Grade14", models.CharField(blank=True, max_length=50)),
                ("Grade15", models.CharField(blank=True, max_length=50)),
                ("Grade16", models.CharField(blank=True, max_length=50)),
                ("Grade17", models.CharField(blank=True, max_length=50)),
                ("Grade18", models.CharField(blank=True, max_length=50)),
                ("Grade19", models.CharField(blank=True, max_length=50)),
                ("Grade20", models.CharField(blank=True, max_length=50)),
                ("Grade21", models.CharField(blank=True, max_length=50)),
                ("Grade22", models.CharField(blank=True, max_length=50)),
                ("Grade23", models.CharField(blank=True, max_length=50)),
                ("Grade24", models.CharField(blank=True, max_length=50)),
                ("Grade25", models.CharField(blank=True, max_length=50)),
                ("Sincronizado", models.CharField(max_length=1)),
                ("dtSincronizacao", models.DateTimeField(auto_now_add=True)),
                ("verSincronizador", models.CharField(max_length=12)),
                ("idSincronizador", models.PositiveIntegerField()),
            ],
        ),
    ]
