# Generated by Django 4.1.4 on 2023-10-26 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0003_alter_ger_condicoespagamento_empresa"),
        ("ger_grade", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_grade",
            name="alteracao_dt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_grade",
            name="exclusao_dt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ger_grade",
            name="statusregistro_id",
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name="ger_grade",
            name="Caracteristica_id",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ger_grade",
            name="EDI_Integracao",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ger_grade",
            name="Grade",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ger_grade",
            name="NroFinal",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ger_grade",
            name="NroInicial",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ger_grade",
            name="Sincronizado",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="ger_grade",
            name="empresa_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ger_empresas.ger_empresas",
            ),
        ),
        migrations.AlterField(
            model_name="ger_grade",
            name="idSincronizador",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ger_grade",
            name="verSincronizador",
            field=models.CharField(max_length=12, null=True),
        ),
    ]
