# Generated by Django 4.1.4 on 2023-10-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_grade", "0002_ger_grade_alteracao_dt_ger_grade_exclusao_dt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_grade",
            name="cadastro_dt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
