# Generated by Django 4.1.4 on 2023-11-07 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ger_grade", "0003_ger_grade_cadastro_dt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ger_grade",
            old_name="empresa_id",
            new_name="empresa",
        ),
        migrations.AlterModelTable(
            name="ger_grade",
            table="ger_grade",
        ),
    ]
