# Generated by Django 4.1.4 on 2023-11-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_grade", "0004_rename_empresa_id_ger_grade_empresa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_grade",
            name="Sincronizado",
            field=models.CharField(default="N", max_length=1),
        ),
    ]
