# Generated by Django 4.1.4 on 2024-01-11 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ger_empresas", "0012_ger_empresas_botnumerovalidacao"),
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MsgMessage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("flow_id", models.IntegerField(null=True)),
                ("direcao", models.CharField(default="I", max_length=1)),
                ("instancia", models.CharField(max_length=100)),
                ("message_id", models.CharField(max_length=100)),
                ("message_reference_id", models.CharField(max_length=100)),
                ("evento1", models.CharField(max_length=100)),
                ("evento2", models.CharField(max_length=100)),
                ("Sender", models.CharField(max_length=100)),
                ("SenderName", models.CharField(max_length=100, null=True)),
                ("Receiver", models.CharField(max_length=100)),
                ("ReceiverName", models.CharField(max_length=100, null=True)),
                ("MensagemTexto", models.TextField(null=True)),
                ("URL_Anexo", models.CharField(max_length=150, null=True)),
                ("ButtonListSeletec", models.CharField(max_length=255)),
                ("DataHoraDoEvento", models.DateTimeField(auto_now_add=True)),
                ("DataHoraProgramada", models.DateTimeField(auto_now_add=True)),
                ("DataHoraEnvio", models.DateTimeField(null=True)),
                ("StatusEnvio", models.CharField(default="A", max_length=1)),
                ("StatusMensagem", models.CharField(default="N", max_length=1)),
                ("StatusFlow", models.CharField(default="W", max_length=1)),
                ("Delivered", models.CharField(default="N", max_length=1)),
                ("DataHoraDelivered", models.DateTimeField(null=True)),
                ("Received", models.CharField(default="N", max_length=1)),
                ("DataHoraReceived", models.DateTimeField(null=True)),
                ("Read", models.CharField(default="N", max_length=1)),
                ("DataHoraRead", models.DateTimeField(null=True)),
                ("Reply", models.CharField(default="N", max_length=1)),
                ("DataHoraReply", models.DateTimeField(null=True)),
                ("Removed", models.CharField(default="N", max_length=1)),
                ("DataHoraRemoved", models.DateTimeField(null=True)),
                ("OrigemMensagem", models.CharField(default="AUTO", max_length=25)),
                ("TipoMensagem", models.CharField(default="T", max_length=2)),
                ("NroCreditos", models.IntegerField(default=1)),
                ("EDI_Integracao", models.CharField(max_length=100, null=True)),
                ("MsgProgramada", models.CharField(default="S", max_length=1)),
                ("MensagemCancelada", models.CharField(default="N", max_length=1)),
                ("MensagemComErro", models.CharField(default="N", max_length=1)),
                ("VerAPI", models.CharField(max_length=10, null=True)),
                ("owner", models.CharField(max_length=100, null=True)),
                ("source", models.CharField(max_length=100, null=True)),
                ("FromMe", models.CharField(default="N", max_length=1)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="bot.bot"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
            ],
            options={
                "db_table": "msg_message",
            },
        ),
    ]
