# Generated by Django 4.1.4 on 2024-02-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg_messages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msgmessage",
            name="ButtonListSeletec",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="msgmessage",
            name="DataHoraProgramada",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="msgmessage",
            name="message_reference_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
