# Generated by Django 4.1.4 on 2024-02-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg_messages", "0002_alter_msgmessage_buttonlistseletec_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msgmessage",
            name="URL_Anexo",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
