# Generated by Django 4.1.4 on 2024-04-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg_messages", "0003_alter_msgmessage_url_anexo"),
    ]

    operations = [
        migrations.AddField(
            model_name="msgmessage",
            name="chave_integracao",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="msgmessage",
            name="complemento1",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="msgmessage",
            name="complemento2",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="msgmessage",
            name="complemento3",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="msgmessage",
            name="complemento4",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="msgmessage",
            name="complemento5",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="msgmessage",
            name="complemento6",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="msgmessage",
            name="complemento7",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="msgmessage",
            name="complemento8",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="msgmessage",
            name="complemento9",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
