# Generated by Django 4.1.4 on 2024-04-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "msg_messages",
            "0004_msgmessage_chave_integracao_msgmessage_complemento1_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="msgmessage",
            name="nome_anexo",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
