# Generated by Django 4.1.4 on 2024-05-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg_messages", "0005_msgmessage_nome_anexo"),
    ]

    operations = [
        migrations.AddField(
            model_name="msgmessage",
            name="context",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
