# Generated by Django 4.1.4 on 2024-07-12 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_entidades", "0019_ger_entidade_lead_key_spl"),
        ("campaign", "0068_bmm_campanha_cadastro_dt_and_more"),
        ("msg_messages", "0006_msgmessage_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="msgmessage",
            name="boomerangue",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="campaign.bmm_boomerangue",
            ),
        ),
        migrations.AddField(
            model_name="msgmessage",
            name="campanha",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="campaign.bmm_campanha",
            ),
        ),
        migrations.AddField(
            model_name="msgmessage",
            name="conteudo",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="msgmessage",
            name="custo_mensagem",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="msgmessage",
            name="entidade",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_entidades.ger_entidade",
            ),
        ),
        migrations.AddField(
            model_name="msgmessage",
            name="flag_revisao",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="msgmessage",
            name="flow_id",
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.CreateModel(
            name="log_mensagens",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("data_evento", models.DateTimeField(auto_now_add=True)),
                ("descricao", models.TextField()),
                (
                    "mensagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="msg_messages.msgmessage",
                    ),
                ),
            ],
        ),
    ]
