# Generated by Django 4.1.4 on 2024-07-12 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("msg_messages", "0007_msgmessage_boomerangue_msgmessage_campanha_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="log_mensagens",
            table="log_mensagens",
        ),
    ]
