# Generated by Django 4.1.4 on 2024-07-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg_messages", "0008_alter_log_mensagens_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msgmessage",
            name="custo_mensagem",
            field=models.DecimalField(
                decimal_places=6, default=0, max_digits=18, null=True
            ),
        ),
    ]
