# Generated by Django 4.1.4 on 2024-07-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg_messages", "0009_alter_msgmessage_custo_mensagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="msgmessage",
            name="origemdados",
            field=models.CharField(
                choices=[
                    ("N", "nao definido"),
                    ("W", "WebHook"),
                    ("M", "API Msg_Create"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
