# Generated by Django 4.1.4 on 2024-07-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg_messages", "0010_msgmessage_origemdados"),
    ]

    operations = [
        migrations.AddField(
            model_name="msgmessage",
            name="alteracao_dt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="msgmessage",
            name="cadastro_dt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="msgmessage",
            name="exclusao_dt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="msgmessage",
            name="statusregistro_id",
            field=models.IntegerField(default=200, null=True),
        ),
    ]
