# Generated by Django 4.1.4 on 2024-07-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "msg_messages",
            "0011_msgmessage_alteracao_dt_msgmessage_cadastro_dt_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="msgmessage",
            name="proxima_msg",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
