# Generated by Django 4.1.4 on 2024-07-18 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("msg_messages", "0012_msgmessage_proxima_msg"),
    ]

    operations = [
        migrations.RenameField(
            model_name="msgmessage",
            old_name="Read",
            new_name="mRead",
        ),
    ]
