# Generated by Django 4.1.4 on 2024-07-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg_messages", "0013_rename_read_msgmessage_mread"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msgmessage",
            name="MensagemTexto",
            field=models.TextField(db_collation="utf8mb4_unicode_ci", null=True),
        ),
    ]
