# Generated by Django 4.1.4 on 2024-07-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg_messages", "0014_alter_msgmessage_mensagemtexto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msgmessage",
            name="MensagemTexto",
            field=models.TextField(null=True),
        ),
    ]
