# Generated by Django 4.1.4 on 2024-07-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg_messages", "0015_alter_msgmessage_mensagemtexto"),
    ]

    operations = [
        migrations.AddField(
            model_name="msgmessage",
            name="mensagem_tratada",
            field=models.CharField(default="N", max_length=1, null=True),
        ),
    ]
