# Generated by Django 4.1.4 on 2024-07-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg_messages", "0016_msgmessage_mensagem_tratada"),
    ]

    operations = [
        migrations.AddField(
            model_name="log_mensagens",
            name="status_mensagem",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
