# Generated by Django 4.1.4 on 2024-08-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg_messages", "0017_log_mensagens_status_mensagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="msgmessage",
            name="doc_validado",
            field=models.CharField(default="N", max_length=1, null=True),
        ),
    ]
