# Generated by Django 4.1.4 on 2024-08-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg_messages", "0018_msgmessage_doc_validado"),
    ]

    operations = [
        migrations.AddField(
            model_name="msgmessage",
            name="msg_lida",
            field=models.CharField(default="N", max_length=1, null=True),
        ),
    ]
