# Generated by Django 4.1.4 on 2024-08-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg_messages", "0019_msgmessage_msg_lida"),
    ]

    operations = [
        migrations.AddField(
            model_name="msgmessage",
            name="notificado",
            field=models.BooleanField(default=False),
        ),
    ]
