# Generated by Django 4.1.4 on 2024-08-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg_messages", "0020_msgmessage_notificado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msgmessage",
            name="notificado",
            field=models.CharField(default="N", max_length=1, null=True),
        ),
    ]
