# Generated by Django 4.1.4 on 2024-09-17 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ger_entidades", "0023_ger_entidade_keysearchmessage_and_more"),
        ("msg_messages", "0021_alter_msgmessage_notificado"),
    ]

    operations = [
        migrations.CreateModel(
            name="canais",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("canal_nome", models.CharField(max_length=50)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True, null=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True, null=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField(default=200, null=True)),
            ],
            options={
                "db_table": "canais",
            },
        ),
        migrations.CreateModel(
            name="usuario_lead",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True, null=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True, null=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField(default=200, null=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_entidades.ger_entidade",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "usuario_lead",
            },
        ),
        migrations.CreateModel(
            name="canais_leads",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True, null=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True, null=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField(default=200, null=True)),
                (
                    "canal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="msg_messages.canais",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_entidades.ger_entidade",
                    ),
                ),
            ],
            options={
                "db_table": "canais_leads",
            },
        ),
    ]
