# Generated by Django 4.1.4 on 2024-09-18 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0033_alter_ger_empresas_empresa"),
        ("msg_messages", "0022_canais_usuario_lead_canais_leads"),
    ]

    operations = [
        migrations.AddField(
            model_name="canais",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ger_empresas.ger_empresas",
            ),
        ),
    ]
