# Generated by Django 4.1.4 on 2023-11-07 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("campaign", "0010_rename_template_id_bmm_campanha_template"),
        ("wpp_templates", "0002_alter_wpp_templates_statusregistro_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="bmm_campanhas_msgs",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "usotemplate",
                    models.CharField(
                        choices=[("OPTIN", "Optin"), ("ENVIO", "Envio")], max_length=5
                    ),
                ),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True)),
                ("alteracao_dt", models.DateTimeField(null=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField(default=200)),
                (
                    "campanha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaign.bmm_campanha",
                    ),
                ),
                (
                    "wpptemplate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wpp_templates.wpp_templates",
                    ),
                ),
            ],
        ),
    ]
