# Generated by Django 4.1.4 on 2023-11-08 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bmm_campanhas_msgs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="bmm_campanhas_msgs",
            table="bmm_campanhas_msgs",
        ),
    ]
