# Generated by Django 4.1.4 on 2024-04-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bmm_campanhas_msgs", "0002_alter_bmm_campanhas_msgs_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bmm_campanhas_msgs",
            name="usotemplate",
            field=models.CharField(
                choices=[("OPTIN", "Optin"), ("ENVIO", "Envio"), ("Teste", "Teste")],
                max_length=5,
            ),
        ),
    ]
