# Generated by Django 4.1.4 on 2024-04-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bmm_campanhas_msgs", "0003_alter_bmm_campanhas_msgs_usotemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bmm_campanhas_msgs",
            name="usotemplate",
            field=models.CharField(
                choices=[
                    ("OPTIN", "Optin"),
                    ("ENVIO", "Envio"),
                    ("REP1", "Repique 1"),
                    ("REP2", "Repique 2"),
                    ("CRABN", "Carrinho Abandonado"),
                    ("CPRCB", "Compra Recebida"),
                ],
                max_length=5,
            ),
        ),
    ]
