# Generated by Django 4.1.4 on 2024-11-18 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ger_produtos", "0007_ger_produtos_saldo"),
        ("ger_entidades", "0026_alter_ger_entidade_limite_de_credito_and_more"),
        ("ger_empresas", "0034_ger_empresas_template_envio_clinica_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="historico_vendasimportado",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tipo_arquivo", models.CharField(default="A Validar", max_length=20)),
                ("NomeArquivo", models.CharField(max_length=200)),
                (
                    "Caminho",
                    models.FileField(null=True, upload_to="media/arq_historico/"),
                ),
                ("DataHora", models.DateTimeField(auto_now=True)),
                ("retorno_arquivo", models.TextField(max_length=100, null=True)),
                ("dtProcessamento", models.DateTimeField(null=True)),
                ("statusarquivo_id", models.CharField(max_length=1)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True, null=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True, null=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField(default=200)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
            ],
            options={
                "db_table": "historico_vendasimportado",
            },
        ),
        migrations.CreateModel(
            name="bmm_historico",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("edi_integracao", models.CharField(max_length=100, null=True)),
                ("tipo_historico", models.CharField(max_length=10, null=True)),
                ("nfe", models.CharField(max_length=50, null=True)),
                ("pedido", models.CharField(max_length=50, null=True)),
                ("dt_emissao", models.DateTimeField(null=True)),
                ("dt_saida", models.DateTimeField(blank=True, null=True)),
                ("edi_condpgto", models.CharField(max_length=50, null=True)),
                ("cond_pgto", models.CharField(max_length=200, null=True)),
                ("fob", models.CharField(default="F", max_length=1)),
                (
                    "total_produtos",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total_nota", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_pedido", models.DecimalField(decimal_places=2, max_digits=10)),
                ("nronotas", models.IntegerField()),
                (
                    "total_desconto",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("tipovenda", models.CharField(max_length=10, null=True)),
                ("autonumerador", models.IntegerField(blank=True, null=True)),
                ("canal_vendas", models.CharField(max_length=100, null=True)),
                ("Representante", models.CharField(max_length=100, null=True)),
                (
                    "categoriaentidade",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_entidades.ger_categoriaentidade",
                    ),
                ),
                (
                    "condicoespagamento",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_empresas.ger_condicoespagamento",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
                (
                    "entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_entidades.ger_entidade",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_produtos.ger_produtos",
                    ),
                ),
            ],
            options={
                "db_table": "bmm_historico",
            },
        ),
        migrations.AddIndex(
            model_name="bmm_historico",
            index=models.Index(
                fields=["edi_integracao"], name="bmm_histori_edi_int_3b7dae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bmm_historico",
            index=models.Index(
                fields=["tipo_historico"], name="bmm_histori_tipo_hi_afb1f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bmm_historico",
            index=models.Index(fields=["nfe"], name="bmm_histori_nfe_3eda8a_idx"),
        ),
        migrations.AddIndex(
            model_name="bmm_historico",
            index=models.Index(fields=["pedido"], name="bmm_histori_pedido_553240_idx"),
        ),
        migrations.AddIndex(
            model_name="bmm_historico",
            index=models.Index(
                fields=["dt_emissao"], name="bmm_histori_dt_emis_5eef9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bmm_historico",
            index=models.Index(
                fields=["dt_saida"], name="bmm_histori_dt_said_3ff1d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bmm_historico",
            index=models.Index(
                fields=["edi_condpgto"], name="bmm_histori_edi_con_eb4a74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bmm_historico",
            index=models.Index(
                fields=["cond_pgto"], name="bmm_histori_cond_pg_1facfe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bmm_historico",
            index=models.Index(fields=["fob"], name="bmm_histori_fob_e08499_idx"),
        ),
        migrations.AddIndex(
            model_name="bmm_historico",
            index=models.Index(
                fields=["total_produtos"], name="bmm_histori_total_p_af4626_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bmm_historico",
            index=models.Index(
                fields=["total_nota"], name="bmm_histori_total_n_928173_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bmm_historico",
            index=models.Index(
                fields=["total_pedido"], name="bmm_histori_total_p_06cd00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bmm_historico",
            index=models.Index(
                fields=["nronotas"], name="bmm_histori_nronota_317bcd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bmm_historico",
            index=models.Index(
                fields=["total_desconto"], name="bmm_histori_total_d_f41f5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bmm_historico",
            index=models.Index(
                fields=["tipovenda"], name="bmm_histori_tipoven_f23fa3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bmm_historico",
            index=models.Index(
                fields=["empresa"], name="bmm_histori_empresa_07c98c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bmm_historico",
            index=models.Index(
                fields=["entidade"], name="bmm_histori_entidad_969d65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bmm_historico",
            index=models.Index(
                fields=["categoriaentidade"], name="bmm_histori_categor_d0d214_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bmm_historico",
            index=models.Index(
                fields=["condicoespagamento"], name="bmm_histori_condico_803d48_idx"
            ),
        ),
    ]
