# Generated by Django 4.1.4 on 2024-11-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("historico_vendas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bmm_historico",
            name="total_pedido",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
