# Generated by Django 4.1.4 on 2024-06-13 18:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("campaign", "0066_bmm_campanha_gateway_pagamento"),
        ("ger_empresas", "0031_alter_ger_empresas_image_logo_empresa"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContaBancaria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("banco_codigo", models.CharField(max_length=10)),
                ("agencia", models.CharField(max_length=10)),
                ("conta", models.CharField(max_length=20)),
                ("chave_pix", models.CharField(blank=True, max_length=77, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolicitacaoPagamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_vencimento", models.DateField(blank=True, null=True)),
                (
                    "tipo_pagamento",
                    models.CharField(
                        choices=[
                            ("PIX", "Pix"),
                            ("CARTAO", "Cartão"),
                            ("BOLETO", "Boleto"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "recorrencia",
                    models.CharField(
                        choices=[
                            ("UNICO", "Único"),
                            ("PARCELADO", "Parcelado"),
                            ("RECORRENTE", "Recorrente"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "boomerangue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="campaign.bmm_boomerangue",
                    ),
                ),
                (
                    "conta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pix_transactions.contabancaria",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("APROVADO", "Aprovado"),
                            ("REJEITADO", "Rejeitado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        max_length=10,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_transacao", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "boomerangue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="campaign.bmm_boomerangue",
                    ),
                ),
                (
                    "solicitacao_pagamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pix_transactions.solicitacaopagamento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recebimento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("RECEBIMENTO", "Recebimento"),
                            ("CANCELAMENTO", "Cancelamento"),
                        ],
                        max_length=13,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_recebimento", models.DateTimeField(auto_now_add=True)),
                (
                    "solicitacao_pagamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pix_transactions.solicitacaopagamento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LogTransacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("mensagem", models.TextField()),
                ("data_log", models.DateTimeField(auto_now_add=True)),
                (
                    "boomerangue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="campaign.bmm_boomerangue",
                    ),
                ),
                (
                    "transacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pix_transactions.transacao",
                    ),
                ),
            ],
        ),
    ]
