# Generated by Django 4.1.4 on 2024-06-13 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0031_alter_ger_empresas_image_logo_empresa"),
        ("pix_transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contabancaria",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_empresas.ger_empresas",
            ),
        ),
        migrations.AlterField(
            model_name="logtransacao",
            name="transacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="pix_transactions.transacao",
            ),
        ),
        migrations.AlterField(
            model_name="recebimento",
            name="solicitacao_pagamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="pix_transactions.solicitacaopagamento",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaopagamento",
            name="conta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="pix_transactions.contabancaria",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaopagamento",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_empresas.ger_empresas",
            ),
        ),
        migrations.AlterField(
            model_name="transacao",
            name="solicitacao_pagamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="pix_transactions.solicitacaopagamento",
            ),
        ),
    ]
