# Generated by Django 4.1.4 on 2024-06-13 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gateway_pagamento", "0004_gateway_pagamento_client_id_and_more"),
        ("pix_transactions", "0002_alter_contabancaria_empresa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitacaopagamento",
            name="conta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="gateway_pagamento.gateway_pagamento",
            ),
        ),
        migrations.DeleteModel(
            name="ContaBancaria",
        ),
    ]
