# Generated by Django 4.1.4 on 2024-06-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pix_transactions", "0003_alter_solicitacaopagamento_conta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaopagamento",
            name="txid",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
