# Generated by Django 4.1.4 on 2024-06-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pix_transactions", "0004_solicitacaopagamento_txid"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaopagamento",
            name="copia_e_cola",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="solicitacaopagamento",
            name="expire_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
