# Generated by Django 4.1.4 on 2024-06-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pix_transactions", "0005_solicitacaopagamento_copia_e_cola_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitacaopagamento",
            name="expire_at",
            field=models.IntegerField(null=True),
        ),
    ]
