# Generated by Django 4.1.4 on 2024-06-13 18:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0066_bmm_campanha_gateway_pagamento"),
        ("pix_transactions", "0006_alter_solicitacaopagamento_expire_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogSolicitacaoPagamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("mensagem", models.TextField(null=True)),
                ("acao", models.TextField(null=True)),
                ("data_log", models.DateTimeField(auto_now_add=True)),
                (
                    "boomerangue",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="campaign.bmm_boomerangue",
                    ),
                ),
                (
                    "solicitacao_pagamento",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pix_transactions.solicitacaopagamento",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="LogTransacao",
        ),
    ]
