# Generated by Django 4.1.4 on 2024-06-13 19:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("pix_transactions", "0007_logsolicitacaopagamento_delete_logtransacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitacaopagamento",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=36,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
