# Generated by Django 4.1.4 on 2024-06-13 19:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("pix_transactions", "0008_alter_solicitacaopagamento_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logsolicitacaopagamento",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=36,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="recebimento",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=36,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="transacao",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=36,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
