# Generated by Django 4.1.4 on 2024-06-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pix_transactions", "0009_alter_logsolicitacaopagamento_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaopagamento",
            name="data_transacao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitacaopagamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("APROVADO", "Aprovado"),
                    ("REJEITADO", "Rejeitado"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="PENDENTE",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="Transacao",
        ),
    ]
