# Generated by Django 4.1.4 on 2024-06-18 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pix_transactions", "0010_solicitacaopagamento_data_transacao_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="solicitacaopagamento",
            old_name="data_transacao",
            new_name="data_tx",
        ),
    ]
