# Generated by Django 4.1.4 on 2024-06-18 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_entidades", "0015_ger_entidade_estagio_flow"),
        ("pix_transactions", "0011_rename_data_transacao_solicitacaopagamento_data_tx"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaopagamento",
            name="lead",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_entidades.ger_entidade",
            ),
        ),
    ]
