# Generated by Django 4.1.4 on 2024-06-18 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pix_transactions", "0012_solicitacaopagamento_lead"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solicitacaopagamento",
            name="lead",
        ),
    ]
