# Generated by Django 4.1.4 on 2024-08-06 20:29

import boomerangue.apps.pix_transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pix_transactions", "0013_remove_solicitacaopagamento_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaopagamento",
            name="import_comprovante",
            field=models.FileField(
                null=True,
                storage=boomerangue.apps.pix_transactions.models.WasabiStorage(),
                upload_to="comprovante/",
            ),
        ),
        migrations.AddField(
            model_name="solicitacaopagamento",
            name="import_comprovante_url",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
