# Generated by Django 4.1.4 on 2024-08-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pix_transactions", "0014_solicitacaopagamento_import_comprovante_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaopagamento",
            name="id_identificador",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
