# Generated by Django 4.1.4 on 2024-08-27 17:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pix_transactions", "0015_solicitacaopagamento_id_identificador"),
    ]

    operations = [
        migrations.RenameField(
            model_name="solicitacaopagamento",
            old_name="id_identificador",
            new_name="id_txid",
        ),
    ]
