# Generated by Django 4.1.4 on 2024-09-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pix_transactions",
            "0016_rename_id_identificador_solicitacaopagamento_id_txid",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitacaopagamento",
            name="data_vencimento",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
