# Generated by Django 4.1.4 on 2023-10-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="wpp_templateapprovals",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("template_id", models.IntegerField()),
                ("aprovado_por", models.CharField(max_length=255)),
                (
                    "status_aprovacao",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Aprovado", "Aprovado"),
                            ("Rejeitado", "Rejeitado"),
                        ],
                        default="Pendente",
                        max_length=10,
                    ),
                ),
                ("data_aprovacao", models.DateTimeField()),
                ("comentarios_aprovacao", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True)),
                ("exclusao_dt", models.DateTimeField(blank=True, null=True)),
                ("statusregistro_id", models.IntegerField()),
            ],
        ),
    ]
