# Generated by Django 4.1.4 on 2023-11-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templateapprovals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wpp_templateapprovals",
            name="statusregistro_id",
            field=models.IntegerField(default=200),
        ),
        migrations.AlterModelTable(
            name="wpp_templateapprovals",
            table="wpp_templateapprovals",
        ),
    ]
