# Generated by Django 4.1.4 on 2023-11-08 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0003_wpp_templates_empresa"),
        (
            "wpp_templateapprovals",
            "0002_alter_wpp_templateapprovals_statusregistro_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="wpp_templateapprovals",
            name="aprovado_por",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="wpp_templateapprovals",
            name="data_aprovacao",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="wpp_templateapprovals",
            name="template_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wpp_templates.wpp_templates",
            ),
        ),
    ]
