# Generated by Django 4.1.4 on 2023-10-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="wpp_templatescomponents",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("template_id", models.IntegerField()),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("HEADER", "HEADER"),
                            ("BODY", "BODY"),
                            ("FOOTER", "FOOTER"),
                            ("BUTTONS", "BUTTONS"),
                            ("LIST", "LIST"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("TEXT", "TEXT"),
                            ("IMAGE", "IMAGE"),
                            ("DOCUMENT", "DOCUMENT"),
                            ("VIDEO", "VIDEO"),
                            ("LOCATION", "LOCATION"),
                        ],
                        max_length=20,
                    ),
                ),
                ("text_content", models.TextField(blank=True, null=True)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True)),
                ("exclusao_dt", models.DateTimeField(blank=True, null=True)),
                ("statusregistro_id", models.IntegerField()),
            ],
        ),
    ]
