# Generated by Django 4.1.4 on 2023-11-07 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0002_alter_wpp_templates_statusregistro_id_and_more"),
        ("wpp_templatescomponents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wpp_templatescomponents",
            name="template_id",
        ),
        migrations.AddField(
            model_name="wpp_templatescomponents",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wpp_templates.wpp_templates",
            ),
        ),
        migrations.AlterModelTable(
            name="wpp_templatescomponents",
            table="wpp_templatescomponents",
        ),
    ]
