# Generated by Django 4.1.4 on 2023-11-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "wpp_templatescomponents",
            "0002_remove_wpp_templatescomponents_template_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="wpp_templatescomponents",
            name="statusregistro_id",
            field=models.IntegerField(default=200),
        ),
    ]
