# Generated by Django 4.1.4 on 2024-03-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "wpp_templatescomponents",
            "0003_alter_wpp_templatescomponents_statusregistro_id",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="wpp_templatescomponents",
            name="text_content",
            field=models.TextField(
                blank=True, db_collation="utf8mb4_unicode_ci", null=True
            ),
        ),
    ]
