# Generated by Django 4.1.4 on 2024-04-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templatescomponents", "0004_alter_wpp_templatescomponents_text_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="wpp_templatescomponents",
            name="image_content",
            field=models.ImageField(
                max_length=400, null=True, upload_to="media/whatsappImages/"
            ),
        ),
    ]
