# Generated by Django 4.1.4 on 2024-04-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templatescomponents", "0005_wpp_templatescomponents_image_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="termos_sendpulse_troca",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("termo_sendpulse", models.CharField(max_length=30, null=True)),
                ("termo_troca", models.CharField(max_length=30, null=True)),
                (
                    "component",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wpp_templatescomponents.wpp_templatescomponents",
                    ),
                ),
            ],
            options={
                "db_table": "termos_sendpulse_troca",
            },
        ),
    ]
