# Generated by Django 4.1.4 on 2024-05-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templatescomponents", "0006_termos_sendpulse_troca"),
    ]

    operations = [
        migrations.AddField(
            model_name="wpp_templatescomponents",
            name="url_formatada",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
