# Generated by Django 4.1.4 on 2024-06-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templatescomponents", "0007_wpp_templatescomponents_url_formatada"),
    ]

    operations = [
        migrations.AddField(
            model_name="wpp_templatescomponents",
            name="possui_qrcode_pix",
            field=models.CharField(default="N", max_length=1),
        ),
    ]
