# Generated by Django 4.1.4 on 2024-06-25 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templatescomponents", "0008_wpp_templatescomponents_possui_qrcode_pix"),
    ]

    operations = [
        migrations.CreateModel(
            name="fluxo_sendpulse",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("fluxo_id", models.CharField(max_length=500, null=True)),
                (
                    "component",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wpp_templatescomponents.wpp_templatescomponents",
                    ),
                ),
            ],
            options={
                "db_table": "fluxo_sendpulse",
            },
        ),
    ]
