# Generated by Django 4.1.4 on 2024-07-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templatescomponents", "0009_fluxo_sendpulse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wpp_templatescomponents",
            name="url_formatada",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
