# Generated by Django 4.1.4 on 2024-04-22 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bot", "0023_bot_ftp_bot_ftp_config_alter_bot_bot_tipo"),
        ("ger_empresas", "0030_ger_empresas_max_tokens_ia"),
    ]

    operations = [
        migrations.CreateModel(
            name="SofBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_id",
                    models.CharField(
                        choices=[
                            ("C", "Consulta"),
                            ("M", "Menu"),
                            ("G", "Mensagem"),
                            ("P", "Push"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "tipolista_id",
                    models.CharField(
                        choices=[
                            ("LI", "Lista"),
                            ("BU", "Botões"),
                            ("ME", "Menu numerado"),
                        ],
                        max_length=2,
                    ),
                ),
                ("comando", models.CharField(max_length=20, unique=True)),
                (
                    "tipoConexao",
                    models.CharField(
                        choices=[("G", "GET"), ("P", "POST")], max_length=1
                    ),
                ),
                ("conexaoUrl", models.CharField(max_length=500)),
                ("header", models.TextField()),
                ("body", models.TextField()),
                ("response", models.TextField()),
                ("numerosOK", models.TextField()),
                ("numerosError", models.TextField()),
                (
                    "diassemanaexecutar",
                    models.CharField(default="0111110", max_length=7),
                ),
                ("iniciaenvios", models.CharField(default="00", max_length=2)),
                ("finalenvios", models.CharField(default="00", max_length=2)),
                (
                    "enviarhorafixa",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("opcaomenu", models.CharField(default="1", max_length=2)),
                ("ativo", models.CharField(default="S", max_length=1)),
                ("dataultimoenvio", models.DateTimeField(blank=True, null=True)),
                ("dataproximoenvio", models.DateTimeField(blank=True, null=True)),
                ("dataultimaconsulta", models.DateTimeField(blank=True, null=True)),
                ("dataultimoerro", models.DateTimeField(blank=True, null=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bot.bot"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
                (
                    "menubot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sofbot.sofbot",
                    ),
                ),
            ],
            options={
                "verbose_name": "SofBot",
                "verbose_name_plural": "SofBots",
                "db_table": "sofbot",
            },
        ),
    ]
