"""
Django settings for zeta project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

CSRF_TRUSTED_ORIGINS = ['https://*.boomerangue.me']

ALLOWED_HOSTS = ["*", "localhost", "*.localhost", "boomerangue.me", "*.boomerangue.me"]
# ALLOWED_HOSTS = ["*", "localhost", "*.localhost", "beta.boomerangue.app", "*.beta.boomerangue.app"]



# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "boomerangue",
    "rest_framework",
    "api",
    "sass_processor",
    "login",
    "ia",
    "boomerangue.apps.b2b",
    "boomerangue.apps.bot",
    "boomerangue.apps.bot_canal",
    "boomerangue.apps.bot_canalempresa",
    "boomerangue.apps.bot_provedor",
    "boomerangue.apps.campaign",
    "boomerangue.apps.ger_categorias",
    "boomerangue.apps.ger_dadosgerais",
    "boomerangue.apps.ger_empresas",
    "boomerangue.apps.ger_entidades",
    "boomerangue.apps.ger_grade",
    "boomerangue.apps.ger_grupoprodutos",
    "boomerangue.apps.ger_linhaprodutos",
    "boomerangue.apps.ger_produtos",
    "boomerangue.apps.wpp_templateapprovals",
    "boomerangue.apps.wpp_templatebuttons",
    "boomerangue.apps.wpp_templatelistitems",
    "boomerangue.apps.wpp_templates",
    "boomerangue.apps.wpp_templatescomponents",
    "boomerangue.apps.bmm_campanhas_msgs",
    "boomerangue.apps.bmm_template_msgs",
    "boomerangue.apps.historico_vendas",
    "boomerangue.apps.msg_messages",
    "boomerangue.apps.empresas_log",
    "boomerangue.apps.sofbot",
    "boomerangue.apps.gateway_pagamento",
    "boomerangue.apps.pix_transactions",
    "boomerangue.apps.pix_database",
    "boomerangue.apps.atributos",
    "boomerangue.apps.ia_messages",
    "boomerangue.apps.validacao_documentos",
    "boomerangue.apps.recrutamento",
    "corsheaders",
    "single_session",
    'channels',
    'storages',
    'django_celery_beat',
]

MIDDLEWARE = [
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "boomerangue.middleware.LanguagePrefixMiddleware",
    "boomerangue.multitenancy.RouterMiddleware",
    # "boomerangue.middleware.CsrfExemptMiddleware",
]

ROOT_URLCONF = "boomerangue.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "boomerangue.wsgi.application"
ASGI_APPLICATION = "boomerangue.asgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
if not DEBUG:
    STATIC_URL = "/boomerangue/static/"
    STATIC_ROOT = os.path.join(BASE_DIR, "static")
    DATABASES = {
        'default': {
            
        }
    }
else:
    STATIC_URL = "static/"
    STATIC_ROOT = os.path.join(BASE_DIR, "static")
    DATABASES = {
        
    }
    # Enable HTTPS by setting the following option to True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # Set the HSTS (HTTP Strict Transport Security) header for enhanced security.
    SECURE_HSTS_SECONDS = 31536000  # 1 year (you can adjust this value as needed)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Ensure all cookies are marked as secure and use only HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
DATABASE_ROUTERS = ["boomerangue.multitenancy.DatabaseRouter", 'boomerangue.db_router.PixDBRouter']

STATICFILES_DIRS = [
    BASE_DIR / "boomerangue/static/assets/",
]


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_USER_MODEL = "login.Usuario"
AUTH_GROUP_MODEL = 'login.Grupos'

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "pt"

LANGUAGES = [
    ('pt', _('Português Brasileiro')),
    ('en', _('English')),
    ('es', _('Espanol')),
    # Adicione mais idiomas, se necessário
]


LOCALE_PATHS = [
    # os.path.join(BASE_DIR, 'locale'),  # Diretório raiz do projeto
    os.path.join(BASE_DIR, 'boomerangue', 'locale'),  # Substitua 'api' pelo nome do seu aplicativo
    # os.path.join(BASE_DIR, 'ia', 'locale'),  # Substitua 'api' pelo nome do seu aplicativo
    # os.path.join(BASE_DIR, 'login', 'locale'),  # Substitua 'api' pelo nome do seu aplicativo
]

LOCALEURL_USE_ACCEPT_LANGUAGE = True

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'sass_processor.finders.CssFinder',
]

SASS_PROCESSOR_ROOT = STATIC_ROOT

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOW_ALL_ORIGINS = True




CELERY_BROKER_URL = 'redis://localhost:6379/0'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG':{
            "hosts": [('127.0.0.1', 6379)],
        }
    }
}


# Wasabi configuration

DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'  # ou o armazenamento padrão desejado

# Configurações para Wasabi


# Aumentando o tamanho máximo de upload de dados (valor padrão é 2.5MB/2621440 bytes)
# Definindo para 20MB (valor em bytes)
DATA_UPLOAD_MAX_MEMORY_SIZE = 20971520



