# Generated by Django 4.1.4 on 2023-10-05 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ger_linhaprodutos",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "template_name",
                    models.CharField(max_length=255, verbose_name="Nome do template"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ACCOUNT_UPDATE", "ACCOUNT_UPDATE"),
                            ("ALERT_UPDATE", "ALERT_UPDATE"),
                            ("APPOINTMENT_UPDATE", "APPOINTMENT_UPDATE"),
                            ("AUTO_REPLY", "AUTO_REPLY"),
                            ("ISSUE_RESOLUTION", "ISSUE_RESOLUTION"),
                            ("PAYMENT_UPDATE", "PAYMENT_UPDATE"),
                            ("PERSONAL_FINANCE_UPDATE", "PERSONAL_FINANCE_UPDATE"),
                            ("RESERVATION_UPDATE", "RESERVATION_UPDATE"),
                            ("SHIPPING_UPDATE", "SHIPPING_UPDATE"),
                            ("TICKET_UPDATE", "TICKET_UPDATE"),
                        ],
                        max_length=23,
                        verbose_name="Categoria do template",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="PT-BR",
                        max_length=10,
                        verbose_name="Idioma do template",
                    ),
                ),
                (
                    "cadastro_dt",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data e hora de criação do registro",
                    ),
                ),
                (
                    "alteracao_dt",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Data e hora da última modificação do registro",
                    ),
                ),
                (
                    "exclusao_dt",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Data e hora de exclusão do registro",
                    ),
                ),
                (
                    "statusregistro_id",
                    models.IntegerField(verbose_name="ID do status do registro"),
                ),
            ],
        ),
    ]
