# Generated by Django 4.1.4 on 2023-11-07 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ger_linhaprodutos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="ger_linhaprodutos",
            table="ger_linhaprodutos",
        ),
    ]
