# Generated by Django 4.1.4 on 2023-11-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_linhaprodutos", "0002_alter_ger_linhaprodutos_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_linhaprodutos",
            name="category",
            field=models.CharField(
                choices=[
                    ("ACCOUNT_UPDATE", "ATUALIZAÇÃO DE CONTA"),
                    ("ALERT_UPDATE", "ATUALIZAÇÃO DE ALERTA"),
                    ("APPOINTMENT_UPDATE", "ATUALIZAÇÃO DE AGENDAMENTO"),
                    ("AUTO_REPLY", "RESPOSTA AUTOMÁTICA"),
                    ("ISSUE_RESOLUTION", "RESOLUÇÃO DE PROBLEMA"),
                    ("PAYMENT_UPDATE", "ATUALIZAÇÃO DE PAGAMENTO"),
                    ("PERSONAL_FINANCE_UPDATE", "ATUALIZAÇÃO FINANCEIRA PESSOAL"),
                    ("RESERVATION_UPDATE", "ATUALIZAÇÃO DE RESERVA"),
                    ("SHIPPING_UPDATE", "ATUALIZAÇÃO DE ENTREGA"),
                    ("TICKET_UPDATE", "ATUALIZAÇÃO DE INGRESSO"),
                ],
                max_length=23,
                verbose_name="Categoria do template",
            ),
        ),
    ]
