# Generated by Django 4.1.4 on 2023-11-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_linhaprodutos", "0003_alter_ger_linhaprodutos_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ger_linhaprodutos",
            name="category",
        ),
        migrations.RemoveField(
            model_name="ger_linhaprodutos",
            name="language",
        ),
        migrations.RemoveField(
            model_name="ger_linhaprodutos",
            name="template_name",
        ),
        migrations.AddField(
            model_name="ger_linhaprodutos",
            name="EDI_Integracao",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="ger_linhaprodutos",
            name="LinhaAtiva",
            field=models.CharField(default="S", max_length=1),
        ),
        migrations.AddField(
            model_name="ger_linhaprodutos",
            name="LinhaProdutos",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="ger_linhaprodutos",
            name="OrdemLinhaProdutos",
            field=models.CharField(default="000", max_length=50),
        ),
        migrations.AddField(
            model_name="ger_linhaprodutos",
            name="Sincronizado",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AddField(
            model_name="ger_linhaprodutos",
            name="dtSincronizacao",
            field=models.DateTimeField(
                auto_now=True,
                null=True,
                verbose_name="Data e hora da última modificação do registro",
            ),
        ),
        migrations.AddField(
            model_name="ger_linhaprodutos",
            name="empresa_id",
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ger_linhaprodutos",
            name="idSincronizador",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="ger_linhaprodutos",
            name="verSincronizador",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name="ger_linhaprodutos",
            name="statusregistro_id",
            field=models.IntegerField(
                default=200, verbose_name="ID do status do registro"
            ),
        ),
    ]
