# Generated by Django 4.1.4 on 2023-11-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_linhaprodutos", "0004_remove_ger_linhaprodutos_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_linhaprodutos",
            name="OrdemLinhaProdutos",
            field=models.CharField(default="000", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ger_linhaprodutos",
            name="alteracao_dt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="ger_linhaprodutos",
            name="cadastro_dt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="ger_linhaprodutos",
            name="dtSincronizacao",
            field=models.DateTimeField(
                null=True, verbose_name="Data e hora da última modificação do registro"
            ),
        ),
        migrations.AlterField(
            model_name="ger_linhaprodutos",
            name="exclusao_dt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="ger_linhaprodutos",
            name="statusregistro_id",
            field=models.IntegerField(default=200),
        ),
    ]
