# Generated by Django 4.1.4 on 2023-11-08 20:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ger_linhaprodutos", "0006_alter_ger_linhaprodutos_empresa_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ger_linhaprodutos",
            old_name="empresa_id",
            new_name="empresa",
        ),
    ]
