# Generated by Django 4.1.4 on 2023-10-05 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ger_entidades", "__first__"),
        ("ger_empresas", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="b2b_bonusconfig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField(default=200)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
                (
                    "entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_entidades.ger_entidade",
                    ),
                ),
            ],
            options={
                "db_table": "b2b_bonusconfig",
            },
        ),
        migrations.CreateModel(
            name="b2b_bonusregraescalonada",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "min_pedido_valor",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "max_pedido_valor",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("min_produto_qtd", models.IntegerField(null=True)),
                ("max_produto_qtd", models.IntegerField(null=True)),
                (
                    "bonus_percentual",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "bonus_valor",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField(default=200)),
                (
                    "bonusconfig",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="b2b.b2b_bonusconfig",
                    ),
                ),
            ],
            options={
                "db_table": "b2b_bonusregraescalonada",
            },
        ),
        migrations.CreateModel(
            name="b2b_bonusmovimento",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("data_movimento", models.DateTimeField(auto_now_add=True)),
                (
                    "valor_movimento",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "tipo_movimento",
                    models.CharField(
                        choices=[("ACUMULO", "Acúmulo"), ("RESGATE", "Resgate")],
                        max_length=7,
                    ),
                ),
                ("data_vencimento", models.DateField(null=True)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField(default=200)),
                (
                    "bonusconfig",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="b2b.b2b_bonusconfig",
                    ),
                ),
                (
                    "bonusescalonado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="b2b.b2b_bonusregraescalonada",
                    ),
                ),
                (
                    "entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_entidades.ger_entidade",
                    ),
                ),
            ],
            options={
                "db_table": "b2b_bonusmovimento",
            },
        ),
        migrations.AddIndex(
            model_name="b2b_bonusregraescalonada",
            index=models.Index(
                fields=["bonusconfig"], name="b2b_bonusre_bonusco_11b56d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="b2b_bonusconfig",
            index=models.Index(
                fields=["empresa"], name="b2b_bonusco_empresa_e2d851_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="b2b_bonusconfig",
            index=models.Index(
                fields=["empresa", "entidade"], name="b2b_bonusco_empresa_aa95e2_idx"
            ),
        ),
    ]
