# Generated by Django 4.1.4 on 2023-10-05 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ger_condicoespagamento",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("condicoes_pagamento", models.CharField(max_length=255)),
                ("valor_minimo", models.DecimalField(decimal_places=6, max_digits=18)),
                ("NroParcelas", models.IntegerField()),
                ("status_condicoes_pagamento", models.IntegerField()),
                ("CondicaoPadrao", models.CharField(default="S", max_length=1)),
                ("CondicaoAtiva", models.CharField(default="S", max_length=1)),
                ("prazo_medio", models.IntegerField(default=0)),
                ("EDI_Integracao", models.CharField(max_length=50)),
                ("COD_TIPO_CONDICAO_PAGAMENTO", models.IntegerField(null=True)),
                ("PRC_ADICIONAL_FINANCEIRO", models.FloatField(null=True)),
                ("PRIORIDADE_CONDICAO_PAGAMENTO", models.IntegerField(null=True)),
                ("TIPO_DOCUMENTO", models.CharField(max_length=5, null=True)),
                ("CondicaoAmigavel", models.CharField(max_length=100, null=True)),
                (
                    "CodTipoDocumentoCobranca",
                    models.CharField(default="00", max_length=10),
                ),
                ("Sincronizado", models.CharField(default="S", max_length=1)),
                ("dtSincronizacao", models.DateTimeField(null=True)),
                (
                    "Sincronizador_ver",
                    models.CharField(default="00.0000.0000", max_length=12),
                ),
                ("Sincronizador_id", models.IntegerField(null=True)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True, null=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True, null=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField(default=200)),
            ],
            options={
                "db_table": "ger_condicoespagamento",
            },
        ),
        migrations.CreateModel(
            name="ger_empresa_b2b",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("b2b_store_id", models.IntegerField()),
                ("b2b_integra", models.BooleanField(default=False)),
                ("b2b_usaescalonamentopreco", models.IntegerField(default=1)),
                ("b2b_usacupomdesconto", models.IntegerField(default=1)),
                ("b2b_usaplanofidelidade", models.IntegerField(default=0)),
                ("b2b_integradolokalizei", models.IntegerField(default=0)),
                (
                    "b2b_idcostumerlojalizei",
                    models.CharField(default="0", max_length=45),
                ),
                ("b2b_integradobot", models.IntegerField(default=1)),
                ("b2b_nomebot", models.CharField(default="plubot", max_length=45)),
                (
                    "b2b_nomeservicobot",
                    models.CharField(default="plugsrvbot", max_length=45),
                ),
                ("b2b_precos_idtabelapadrao", models.IntegerField(default=0)),
                ("b2b_logo_empresa_color", models.CharField(max_length=100)),
                ("b2b_logo_empresa_bco", models.CharField(max_length=100)),
                (
                    "b2b_integradorativo",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não")], default="S", max_length=1
                    ),
                ),
                ("b2b_parceiro", models.CharField(default="PlugThink", max_length=50)),
                (
                    "b2b_nome_integrador",
                    models.CharField(default="PlugThink", max_length=50),
                ),
                ("b2b_dataultimasincronizacao", models.DateTimeField(null=True)),
                (
                    "b2b_template_integracao",
                    models.CharField(default="PADRAO", max_length=50),
                ),
                ("b2b_exportafirebase", models.CharField(default="N", max_length=1)),
                ("b2b_exportapreco", models.CharField(default="N", max_length=1)),
                ("b2b_usatabelaunica", models.CharField(default="S", max_length=1)),
                ("b2b_tabelaprecopadrao_id", models.IntegerField(null=True)),
                (
                    "b2b_firebaseexportador",
                    models.CharField(default="OLAPDV", max_length=45),
                ),
                (
                    "b2b_produtosusarnomepersonalizado",
                    models.CharField(default="N", max_length=1),
                ),
                (
                    "b2b_empresademonstracao",
                    models.CharField(default="N", max_length=1),
                ),
                (
                    "b2b_formatoarquivoexportacao",
                    models.CharField(
                        default="c:\\exporta\\���������CODP\u200bUXADA\\Pedidos\\",
                        max_length=100,
                    ),
                ),
                (
                    "b2b_pedidoexportacaoarquivo",
                    models.CharField(default="FLAG", max_length=45),
                ),
                (
                    "b2b_pedido_nome_arquivo",
                    models.CharField(
                        default="PEDIDO_���������CODP\u200bUXADA�������DATAESP���PED.TXT",
                        max_length=100,
                    ),
                ),
                (
                    "b2b_pedido_formato",
                    models.CharField(default="000000", max_length=10),
                ),
                (
                    "b2b_pedido_formato_data",
                    models.CharField(default="YYYYMMDD", max_length=10),
                ),
                (
                    "b2b_cliente_nome_arquivo",
                    models.CharField(
                        default="PDV_���������CODP\u200bUXADA�������DATAESP���CLI.TXT",
                        max_length=45,
                    ),
                ),
                ("b2b_cadastro_clientes", models.CharField(max_length=1)),
                ("b2b_integrador_inicio", models.DateTimeField(null=True)),
                ("b2b_integrador_ult_atividade", models.DateTimeField(null=True)),
                ("b2b_integrador_fim", models.DateTimeField(null=True)),
                (
                    "b2b_integrador_status_atual",
                    models.CharField(default="Integrado", max_length=200),
                ),
                (
                    "b2b_integrador_liberado",
                    models.CharField(default="S", max_length=1),
                ),
                (
                    "b2b_categoria_especiais",
                    models.CharField(default="N", max_length=1),
                ),
                (
                    "b2b_ia_vendascategorias",
                    models.CharField(default="N", max_length=1),
                ),
                ("b2b_rotinaexportacao", models.CharField(default="T", max_length=1)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField()),
            ],
            options={
                "db_table": "ger_empresa_b2b",
            },
        ),
        migrations.CreateModel(
            name="ger_empresa_bmm",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "bm_site",
                    models.CharField(default="https:\\boomerangue.me", max_length=100),
                ),
                (
                    "bm_telentrada",
                    models.CharField(
                        choices=[("D", "Usuário"), ("U", "Login")],
                        default="U",
                        max_length=1,
                    ),
                ),
                (
                    "bm_enviaconfirmacaopartner",
                    models.CharField(default="N", max_length=1),
                ),
                ("bm_usa_exportador", models.CharField(default="N", max_length=1)),
                (
                    "bm_bot_rotinaenvio",
                    models.CharField(default="padrao", max_length=50),
                ),
                (
                    "bm_bot_prefixo",
                    models.CharField(default="bmbot_�������apelido", max_length=45),
                ),
                ("bm_bot_nromaxbots", models.IntegerField(default=3)),
                ("bm_bot_nromaxenviosrodada", models.IntegerField(default=120)),
                ("bm_bot_intervalorodada", models.IntegerField(default=30)),
                (
                    "bm_bot_enviarepic",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não")], default="N", max_length=1
                    ),
                ),
                (
                    "bm_bot_calcrepicautomatico",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não")], default="N", max_length=1
                    ),
                ),
                ("bm_bot_intervalominimorepic", models.IntegerField(default=360)),
                ("bm_bot_nrominimorepic", models.IntegerField(default=1)),
                ("bm_bot_nromaximorepic", models.IntegerField(default=1)),
                (
                    "bm_bot_horainicialenvio",
                    models.CharField(default="07:30", max_length=5),
                ),
                (
                    "bm_bot_horafinalenvio",
                    models.CharField(default="21:00", max_length=5),
                ),
                (
                    "bm_bot_enviaferiado",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não")], default="N", max_length=1
                    ),
                ),
                (
                    "bm_bot_enviasabado",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não")], default="S", max_length=1
                    ),
                ),
                (
                    "bm_bot_enviadomingo",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não")], default="N", max_length=1
                    ),
                ),
                ("bm_bannerboomerangue", models.CharField(max_length=100)),
                (
                    "bm_horariosintegracao",
                    models.CharField(default="04:00,10:00,16:00,20:00", max_length=100),
                ),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField()),
            ],
            options={
                "db_table": "ger_empresa_bmm",
            },
        ),
        migrations.CreateModel(
            name="ger_empresas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("parceiro_id", models.IntegerField(default=1)),
                (
                    "tipoempresa_id",
                    models.CharField(
                        choices=[("M", "Matriz"), ("F", "Filial")],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("empresagestao_id", models.IntegerField(null=True)),
                ("empresa", models.CharField(max_length=40)),
                ("empresa_apelido", models.CharField(max_length=20)),
                ("cnpj", models.CharField(max_length=20)),
                ("cod_puxada", models.CharField(max_length=50)),
                ("chave_edi", models.CharField(max_length=50)),
                ("cod_empresa", models.CharField(max_length=50)),
                ("edi_integracao", models.CharField(max_length=50)),
                ("tokenapi", models.CharField(max_length=50)),
                ("tokennumerico", models.IntegerField(default=0)),
                ("tokenbmempresa", models.CharField(max_length=50)),
                (
                    "telefonesac",
                    models.CharField(default="(00) 0000-0000", max_length=20),
                ),
                ("codtelefone", models.CharField(max_length=45)),
                ("prefixopedido", models.CharField(default="PED", max_length=3)),
                ("emailpedidodireto", models.CharField(max_length=200)),
                ("emailpedidoempresa", models.CharField(max_length=200)),
                ("emailpedidocopiacliente", models.BooleanField(default=False)),
                (
                    "comissaopadrao",
                    models.DecimalField(decimal_places=4, default=1.0, max_digits=18),
                ),
                (
                    "bancodadosfirebase",
                    models.CharField(default="boomeranguev4", max_length=100),
                ),
                (
                    "categoriacorfundo",
                    models.CharField(default="#FFFFFF", max_length=10),
                ),
                (
                    "categoriacorletra",
                    models.CharField(default="#000000", max_length=10),
                ),
                ("extarquivoimg", models.CharField(default=".png", max_length=10)),
                ("integracao_status", models.CharField(max_length=1, null=True)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField(default=200)),
            ],
            options={
                "db_table": "ger_empresas",
            },
        ),
        migrations.AddIndex(
            model_name="ger_empresas",
            index=models.Index(
                fields=["empresa"], name="ger_empresa_empresa_e9384c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ger_empresas",
            index=models.Index(
                fields=["tokenapi"], name="ger_empresa_tokenap_ce7aab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ger_empresas",
            index=models.Index(
                fields=["statusregistro_id"], name="ger_empresa_statusr_6867a7_idx"
            ),
        ),
        migrations.AddField(
            model_name="ger_empresa_bmm",
            name="empresa_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ger_empresas.ger_empresas",
            ),
        ),
        migrations.AddField(
            model_name="ger_empresa_b2b",
            name="empresa_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ger_empresas.ger_empresas",
            ),
        ),
        migrations.AddField(
            model_name="ger_condicoespagamento",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ger_empresas.ger_empresas",
            ),
        ),
        migrations.AddIndex(
            model_name="ger_empresa_bmm",
            index=models.Index(
                fields=["empresa_id"], name="ger_empresa_empresa_9af1e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ger_empresa_b2b",
            index=models.Index(
                fields=["empresa_id"], name="ger_empresa_empresa_daa3b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ger_condicoespagamento",
            index=models.Index(
                fields=["empresa"], name="ger_condico_empresa_4e5399_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ger_condicoespagamento",
            index=models.Index(
                fields=["empresa", "EDI_Integracao"],
                name="ger_condico_empresa_440d88_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ger_condicoespagamento",
            index=models.Index(
                fields=[
                    "empresa",
                    "status_condicoes_pagamento",
                    "CodTipoDocumentoCobranca",
                ],
                name="ger_condico_empresa_516272_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ger_condicoespagamento",
            index=models.Index(
                fields=["empresa", "condicoes_pagamento"],
                name="ger_condico_empresa_98cf9c_idx",
            ),
        ),
    ]
