# Generated by Django 4.1.4 on 2023-10-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_empresas",
            name="url_boomerangue",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ger_empresas",
            name="empresa_apelido",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="ger_empresas",
            name="tokennumerico",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
