# Generated by Django 4.1.4 on 2023-10-16 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0002_ger_empresas_url_boomerangue_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_condicoespagamento",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ger_empresas.ger_empresas",
            ),
        ),
    ]
