# Generated by Django 4.1.4 on 2023-10-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0003_alter_ger_condicoespagamento_empresa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_empresas",
            name="statusregistro_id",
            field=models.IntegerField(default=900),
        ),
    ]
