# Generated by Django 4.1.4 on 2023-11-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0004_alter_ger_empresas_statusregistro_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_empresas",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("D", "Distribuidora"),
                    ("H", "Hospital"),
                    ("CM", "Clínica Médica"),
                    ("CD", "Clínica Dentista"),
                    ("I", "Indústria"),
                    ("DF", "Default"),
                ],
                default="DF",
                max_length=2,
            ),
        ),
    ]
