# Generated by Django 4.1.4 on 2023-11-07 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0005_ger_empresas_tipo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ger_empresa_b2b",
            old_name="empresa_id",
            new_name="empresa",
        ),
        migrations.RenameField(
            model_name="ger_empresa_bmm",
            old_name="empresa_id",
            new_name="empresa",
        ),
        migrations.RenameIndex(
            model_name="ger_empresa_b2b",
            new_name="ger_empresa_empresa_926a14_idx",
            old_name="ger_empresa_empresa_daa3b8_idx",
        ),
        migrations.RenameIndex(
            model_name="ger_empresa_bmm",
            new_name="ger_empresa_empresa_cd0de4_idx",
            old_name="ger_empresa_empresa_9af1e1_idx",
        ),
    ]
