# Generated by Django 4.1.4 on 2023-11-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0006_rename_empresa_id_ger_empresa_b2b_empresa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_condicoespagamento",
            name="CondicaoPadrao",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="ger_condicoespagamento",
            name="NroParcelas",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="ger_condicoespagamento",
            name="Sincronizado",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="ger_condicoespagamento",
            name="Sincronizador_ver",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="ger_condicoespagamento",
            name="status_condicoes_pagamento",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ger_condicoespagamento",
            name="valor_minimo",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="ger_empresa_b2b",
            name="b2b_cliente_nome_arquivo",
            field=models.CharField(
                default="PDV_$$CODP\u200bUXADA$$DATAESP$$CLI.TXT", max_length=45
            ),
        ),
        migrations.AlterField(
            model_name="ger_empresa_b2b",
            name="b2b_formatoarquivoexportacao",
            field=models.CharField(
                default="c:\\exporta\\$$CODP\u200bUXADA$$\\Pedidos\\", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="ger_empresa_b2b",
            name="b2b_pedido_nome_arquivo",
            field=models.CharField(
                default="PEDIDO_$$CODP\u200bUXADA$$DATAESP$$PED.TXT", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="ger_empresa_b2b",
            name="b2b_store_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ger_empresa_b2b",
            name="statusregistro_id",
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name="ger_empresa_bmm",
            name="bm_bot_prefixo",
            field=models.CharField(default="bmbot_$$apelido", max_length=45),
        ),
        migrations.AlterField(
            model_name="ger_empresa_bmm",
            name="statusregistro_id",
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name="ger_empresas",
            name="codtelefone",
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name="ger_empresas",
            name="emailpedidocopiacliente",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="ger_empresas",
            name="emailpedidodireto",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="ger_empresas",
            name="emailpedidoempresa",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="ger_empresas",
            name="integracao_status",
            field=models.CharField(default="0", max_length=1, null=True),
        ),
    ]
