# Generated by Django 4.1.4 on 2023-12-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0008_alter_ger_empresas_tipo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_empresas",
            name="tipoempresa_id",
            field=models.CharField(
                choices=[
                    ("DI", "Distribuidora"),
                    ("HSP", "Hospital"),
                    ("FUN", "Fundacao"),
                    ("IND", "Industria"),
                    ("ICAL", "Industria Calcados"),
                    ("COM", "Comercio"),
                    ("SRV", "Servicos"),
                    ("SEG", "Seguros"),
                    ("MED", "Medicina"),
                    ("ODO", "Odontologia"),
                    ("CLI", "Clinicas"),
                    ("EST", "Clinicas Esteticas"),
                    ("DF", "Default"),
                ],
                default="DF",
                max_length=10,
            ),
        ),
    ]
