# Generated by Django 4.1.4 on 2023-12-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0010_ger_empresas_tipo_de_negocio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_empresas",
            name="empresa_apelido",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
