# Generated by Django 4.1.4 on 2023-12-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0011_alter_ger_empresas_empresa_apelido"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_empresas",
            name="botNumeroValidacao",
            field=models.CharField(max_length=45, null=True),
        ),
    ]
