# Generated by Django 4.1.4 on 2024-01-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0012_ger_empresas_botnumerovalidacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="ger_tipoempresa",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("value_prefixo", models.CharField(max_length=5)),
                ("value", models.CharField(max_length=50)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField(default=200)),
            ],
            options={
                "db_table": "ger_tipoempresa",
            },
        ),
        migrations.RemoveField(
            model_name="ger_empresas",
            name="tipo_de_negocio",
        ),
    ]
