# Generated by Django 4.1.4 on 2024-01-11 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0013_ger_tipoempresa_remove_ger_empresas_tipo_de_negocio"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_empresas",
            name="tipo_de_negocio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_empresas.ger_tipoempresa",
            ),
        ),
    ]
