# Generated by Django 4.1.4 on 2024-01-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0014_ger_empresas_tipo_de_negocio"),
    ]

    operations = [
        migrations.CreateModel(
            name="permissoes_paginas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("descricao", models.TextField()),
            ],
        ),
    ]
