# Generated by Django 4.1.4 on 2024-01-11 22:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0015_permissoes_paginas"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="permissoes_paginas",
            table="permissoes_paginas",
        ),
    ]
