# Generated by Django 4.1.4 on 2024-01-11 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0016_alter_permissoes_paginas_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoEmpresaPermissao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permissao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_empresas.permissoes_paginas",
                    ),
                ),
                (
                    "tipo_empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_empresas.ger_tipoempresa",
                    ),
                ),
            ],
            options={
                "db_table": "TipoEmpresaPermissao",
            },
        ),
    ]
