# Generated by Django 4.1.4 on 2024-01-15 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0017_tipoempresapermissao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_empresas",
            name="tipo_de_negocio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ger_empresas.ger_tipoempresa",
            ),
        ),
    ]
