# Generated by Django 4.1.4 on 2024-01-16 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0018_alter_ger_empresas_tipo_de_negocio"),
    ]

    operations = [
        migrations.CreateModel(
            name="select_tipo_campanha",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("option", models.CharField(max_length=50)),
                ("option_prefix", models.CharField(max_length=5)),
                (
                    "tipo_empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_empresas.ger_tipoempresa",
                    ),
                ),
            ],
            options={
                "db_table": "select_tipo_campanha",
            },
        ),
    ]
