# Generated by Django 4.1.4 on 2024-01-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0019_select_tipo_campanha"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_empresas",
            name="prompt_IA_especifico",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_tipoempresa",
            name="prompt_IA",
            field=models.TextField(blank=True, null=True),
        ),
    ]
