# Generated by Django 4.1.4 on 2024-01-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0020_ger_empresas_prompt_ia_especifico_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StringPersonalizada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chave", models.CharField(max_length=255)),
                ("valor", models.TextField()),
                ("lingua", models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name="ger_tipoempresa",
            name="strings_personalizadas",
            field=models.ManyToManyField(
                blank=True, to="ger_empresas.stringpersonalizada"
            ),
        ),
    ]
