# Generated by Django 4.1.4 on 2024-01-18 21:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0021_stringpersonalizada_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="stringpersonalizada",
            table="StringPersonalizada",
        ),
    ]
