# Generated by Django 4.1.4 on 2024-01-19 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0022_alter_stringpersonalizada_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ger_tipoempresa",
            name="strings_personalizadas",
        ),
        migrations.AddField(
            model_name="stringpersonalizada",
            name="tipo_empresa",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ger_empresas.ger_tipoempresa",
            ),
        ),
    ]
