# Generated by Django 4.1.4 on 2024-01-22 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0023_remove_ger_tipoempresa_strings_personalizadas_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="prompt_ia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("descricao", models.TextField()),
                (
                    "tipo_empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_empresas.ger_tipoempresa",
                    ),
                ),
            ],
            options={
                "db_table": "prompt_ia",
            },
        ),
    ]
