# Generated by Django 4.1.4 on 2024-01-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0024_prompt_ia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt_ia",
            name="nome",
            field=models.CharField(default="Prompt Relatório IA", max_length=50),
        ),
    ]
