# Generated by Django 4.1.4 on 2024-01-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0025_alter_prompt_ia_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt_ia",
            name="descricao",
            field=models.TextField(
                default="Desenvolva um relatório de vendas detalhado e profissional, apresentando as seguintes métricas chave: Número Total de Boomerangues ({nBoomerangues}), Boomerangues Enviados ({Enviado}), Total de Vendas em Reais (R$ {ValorVendas}), e Ticket Médio ({TicketMedio}). Este relatório deve oferecer uma visão clara e concisa do desempenho de vendas, com foco na análise e interpretação desses dados específicos."
            ),
        ),
    ]
