# Generated by Django 4.1.4 on 2024-01-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0026_alter_prompt_ia_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stringpersonalizada",
            name="lingua",
            field=models.CharField(default="pt", max_length=3),
        ),
    ]
