# Generated by Django 4.1.4 on 2024-03-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0027_alter_stringpersonalizada_lingua"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_empresas",
            name="image_logo_empresa",
            field=models.ImageField(
                max_length=400, null=True, upload_to="media/logo_empresa/"
            ),
        ),
    ]
