# Generated by Django 4.1.4 on 2024-04-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0028_ger_empresas_image_logo_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_empresas",
            name="CarrinhoAbandonado",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AddField(
            model_name="ger_empresas",
            name="CompraRecebida",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AddField(
            model_name="ger_empresas",
            name="Repique1",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AddField(
            model_name="ger_empresas",
            name="Repique1minutos",
            field=models.IntegerField(default=240, null=True),
        ),
        migrations.AddField(
            model_name="ger_empresas",
            name="Repique2",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AddField(
            model_name="ger_empresas",
            name="Repique2minutos",
            field=models.IntegerField(default=240, null=True),
        ),
        migrations.AddField(
            model_name="ger_empresas",
            name="bot_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="ger_empresas",
            name="canal_id",
            field=models.IntegerField(null=True),
        ),
    ]
