# Generated by Django 4.1.4 on 2024-04-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0029_ger_empresas_carrinhoabandonado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_empresas",
            name="max_tokens_ia",
            field=models.IntegerField(default=800, null=True),
        ),
    ]
