# Generated by Django 4.1.4 on 2024-04-29 20:04

import boomerangue.apps.ger_empresas.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0030_ger_empresas_max_tokens_ia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_empresas",
            name="image_logo_empresa",
            field=models.FileField(
                max_length=400,
                null=True,
                upload_to="media/logo_empresa/",
                validators=[boomerangue.apps.ger_empresas.models.ValidateSVG()],
            ),
        ),
    ]
