# Generated by Django 4.1.4 on 2024-08-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0031_alter_ger_empresas_image_logo_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_empresas",
            name="template_resposta",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
