# Generated by Django 4.1.4 on 2024-08-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0032_ger_empresas_template_resposta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_empresas",
            name="empresa",
            field=models.CharField(max_length=200),
        ),
    ]
