# Generated by Django 4.1.4 on 2024-09-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0033_alter_ger_empresas_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_empresas",
            name="template_envio_clinica",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="ger_empresas",
            name="template_optin_clinica",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
