# Generated by Django 4.1.4 on 2024-12-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0034_ger_empresas_template_envio_clinica_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_empresas",
            name="prompt_IA_mapa",
            field=models.TextField(blank=True, null=True),
        ),
    ]
