# Generated by Django 4.1.4 on 2024-12-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0035_ger_empresas_prompt_ia_mapa"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_empresas",
            name="modelo_ia",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
