# Generated by Django 4.1.4 on 2024-12-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0036_ger_empresas_modelo_ia"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_empresas",
            name="template_envio_vendedores",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="ger_empresas",
            name="template_optin_vendedores",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
