# Generated by Django 4.1.4 on 2025-03-07 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0038_ger_unidade"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="ger_unidade",
            table="ger_unidade",
        ),
    ]
