# Generated by Django 4.1.4 on 2025-04-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0039_alter_ger_unidade_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_unidade",
            name="boomerangue_apikey",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ger_unidade",
            name="boomerangue_empresa_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_unidade",
            name="boomerangue_url",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ger_unidade",
            name="bot_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ger_unidade",
            name="cnpj",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="ger_unidade",
            name="flow_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ger_unidade",
            name="message_agenda_flow_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ger_unidade",
            name="message_agenda_flow_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ger_unidade",
            name="message_agenda_flow_url",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ger_unidade",
            name="message_agenda_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ger_unidade",
            name="message_agenda_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_unidade",
            name="message_bemvindo_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ger_unidade",
            name="message_bemvindo_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_unidade",
            name="message_finalizado_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ger_unidade",
            name="message_finalizado_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_unidade",
            name="message_modelo_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ger_unidade",
            name="message_modelo_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_unidade",
            name="message_notificacao_flow_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ger_unidade",
            name="message_notificacao_flow_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ger_unidade",
            name="message_notificacao_flow_url",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ger_unidade",
            name="message_notificacao_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ger_unidade",
            name="message_notificacao_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_unidade",
            name="message_reenvio_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ger_unidade",
            name="message_reenvio_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
