# Generated by Django 4.1.4 on 2023-11-08 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ger_linhaprodutos", "0004_remove_ger_linhaprodutos_category_and_more"),
        ("ger_grade", "0004_rename_empresa_id_ger_grade_empresa_and_more"),
        (
            "ger_grupoprodutos",
            "0003_rename_empresa_id_ger_grupoprodutos_empresa_and_more",
        ),
        ("ger_categorias", "0005_alter_ger_categorias_sincronizado_and_more"),
        ("ger_empresas", "0007_alter_ger_condicoespagamento_condicaopadrao_and_more"),
        (
            "ger_dadosgerais",
            "0006_ger_marcas_alteracao_dt_ger_marcas_cadastro_dt_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ger_produtos",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("EDI_Integracao", models.CharField(max_length=50)),
                ("Marca_Filtro", models.CharField(max_length=50)),
                ("SKU", models.CharField(max_length=50)),
                ("Codigo", models.CharField(max_length=50)),
                ("CodigoFornecedor", models.CharField(max_length=50)),
                ("Busca", models.CharField(max_length=50)),
                ("EAN", models.CharField(max_length=50)),
                ("DUN", models.CharField(max_length=50)),
                ("Agrupador", models.CharField(max_length=50)),
                ("ProdutoBusca", models.CharField(max_length=100)),
                (
                    "Destaque",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não")], max_length=1
                    ),
                ),
                (
                    "SaiListaGeral",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não")], max_length=1
                    ),
                ),
                (
                    "TemVariacao",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não")], max_length=1
                    ),
                ),
                (
                    "UsarDescricaoPersonalizada",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não")], max_length=1
                    ),
                ),
                (
                    "UsaMultiplicador",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não")], max_length=1
                    ),
                ),
                (
                    "produtoAtivo",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não")], max_length=1
                    ),
                ),
                (
                    "GrupoAtivo",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não")], max_length=1
                    ),
                ),
                (
                    "LinhaAtiva",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não")], max_length=1
                    ),
                ),
                ("CEST", models.CharField(max_length=20)),
                ("NCM", models.CharField(max_length=20)),
                ("Descricao", models.CharField(max_length=150)),
                ("Descricao_Longa", models.CharField(max_length=150)),
                ("Descricao_Curta", models.CharField(max_length=150)),
                ("Descricao_Detalhada", models.TextField()),
                ("Descricao_Amigavel", models.CharField(max_length=150)),
                ("Descricao_Limpa", models.CharField(max_length=150)),
                ("Descricao_Personalizada", models.CharField(max_length=150)),
                ("CategoriaAPP1Ordem", models.CharField(max_length=5)),
                ("CategoriaAPP2Ordem", models.CharField(max_length=5)),
                (
                    "Fator_Unitario",
                    models.DecimalField(decimal_places=6, max_digits=18),
                ),
                (
                    "Categoria1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Categoria1",
                        to="ger_categorias.ger_categorias",
                    ),
                ),
                (
                    "Categoria2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Categoria2",
                        to="ger_categorias.ger_categorias",
                    ),
                ),
                (
                    "Categoria3",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Categoria3",
                        to="ger_categorias.ger_categorias",
                    ),
                ),
                (
                    "CategoriaApp1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="CategoriaApp1",
                        to="ger_categorias.ger_categorias",
                    ),
                ),
                (
                    "CategoriaApp2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="CategoriaApp2",
                        to="ger_categorias.ger_categorias",
                    ),
                ),
                (
                    "GrupoProdutos",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ger_grupoprodutos.ger_grupoprodutos",
                    ),
                ),
                (
                    "LinhaProduto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ger_linhaprodutos.ger_linhaprodutos",
                    ),
                ),
                (
                    "UnidadeMedidaCx",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="UnidadeMedidaCx",
                        to="ger_dadosgerais.ger_unidademedida",
                    ),
                ),
                (
                    "UnidadeMedidaUn",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="UnidadeMedidaUn",
                        to="ger_dadosgerais.ger_unidademedida",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ger_grade.ger_grade",
                    ),
                ),
                (
                    "marca",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_dadosgerais.ger_marcas",
                    ),
                ),
            ],
            options={
                "db_table": "ger_produtos",
            },
        ),
    ]
