# Generated by Django 4.1.4 on 2023-11-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_produtos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_produtos",
            name="Agrupador",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="Busca",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="CEST",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="CategoriaAPP1Ordem",
            field=models.CharField(default="0000", max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="CategoriaAPP2Ordem",
            field=models.CharField(default="0000", max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="CodigoFornecedor",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="DUN",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="Descricao_Detalhada",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="Descricao_Longa",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="Descricao_Personalizada",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="Destaque",
            field=models.CharField(
                choices=[("S", "Sim"), ("N", "Não")], default="N", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="EAN",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="GrupoAtivo",
            field=models.CharField(
                choices=[("S", "Sim"), ("N", "Não")], default="S", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="LinhaAtiva",
            field=models.CharField(
                choices=[("S", "Sim"), ("N", "Não")], default="S", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="Marca_Filtro",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="NCM",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="ProdutoBusca",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="SKU",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="SaiListaGeral",
            field=models.CharField(
                choices=[("S", "Sim"), ("N", "Não")], default="S", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="TemVariacao",
            field=models.CharField(
                choices=[("S", "Sim"), ("N", "Não")], default="N", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="UsaMultiplicador",
            field=models.CharField(
                choices=[("S", "Sim"), ("N", "Não")], default="N", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="UsarDescricaoPersonalizada",
            field=models.CharField(
                choices=[("S", "Sim"), ("N", "Não")], default="N", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="produtoAtivo",
            field=models.CharField(
                choices=[("S", "Sim"), ("N", "Não")], default="S", max_length=1
            ),
        ),
    ]
