# Generated by Django 4.1.4 on 2023-11-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_produtos", "0002_alter_ger_produtos_agrupador_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_produtos",
            name="alteracao_dt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_produtos",
            name="cadastro_dt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_produtos",
            name="exclusao_dt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ger_produtos",
            name="statusregistro_id",
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="Fator_Unitario",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
    ]
