# Generated by Django 4.1.4 on 2023-11-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ger_produtos",
            "0003_ger_produtos_alteracao_dt_ger_produtos_cadastro_dt_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="ger_produtos",
            old_name="EDI_Integracao",
            new_name="edi_integracao",
        ),
        migrations.AddField(
            model_name="ger_produtos",
            name="OrdemPersonalizada",
            field=models.CharField(default="0000", max_length=100),
        ),
        migrations.AddField(
            model_name="ger_produtos",
            name="PathProduto",
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="Codigo",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="Descricao",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="Descricao_Amigavel",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="Descricao_Curta",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="Descricao_Limpa",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddIndex(
            model_name="ger_produtos",
            index=models.Index(
                fields=["empresa_id", "edi_integracao"], name="ix_gerproduto_upsert"
            ),
        ),
    ]
