# Generated by Django 4.1.4 on 2024-05-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ger_produtos",
            "0004_rename_edi_integracao_ger_produtos_edi_integracao_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_produtos",
            name="quantidade_disponivel",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
