# Generated by Django 4.1.4 on 2024-06-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_produtos", "0005_ger_produtos_quantidade_disponivel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_produtos",
            name="quantidade_disponivel",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=18, null=True
            ),
        ),
    ]
