# Generated by Django 4.1.4 on 2024-11-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_produtos", "0006_alter_ger_produtos_quantidade_disponivel"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_produtos",
            name="saldo",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=18, null=True
            ),
        ),
    ]
