# Generated by Django 4.1.4 on 2024-11-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_produtos", "0007_ger_produtos_saldo"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_produtos",
            name="QuantidadePorCaixa",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Quantidade de itens por caixa",
                max_digits=10,
                null=True,
            ),
        ),
    ]
