# Generated by Django 4.1.4 on 2024-12-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_produtos", "0008_ger_produtos_quantidadeporcaixa"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_produtos",
            name="final_relevance",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="ger_produtos",
            name="relevancia_peso",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=18, null=True
            ),
        ),
    ]
