# Generated by Django 4.1.4 on 2024-12-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_produtos", "0009_ger_produtos_final_relevance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_produtos",
            name="final_relevance",
            field=models.DecimalField(
                decimal_places=4, default=1, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ger_produtos",
            name="relevancia_peso",
            field=models.DecimalField(
                decimal_places=4, default=1, max_digits=18, null=True
            ),
        ),
    ]
