# Generated by Django 4.1.4 on 2024-12-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_produtos", "0010_alter_ger_produtos_final_relevance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_produtos",
            name="Descricao_Detalhada",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name="ger_produtos",
            index=models.Index(
                fields=[
                    "Descricao",
                    "Descricao_Curta",
                    "Descricao_Amigavel",
                    "EAN",
                    "Codigo",
                    "SKU",
                ],
                name="ix_gerproduto",
            ),
        ),
        migrations.AddIndex(
            model_name="ger_produtos",
            index=models.Index(fields=["Descricao_Detalhada"], name="desc_detalhada"),
        ),
    ]
