# Generated by Django 4.1.4 on 2024-09-30 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("campaign", "0074_bmm_boomerangue_data_consulta_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Atributo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_atributo", models.CharField(max_length=100)),
                (
                    "tipo_atributo",
                    models.CharField(
                        choices=[
                            ("texto", "Texto"),
                            ("combo", "Combo"),
                            ("textarea", "Textarea"),
                        ],
                        max_length=10,
                    ),
                ),
                ("conteudo_padrao", models.TextField(blank=True, null=True)),
                ("obrigatorio", models.BooleanField(default=False)),
                ("tipo_empresa", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="BoomerangueAtributo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_atributo", models.TextField()),
                (
                    "atributo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="atributos.atributo",
                    ),
                ),
                (
                    "boomerangue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaign.bmm_boomerangue",
                    ),
                ),
            ],
            options={
                "unique_together": {("boomerangue", "atributo")},
            },
        ),
    ]
