# Generated by Django 4.1.4 on 2024-09-30 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0034_ger_empresas_template_envio_clinica_and_more"),
        ("atributos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atributo",
            name="tipo_empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_empresas.ger_tipoempresa",
            ),
        ),
        migrations.AlterModelTable(
            name="atributo",
            table="Atributo",
        ),
        migrations.AlterModelTable(
            name="boomerangueatributo",
            table="BoomerangueAtributo",
        ),
    ]
