# Generated by Django 4.1.4 on 2024-09-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atributos", "0002_alter_atributo_tipo_empresa_alter_atributo_table_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrupoAgendamentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("color", models.CharField(default="#ffffff", max_length=100)),
                ("bg_color", models.CharField(max_length=100)),
            ],
        ),
    ]
