# Generated by Django 4.1.4 on 2024-09-30 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0034_ger_empresas_template_envio_clinica_and_more"),
        ("atributos", "0003_grupoagendamentos"),
    ]

    operations = [
        migrations.AddField(
            model_name="grupoagendamentos",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ger_empresas.ger_empresas",
            ),
        ),
    ]
