# Generated by Django 4.1.4 on 2024-10-01 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0075_bmm_boomerangue_bm_tipo"),
        ("atributos", "0004_grupoagendamentos_empresa"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoomerangueAgendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dtcadastro", models.DateTimeField(auto_now_add=True)),
                (
                    "boomerangue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaign.bmm_boomerangue",
                    ),
                ),
                (
                    "grupo_agendamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="atributos.grupoagendamentos",
                    ),
                ),
            ],
        ),
    ]
