# Generated by Django 4.1.4 on 2023-10-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ger_categorias",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("empresa_id", models.IntegerField()),
                ("EDI_Integracao", models.CharField(max_length=50)),
                (
                    "TipoCategoria",
                    models.CharField(
                        choices=[
                            ("N", "Normal"),
                            ("TV", "Top Vendas"),
                            ("S", "Sugestão"),
                        ],
                        max_length=2,
                    ),
                ),
                ("categoriaanterior_id", models.IntegerField()),
                ("CategoriaSubstituta_id", models.IntegerField()),
                ("Categoria", models.CharField(max_length=50)),
                ("CategoriaAmigavel", models.CharField(max_length=50)),
                ("CategoriaPersonalizada", models.CharField(max_length=50)),
                ("CategoriaDescricao", models.CharField(max_length=255)),
                ("OrdemCategoria", models.CharField(max_length=5)),
                ("OrdemExibicao", models.CharField(max_length=5)),
                ("CategoriaIcone", models.CharField(max_length=255)),
                ("IconePersonalizado", models.CharField(max_length=255)),
                ("CategoriaCorFundo", models.CharField(max_length=10)),
                ("CategoriaCorLetra", models.CharField(max_length=10)),
                ("Categoria1Prioridade", models.IntegerField()),
                ("Categoria1Ativa", models.IntegerField()),
                ("CategoriaUsarDoProduto", models.CharField(max_length=1)),
                ("CategoriaDesativarForcado", models.CharField(max_length=1)),
                ("Sincronizado", models.CharField(max_length=1)),
                ("dtSincronizacao", models.DateTimeField(auto_now_add=True)),
                ("verSincronizador", models.CharField(max_length=12)),
                ("idSincronizador", models.IntegerField()),
            ],
        ),
    ]
