# Generated by Django 4.1.4 on 2023-10-25 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0003_alter_ger_condicoespagamento_empresa"),
        ("ger_categorias", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_categorias",
            name="alteracao_dt",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="ger_categorias",
            name="cadastro_dt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_categorias",
            name="exclusao_dt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ger_categorias",
            name="statusregistro_id",
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name="ger_categorias",
            name="Categoria1Ativa",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ger_categorias",
            name="Categoria1Prioridade",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ger_categorias",
            name="CategoriaAmigavel",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ger_categorias",
            name="CategoriaCorFundo",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="ger_categorias",
            name="CategoriaCorLetra",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="ger_categorias",
            name="CategoriaDesativarForcado",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="ger_categorias",
            name="CategoriaDescricao",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ger_categorias",
            name="CategoriaIcone",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ger_categorias",
            name="CategoriaPersonalizada",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ger_categorias",
            name="CategoriaSubstituta_id",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="ger_categorias",
            name="CategoriaUsarDoProduto",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="ger_categorias",
            name="IconePersonalizado",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ger_categorias",
            name="OrdemCategoria",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="ger_categorias",
            name="OrdemExibicao",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="ger_categorias",
            name="Sincronizado",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="ger_categorias",
            name="categoriaanterior_id",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="ger_categorias",
            name="empresa_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ger_empresas.ger_empresas",
            ),
        ),
        migrations.AlterField(
            model_name="ger_categorias",
            name="idSincronizador",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ger_categorias",
            name="verSincronizador",
            field=models.CharField(max_length=12, null=True),
        ),
    ]
