# Generated by Django 4.1.4 on 2023-10-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_categorias", "0002_ger_categorias_alteracao_dt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_categorias",
            name="EDI_Integracao",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
