# Generated by Django 4.1.4 on 2023-11-07 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ger_categorias", "0003_alter_ger_categorias_edi_integracao"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ger_categorias",
            old_name="empresa_id",
            new_name="empresa",
        ),
        migrations.AlterModelTable(
            name="ger_categorias",
            table="ger_categorias",
        ),
    ]
