# Generated by Django 4.1.4 on 2023-11-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_categorias", "0004_rename_empresa_id_ger_categorias_empresa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_categorias",
            name="Sincronizado",
            field=models.CharField(default="N", max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="ger_categorias",
            name="dtSincronizacao",
            field=models.DateTimeField(null=True),
        ),
    ]
