# Generated by Django 4.1.4 on 2023-10-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="wpp_templates",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("template_name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ACCOUNT_UPDATE", "ACCOUNT_UPDATE"),
                            ("ALERT_UPDATE", "ALERT_UPDATE"),
                            ("APPOINTMENT_UPDATE", "APPOINTMENT_UPDATE"),
                            ("AUTO_REPLY", "AUTO_REPLY"),
                            ("ISSUE_RESOLUTION", "ISSUE_RESOLUTION"),
                            ("PAYMENT_UPDATE", "PAYMENT_UPDATE"),
                            ("PERSONAL_FINANCE_UPDATE", "PERSONAL_FINANCE_UPDATE"),
                            ("RESERVATION_UPDATE", "RESERVATION_UPDATE"),
                            ("SHIPPING_UPDATE", "SHIPPING_UPDATE"),
                            ("TICKET_UPDATE", "TICKET_UPDATE"),
                        ],
                        max_length=25,
                    ),
                ),
                ("language", models.CharField(default="PT-BR", max_length=10)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True)),
                ("exclusao_dt", models.DateTimeField(blank=True, null=True)),
                ("statusregistro_id", models.IntegerField()),
            ],
        ),
    ]
