# Generated by Django 4.1.4 on 2023-11-08 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0007_alter_ger_condicoespagamento_condicaopadrao_and_more"),
        ("wpp_templates", "0003_wpp_templates_empresa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wpp_templates",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_empresas.ger_empresas",
            ),
        ),
    ]
