# Generated by Django 4.1.4 on 2024-03-01 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0027_alter_stringpersonalizada_lingua"),
        ("wpp_templates", "0004_alter_wpp_templates_empresa"),
    ]

    operations = [
        migrations.CreateModel(
            name="ia_criatividade",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("criatividade", models.CharField(max_length=255)),
                ("gpt", models.CharField(max_length=255)),
                ("key", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "ia_criatividade",
            },
        ),
        migrations.CreateModel(
            name="ia_tomvoz",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tomvoz", models.CharField(max_length=255)),
                ("gpt", models.CharField(max_length=255)),
                ("key", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "ia_tomvoz",
            },
        ),
        migrations.CreateModel(
            name="ia_geracao",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("prompt_text_produto", models.TextField()),
                ("prompt_publico_alvo", models.TextField(null=True)),
                ("prompt_descricao", models.TextField(null=True)),
                ("text_gerado_ia", models.TextField(null=True)),
                ("tokens_usados", models.CharField(max_length=255, null=True)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True)),
                (
                    "criatividade",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="wpp_templates.ia_criatividade",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
                (
                    "tomvoz",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="wpp_templates.ia_tomvoz",
                    ),
                ),
            ],
            options={
                "db_table": "ia_geracao",
            },
        ),
    ]
