# Generated by Django 4.1.4 on 2024-03-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0005_ia_criatividade_ia_tomvoz_ia_geracao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ia_criatividade",
            name="gpt",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="ia_criatividade",
            name="key",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="ia_tomvoz",
            name="gpt",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="ia_tomvoz",
            name="key",
            field=models.TextField(),
        ),
    ]
