# Generated by Django 4.1.4 on 2024-03-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "wpp_templates",
            "0006_alter_ia_criatividade_gpt_alter_ia_criatividade_key_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ia_criatividade",
            name="gpt",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="ia_criatividade",
            name="key",
            field=models.TextField(null=True),
        ),
    ]
