# Generated by Django 4.1.4 on 2024-03-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0007_alter_ia_criatividade_gpt_alter_ia_criatividade_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ia_tomvoz",
            name="gpt",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="ia_tomvoz",
            name="key",
            field=models.TextField(null=True),
        ),
    ]
