# Generated by Django 4.1.4 on 2024-03-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0008_alter_ia_tomvoz_gpt_alter_ia_tomvoz_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="gpt_engine",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("gpt_engine", models.TextField(null=True)),
            ],
            options={
                "db_table": "gpt_engine",
            },
        ),
        migrations.CreateModel(
            name="ia_prompt_settings",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("prompt", models.TextField(null=True)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ia_prompt_settings",
            },
        ),
    ]
