# Generated by Django 4.1.4 on 2024-03-05 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0009_gpt_engine_ia_prompt_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="ia_prompt_settings",
            name="gpt_engine",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="wpp_templates.gpt_engine",
            ),
        ),
    ]
