# Generated by Django 4.1.4 on 2024-03-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0010_ia_prompt_settings_gpt_engine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ia_geracao",
            name="text_gerado_ia",
            field=models.TextField(db_collation="utf8mb4_unicode_ci", null=True),
        ),
    ]
