# Generated by Django 4.1.4 on 2024-04-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0011_alter_ia_geracao_text_gerado_ia"),
    ]

    operations = [
        migrations.CreateModel(
            name="wpp_fields",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("exibicao", models.CharField(max_length=100, null=True)),
                ("descricao", models.CharField(max_length=100, null=True)),
                ("tabela_origem", models.CharField(max_length=100, null=True)),
                ("campo_origem", models.CharField(max_length=100, null=True)),
                ("tabela_vinculada", models.CharField(max_length=100, null=True)),
                ("campo_vinculado", models.CharField(max_length=100, null=True)),
                ("campo_chave", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
