# Generated by Django 4.1.4 on 2024-04-04 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0017_bot_horariofimenvio_bot_horarioinicioenvio"),
        ("bot_canal", "0003_remove_bot_canal_provedor"),
        ("wpp_templates", "0012_wpp_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="wpp_templates",
            name="CarrinhoAbandonado",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AddField(
            model_name="wpp_templates",
            name="CompraRecebida",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AddField(
            model_name="wpp_templates",
            name="Repique1",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AddField(
            model_name="wpp_templates",
            name="Repique1minutos",
            field=models.IntegerField(default=240, null=True),
        ),
        migrations.AddField(
            model_name="wpp_templates",
            name="Repique2",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AddField(
            model_name="wpp_templates",
            name="Repique2minutos",
            field=models.IntegerField(default=240, null=True),
        ),
        migrations.AddField(
            model_name="wpp_templates",
            name="bot_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="bot.bot"
            ),
        ),
        migrations.AddField(
            model_name="wpp_templates",
            name="canal_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bot_canal.bot_canal",
            ),
        ),
    ]
