# Generated by Django 4.1.4 on 2024-04-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0013_wpp_templates_carrinhoabandonado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wpp_templates",
            name="id_sendpulse",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
