# Generated by Django 4.1.4 on 2024-05-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0014_wpp_templates_id_sendpulse"),
    ]

    operations = [
        migrations.AddField(
            model_name="wpp_templates",
            name="possui_call_to_action",
            field=models.CharField(default="N", max_length=1),
        ),
    ]
