# Generated by Django 4.1.4 on 2024-05-09 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0015_wpp_templates_possui_call_to_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="callToAction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("palavra_acao", models.CharField(max_length=100)),
                ("link", models.CharField(max_length=500, null=True)),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="template_call_to_actions",
                        to="wpp_templates.wpp_templates",
                    ),
                ),
                (
                    "template_resposta",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="template_resposta_call_to_actions",
                        to="wpp_templates.wpp_templates",
                    ),
                ),
            ],
        ),
    ]
