# Generated by Django 4.1.4 on 2024-05-09 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0016_calltoaction"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="calltoaction",
            table="callToAction",
        ),
    ]
