# Generated by Django 4.1.4 on 2024-05-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0017_alter_calltoaction_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="calltoaction",
            name="processada",
            field=models.CharField(default="N", max_length=1),
        ),
    ]
