# Generated by Django 4.1.4 on 2024-05-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0018_calltoaction_processada"),
    ]

    operations = [
        migrations.AddField(
            model_name="wpp_templates",
            name="processada_ajuste_resposta",
            field=models.CharField(default="N", max_length=1),
        ),
    ]
