# Generated by Django 4.1.4 on 2024-05-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0026_bot_call_to_actions"),
        ("wpp_templates", "0019_wpp_templates_processada_ajuste_resposta"),
    ]

    operations = [
        migrations.AddField(
            model_name="calltoaction",
            name="bots_conectados",
            field=models.ManyToManyField(blank=True, to="bot.bot"),
        ),
    ]
