# Generated by Django 4.1.4 on 2024-05-24 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0031_alter_ger_empresas_image_logo_empresa"),
        ("wpp_templates", "0020_calltoaction_bots_conectados"),
    ]

    operations = [
        migrations.AddField(
            model_name="calltoaction",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_empresas.ger_empresas",
            ),
        ),
    ]
