# Generated by Django 4.1.4 on 2024-06-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0021_calltoaction_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="calltoaction",
            name="opcoes",
            field=models.CharField(
                choices=[("PIX", "Pix"), ("CPF", "CPF/CNPJ")], max_length=3, null=True
            ),
        ),
    ]
