# Generated by Django 4.1.4 on 2024-06-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0022_calltoaction_opcoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="calltoaction",
            name="valor_pix",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
