# Generated by Django 4.1.4 on 2024-06-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0023_calltoaction_valor_pix"),
    ]

    operations = [
        migrations.AddField(
            model_name="wpp_templates",
            name="flow_id",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
