# Generated by Django 4.1.4 on 2024-06-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0024_wpp_templates_flow_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wpp_templates",
            old_name="flow_id",
            new_name="flow_id_1",
        ),
        migrations.AddField(
            model_name="wpp_templates",
            name="flow_id_2",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
