# Generated by Django 4.1.4 on 2024-07-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0025_rename_flow_id_wpp_templates_flow_id_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wpp_templates",
            name="ajustada_fuxo_mensagens",
            field=models.CharField(default="N", max_length=1, null=True),
        ),
    ]
