# Generated by Django 4.1.4 on 2024-10-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0026_wpp_templates_ajustada_fuxo_mensagens"),
    ]

    operations = [
        migrations.AddField(
            model_name="wpp_fields",
            name="campo_vinculado_2",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="wpp_fields",
            name="tabela_vinculada_2",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
