# Generated by Django 4.1.4 on 2024-10-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0027_wpp_fields_campo_vinculado_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wpp_fields",
            name="valor_filtragem",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
