# Generated by Django 4.1.4 on 2024-10-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0028_wpp_fields_valor_filtragem"),
    ]

    operations = [
        migrations.AddField(
            model_name="wpp_fields",
            name="campo_chave_2",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
