# Generated by Django 4.1.4 on 2025-01-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0029_wpp_fields_campo_chave_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="wpp_templates",
            name="status",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
