# Generated by Django 4.1.4 on 2025-04-07 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0040_ger_unidade_boomerangue_apikey_and_more"),
        ("wpp_templates", "0030_wpp_templates_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flows",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        help_text="Nome ou título do fluxo", max_length=200
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "flow_json",
                    models.JSONField(
                        help_text="Representação JSON do fluxo criado na UI"
                    ),
                ),
                (
                    "n8n_workflow_id",
                    models.CharField(
                        blank=True,
                        help_text="ID do workflow no n8n, por exemplo: [company_id]_workflow_[uuid]",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True)),
                ("exclusao_dt", models.DateTimeField(blank=True, null=True)),
                ("statusregistro_id", models.IntegerField(default=200)),
                (
                    "empresa",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
            ],
            options={
                "db_table": "flows",
            },
        ),
    ]
