# Generated by Django 4.1.4 on 2025-04-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0031_flows"),
    ]

    operations = [
        migrations.AddField(
            model_name="flows",
            name="userVariables",
            field=models.TextField(
                blank=True,
                help_text="JSON string das variáveis definidas pelo usuário no fluxo",
                null=True,
            ),
        ),
    ]
