# Generated by Django 4.1.4 on 2025-04-22 18:05

import boomerangue.apps.wpp_templates.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0032_flows_uservariables"),
    ]

    operations = [
        migrations.AddField(
            model_name="flows",
            name="attached_file",
            field=models.FileField(
                blank=True,
                help_text="Arquivo anexado ao nó 'enviar_mensagem' do fluxo",
                null=True,
                upload_to=boomerangue.apps.wpp_templates.models.flow_attachment_path,
            ),
        ),
    ]
