# Generated by Django 4.1.4 on 2025-04-23 22:43

import boomerangue.apps.wpp_templates.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0033_flows_attached_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flows",
            name="attached_file",
            field=models.FileField(
                blank=True,
                help_text="Arquivo anexado ao nó 'enviar_mensagem' do fluxo (depreciado)",
                null=True,
                upload_to=boomerangue.apps.wpp_templates.models.flow_attachment_path,
            ),
        ),
        migrations.CreateModel(
            name="FlowAttachment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "node_id",
                    models.CharField(
                        help_text="ID do nó ao qual este arquivo está associado",
                        max_length=100,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=boomerangue.apps.wpp_templates.models.flow_attachment_path
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="Nome original do arquivo", max_length=255
                    ),
                ),
                (
                    "file_type",
                    models.CharField(help_text="Tipo MIME do arquivo", max_length=100),
                ),
                (
                    "file_key",
                    models.CharField(
                        help_text="Chave única para identificar este arquivo no flow_json",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="wpp_templates.flows",
                    ),
                ),
            ],
            options={
                "db_table": "flow_attachments",
            },
        ),
    ]
