# Generated by Django 4.1.4 on 2025-04-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0034_alter_flows_attached_file_flowattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="flows",
            name="n8n_return_id",
            field=models.CharField(
                blank=True,
                help_text="ID do fluxo n8n que retorna o resultado do fluxo",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flows",
            name="n8n_workflow_id",
            field=models.CharField(
                blank=True, help_text="ID único", max_length=100, null=True
            ),
        ),
    ]
