# Generated by Django 4.1.4 on 2023-10-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ger_grupoprodutos",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("empresa_id", models.BigIntegerField()),
                ("EDI_Integracao", models.CharField(max_length=50)),
                ("GrupoProdutos", models.CharField(max_length=50)),
                ("OrdemGrupoProdutos", models.CharField(max_length=5)),
                (
                    "grupoAtivo",
                    models.CharField(
                        choices=[("S", "Ativo"), ("N", "Inativo")], max_length=1
                    ),
                ),
                ("Sincronizado", models.CharField(max_length=1)),
                ("dtSincronizacao", models.DateTimeField()),
                ("verSincronizador", models.CharField(max_length=12)),
                ("idSincronizador", models.IntegerField()),
            ],
        ),
    ]
