# Generated by Django 4.1.4 on 2023-10-30 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0004_alter_ger_empresas_statusregistro_id"),
        ("ger_grupoprodutos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_grupoprodutos",
            name="alteracao_dt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_grupoprodutos",
            name="cadastro_dt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_grupoprodutos",
            name="exclusao_dt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ger_grupoprodutos",
            name="statusregistro_id",
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name="ger_grupoprodutos",
            name="EDI_Integracao",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ger_grupoprodutos",
            name="GrupoProdutos",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ger_grupoprodutos",
            name="OrdemGrupoProdutos",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="ger_grupoprodutos",
            name="Sincronizado",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="ger_grupoprodutos",
            name="dtSincronizacao",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="ger_grupoprodutos",
            name="empresa_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ger_empresas.ger_empresas",
            ),
        ),
        migrations.AlterField(
            model_name="ger_grupoprodutos",
            name="idSincronizador",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ger_grupoprodutos",
            name="verSincronizador",
            field=models.CharField(max_length=12, null=True),
        ),
    ]
