# Generated by Django 4.1.4 on 2023-11-07 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ger_grupoprodutos", "0002_ger_grupoprodutos_alteracao_dt_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ger_grupoprodutos",
            old_name="empresa_id",
            new_name="empresa",
        ),
        migrations.AlterModelTable(
            name="ger_grupoprodutos",
            table="ger_grupoprodutos",
        ),
    ]
