# Generated by Django 4.1.4 on 2023-11-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ger_grupoprodutos",
            "0003_rename_empresa_id_ger_grupoprodutos_empresa_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_grupoprodutos",
            name="Sincronizado",
            field=models.CharField(default="N", max_length=1),
        ),
    ]
