# Generated by Django 4.1.4 on 2023-10-05 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ger_dadosgerais", "0001_initial"),
        ("ger_empresas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ger_entidade",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "TipoEmpresa",
                    models.CharField(
                        choices=[("F", "Pessoa Física"), ("J", "Pessoa Jurídica")],
                        default="F",
                        max_length=1,
                    ),
                ),
                ("TipoEntidade", models.IntegerField(default="1")),
                ("InscricaoEstadual", models.CharField(max_length=10, null=True)),
                ("CNPJ", models.CharField(max_length=20, null=True)),
                ("CNPJNumerico", models.CharField(max_length=20, null=True)),
                ("Entidade", models.CharField(max_length=100, null=True)),
                ("Fantasia", models.CharField(max_length=100, null=True)),
                ("Endereco", models.CharField(max_length=70, null=True)),
                ("Numero", models.CharField(max_length=20, null=True)),
                ("Complemento", models.CharField(max_length=100, null=True)),
                ("Bairro", models.CharField(max_length=35, null=True)),
                ("CliLatitude", models.CharField(max_length=25, null=True)),
                ("CliLongitude", models.CharField(max_length=25, null=True)),
                ("Telefone1", models.CharField(max_length=25, null=True)),
                ("Telefone2", models.CharField(max_length=25, null=True)),
                ("WhatsAPPComercial", models.CharField(max_length=50, null=True)),
                ("Email_Comercial", models.EmailField(max_length=100, null=True)),
                ("Email_Compras", models.EmailField(max_length=100, null=True)),
                ("EMAIL_NFE", models.EmailField(max_length=100, null=True)),
                ("EMAIL_Marketing", models.EmailField(max_length=100, null=True)),
                ("Entidade_Ativa", models.CharField(default="S", max_length=1)),
                ("Cliente", models.CharField(default="S", max_length=1)),
                ("CEP", models.CharField(max_length=15, null=True)),
                ("ReceitaTelefone", models.CharField(max_length=50, null=True)),
                ("ReceitaEmail", models.EmailField(max_length=100, null=True)),
                ("ReceitaDataSituacao", models.DateField(null=True)),
                ("ReceitaAtivo", models.CharField(default="S", max_length=1)),
                ("DtAberturaEmpresa", models.DateField(null=True)),
                (
                    "Capital_Social",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                ("NomeContato", models.CharField(max_length=255, null=True)),
                ("SobrenomeContato", models.CharField(max_length=255, null=True)),
                ("EDI_Integracao", models.CharField(max_length=50, null=True)),
                ("TokenCliente", models.CharField(max_length=100, null=True)),
                ("Sincronizado", models.CharField(default="S", max_length=1)),
                ("dtSincronizacao", models.DateTimeField(null=True)),
                (
                    "Sincronizador_ver",
                    models.CharField(default="00.0000.0000", max_length=12),
                ),
                ("Sincronizador_id", models.IntegerField(null=True)),
                (
                    "cidade",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ger_dadosgerais.ger_cidade",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
                (
                    "pais",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ger_dadosgerais.ger_pais",
                    ),
                ),
                (
                    "uf",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ger_dadosgerais.ger_uf",
                    ),
                ),
            ],
            options={
                "db_table": "ger_entidade",
            },
        ),
        migrations.CreateModel(
            name="ger_grupoentidade",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("GrupoEntidade", models.CharField(max_length=50)),
                ("GrupoPadrao", models.BigIntegerField(default=0)),
                ("EDI_Integracao", models.CharField(max_length=50, null=True)),
                ("Sincronizado", models.CharField(default="S", max_length=1)),
                ("dtSincronizacao", models.DateTimeField(null=True)),
                (
                    "Sincronizador_ver",
                    models.CharField(default="00.0000.0000", max_length=12),
                ),
                ("Sincronizador_id", models.IntegerField(null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
            ],
            options={
                "db_table": "ger_grupoentidade",
            },
        ),
        migrations.CreateModel(
            name="ger_entidadetransportadora",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("EDI_Integracao", models.CharField(default="001", max_length=50)),
                (
                    "EntidadeTransportadoraAtiva",
                    models.CharField(default="S", max_length=1),
                ),
                ("Sincronizado", models.CharField(default="S", max_length=1)),
                ("dtSincronizacao", models.DateTimeField(null=True)),
                (
                    "Sincronizador_ver",
                    models.CharField(default="00.0000.0000", max_length=12),
                ),
                ("Sincronizador_id", models.IntegerField(null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
                (
                    "entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_entidades.ger_entidade",
                    ),
                ),
                (
                    "transportadora",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_dadosgerais.ger_transportadora",
                    ),
                ),
            ],
            options={
                "db_table": "ger_entidadetransportadora",
            },
        ),
        migrations.CreateModel(
            name="ger_entidadetabelapreco",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("EDI_Integracao", models.CharField(max_length=50, null=True)),
                ("TabelaAtivaEntidade", models.CharField(default="S", max_length=1)),
                (
                    "ValorMinimoPedido",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                ("TabelaValidaDesde", models.DateField(null=True)),
                ("TabelaValidaAte", models.DateField(null=True)),
                ("Sincronizado", models.CharField(default="S", max_length=1)),
                ("dtSincronizacao", models.DateTimeField(null=True)),
                (
                    "verSincronizador",
                    models.CharField(default="00.0000.0000", max_length=12),
                ),
                ("idSincronizador", models.IntegerField(null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
                (
                    "entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_entidades.ger_entidade",
                    ),
                ),
                (
                    "tabela_preco",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_dadosgerais.ger_tabelaprecos",
                    ),
                ),
            ],
            options={
                "db_table": "ger_entidadetabelapreco",
            },
        ),
        migrations.CreateModel(
            name="ger_entidadeendereco",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("EDI_Integracao", models.CharField(max_length=50, null=True)),
                (
                    "TipoEndereco_id",
                    models.CharField(
                        choices=[
                            ("E", "Fiscal"),
                            ("C", "Cobrança"),
                            ("ENT", "Entrega"),
                        ],
                        max_length=3,
                    ),
                ),
                ("EnderecoExibicao", models.CharField(max_length=100)),
                (
                    "TipoEmpresa",
                    models.CharField(
                        choices=[("F", "Pessoa Física"), ("J", "Pessoa Jurídica")],
                        max_length=1,
                    ),
                ),
                ("CNPJEndereco", models.CharField(max_length=20, null=True)),
                ("InscricaoEndereco", models.CharField(max_length=20, null=True)),
                ("CEP", models.CharField(default="00000-000", max_length=20)),
                ("Endereco", models.CharField(max_length=70)),
                ("Numero", models.CharField(max_length=20)),
                ("Complemento", models.CharField(max_length=30, null=True)),
                ("Bairro", models.CharField(max_length=50)),
                ("PontoReferencia", models.CharField(max_length=70)),
                ("TelefoneEndereco1", models.CharField(max_length=25)),
                ("RestricaoEntrega", models.CharField(max_length=50)),
                ("EnderecoAtivo", models.CharField(default="S", max_length=1)),
                ("EnderecoPadrao", models.CharField(default="N", max_length=1)),
                ("Sincronizado", models.CharField(default="S", max_length=1)),
                ("dtSincronizacao", models.DateTimeField(null=True)),
                (
                    "verSincronizador",
                    models.CharField(default="00.0000.0000", max_length=12),
                ),
                ("idSincronizador", models.IntegerField(null=True)),
                (
                    "cidade",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ger_dadosgerais.ger_cidade",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
                (
                    "entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_entidades.ger_entidade",
                    ),
                ),
                (
                    "pais",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_dadosgerais.ger_pais",
                    ),
                ),
                (
                    "uf",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ger_dadosgerais.ger_uf",
                    ),
                ),
            ],
            options={
                "db_table": "ger_entidadeendereco",
            },
        ),
        migrations.CreateModel(
            name="ger_entidadeempresa",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("EDI_Integracao", models.CharField(max_length=50, null=True)),
                ("MarcaEmpresa", models.CharField(max_length=100, null=True)),
                (
                    "urlMinhasEntregas",
                    models.CharField(
                        default="https://app.lokalizei.com/track/?id={pedido}",
                        max_length=100,
                    ),
                ),
                (
                    "SaldoDisponivel",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "LimiteCredito",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("GrupoEntidade_id", models.BigIntegerField()),
                ("CategoriaEntidade_id", models.IntegerField()),
                ("icondicoespagamento_id", models.BigIntegerField()),
                (
                    "CondPgtoCodTpDocCobranca",
                    models.CharField(max_length=10, null=True),
                ),
                ("NroCondicoesPgto", models.PositiveSmallIntegerField(default=0)),
                ("dtAlteracaoCondPgto", models.DateTimeField(null=True)),
                ("TabelaPreco_id", models.BigIntegerField()),
                ("TabelaPrecoSistema_id", models.BigIntegerField(null=True)),
                ("RotaVenda_id", models.BigIntegerField()),
                ("Vendedor_id", models.BigIntegerField()),
                ("Transportadora_id", models.IntegerField(null=True)),
                ("fretepadrao_id", models.IntegerField(default=0)),
                ("StatusAcesso_id", models.PositiveSmallIntegerField(default=0)),
                ("idEntidadeEndereco", models.BigIntegerField(default=0)),
                ("dtAlteracaoEndereco", models.DateTimeField(null=True)),
                ("NroEnderecos", models.PositiveSmallIntegerField(default=0)),
                ("Sincronizado", models.CharField(default="S", max_length=1)),
                ("dtSincronizacao", models.DateTimeField(null=True)),
                (
                    "Sincronizador_ver",
                    models.CharField(default="00.0000.0000", max_length=12),
                ),
                ("Sincronizador_id", models.IntegerField(null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
                (
                    "entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_entidades.ger_entidade",
                    ),
                ),
            ],
            options={
                "db_table": "ger_entidadeempresa",
            },
        ),
        migrations.CreateModel(
            name="ger_entidadecondicoespagamento",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "ParcelaMinima",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "Multiplicador",
                    models.DecimalField(decimal_places=8, default=1.0, max_digits=18),
                ),
                (
                    "MultiplicadorAPI",
                    models.DecimalField(decimal_places=8, default=1.0, max_digits=18),
                ),
                ("EntidadeCondicaoAtiva", models.CharField(default="S", max_length=1)),
                ("EDI_Integracao", models.CharField(default="001", max_length=50)),
                ("Sincronizado", models.CharField(default="S", max_length=1)),
                ("dtSincronizacao", models.DateTimeField(null=True)),
                (
                    "Sincronizador_ver",
                    models.CharField(default="00.0000.0000", max_length=12),
                ),
                ("Sincronizador_id", models.IntegerField(null=True)),
                (
                    "CondicaoPagamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_empresas.ger_condicoespagamento",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
                (
                    "entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_entidades.ger_entidade",
                    ),
                ),
            ],
            options={
                "db_table": "ger_entidadecondicoespagamento",
            },
        ),
        migrations.CreateModel(
            name="ger_categoriaentidade",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("CategoriaEntidade", models.CharField(max_length=50)),
                ("CategoriaPadrao", models.IntegerField(default=0)),
                ("EDI_Integracao", models.CharField(max_length=50, null=True)),
                ("Sincronizado", models.CharField(default="S", max_length=1)),
                ("dtSincronizacao", models.DateTimeField(null=True)),
                (
                    "Sincronizador_ver",
                    models.CharField(default="00.0000.0000", max_length=12),
                ),
                ("Sincronizador_id", models.IntegerField(null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
            ],
            options={
                "db_table": "ger_categoriaentidade",
            },
        ),
        migrations.AddIndex(
            model_name="ger_grupoentidade",
            index=models.Index(
                fields=["empresa"], name="ger_grupoen_empresa_cb2653_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ger_entidadetransportadora",
            unique_together={("entidade", "empresa", "transportadora")},
        ),
        migrations.AddIndex(
            model_name="ger_entidadetabelapreco",
            index=models.Index(
                fields=["empresa", "entidade"], name="ger_entidad_empresa_ed81b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ger_entidadetabelapreco",
            index=models.Index(
                fields=["empresa", "entidade", "tabela_preco"],
                name="ger_entidad_empresa_46172d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ger_entidadetabelapreco",
            index=models.Index(
                fields=["empresa", "entidade", "EDI_Integracao"],
                name="ger_entidad_empresa_4fa34a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ger_entidadetabelapreco",
            unique_together={("empresa", "entidade")},
        ),
        migrations.AlterUniqueTogether(
            name="ger_entidadeendereco",
            unique_together={
                ("empresa", "entidade", "TipoEndereco_id", "EDI_Integracao")
            },
        ),
        migrations.AlterUniqueTogether(
            name="ger_entidadeempresa",
            unique_together={("empresa", "entidade")},
        ),
        migrations.AlterUniqueTogether(
            name="ger_entidadecondicoespagamento",
            unique_together={("entidade", "empresa", "CondicaoPagamento")},
        ),
        migrations.AlterUniqueTogether(
            name="ger_entidade",
            unique_together={("TokenCliente",), ("empresa", "EDI_Integracao")},
        ),
        migrations.AddIndex(
            model_name="ger_categoriaentidade",
            index=models.Index(fields=["empresa"], name="idEmpresa"),
        ),
    ]
