# Generated by Django 4.1.4 on 2023-10-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_entidades", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_entidade",
            name="alteracao_dt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_entidade",
            name="exclusao_dt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ger_entidade",
            name="statusregistro_id",
            field=models.IntegerField(default=200),
        ),
    ]
