# Generated by Django 4.1.4 on 2023-10-16 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0003_alter_ger_condicoespagamento_empresa"),
        (
            "ger_entidades",
            "0002_ger_entidade_alteracao_dt_ger_entidade_exclusao_dt_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_entidade",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ger_empresas.ger_empresas",
            ),
        ),
    ]
