# Generated by Django 4.1.4 on 2023-11-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_entidades", "0003_alter_ger_entidade_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_categoriaentidade",
            name="alteracao_dt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_categoriaentidade",
            name="cadastro_dt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_categoriaentidade",
            name="exclusao_dt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ger_categoriaentidade",
            name="statusregistro_id",
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name="ger_entidade",
            name="cadastro_dt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_entidadecondicoespagamento",
            name="alteracao_dt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_entidadecondicoespagamento",
            name="cadastro_dt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_entidadecondicoespagamento",
            name="exclusao_dt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ger_entidadecondicoespagamento",
            name="statusregistro_id",
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name="ger_entidadeempresa",
            name="alteracao_dt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_entidadeempresa",
            name="cadastro_dt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_entidadeempresa",
            name="exclusao_dt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ger_entidadeempresa",
            name="statusregistro_id",
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name="ger_entidadeendereco",
            name="alteracao_dt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_entidadeendereco",
            name="cadastro_dt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_entidadeendereco",
            name="exclusao_dt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ger_entidadeendereco",
            name="statusregistro_id",
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name="ger_entidadetabelapreco",
            name="alteracao_dt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_entidadetabelapreco",
            name="cadastro_dt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_entidadetabelapreco",
            name="exclusao_dt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ger_entidadetabelapreco",
            name="statusregistro_id",
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name="ger_entidadetransportadora",
            name="alteracao_dt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_entidadetransportadora",
            name="cadastro_dt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_entidadetransportadora",
            name="exclusao_dt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ger_entidadetransportadora",
            name="statusregistro_id",
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name="ger_grupoentidade",
            name="alteracao_dt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_grupoentidade",
            name="cadastro_dt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="ger_grupoentidade",
            name="exclusao_dt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ger_grupoentidade",
            name="statusregistro_id",
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name="ger_categoriaentidade",
            name="CategoriaPadrao",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="ger_categoriaentidade",
            name="Sincronizado",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="ger_categoriaentidade",
            name="Sincronizador_ver",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="ger_entidade",
            name="Sincronizado",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="ger_entidade",
            name="Sincronizador_ver",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="ger_entidadecondicoespagamento",
            name="EDI_Integracao",
            field=models.CharField(default="001", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ger_entidadecondicoespagamento",
            name="EntidadeCondicaoAtiva",
            field=models.CharField(default="S", max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="ger_entidadecondicoespagamento",
            name="Multiplicador",
            field=models.DecimalField(
                decimal_places=8, default=1.0, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ger_entidadecondicoespagamento",
            name="MultiplicadorAPI",
            field=models.DecimalField(
                decimal_places=8, default=1.0, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ger_entidadecondicoespagamento",
            name="ParcelaMinima",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ger_entidadecondicoespagamento",
            name="Sincronizado",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="ger_entidadecondicoespagamento",
            name="Sincronizador_ver",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="ger_entidadeempresa",
            name="CategoriaEntidade_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ger_entidadeempresa",
            name="GrupoEntidade_id",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ger_entidadeempresa",
            name="LimiteCredito",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ger_entidadeempresa",
            name="NroCondicoesPgto",
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="ger_entidadeempresa",
            name="NroEnderecos",
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="ger_entidadeempresa",
            name="RotaVenda_id",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ger_entidadeempresa",
            name="SaldoDisponivel",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ger_entidadeempresa",
            name="Sincronizado",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="ger_entidadeempresa",
            name="Sincronizador_ver",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="ger_entidadeempresa",
            name="StatusAcesso_id",
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="ger_entidadeempresa",
            name="TabelaPreco_id",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ger_entidadeempresa",
            name="Vendedor_id",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ger_entidadeempresa",
            name="fretepadrao_id",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="ger_entidadeempresa",
            name="icondicoespagamento_id",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ger_entidadeempresa",
            name="idEntidadeEndereco",
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="ger_entidadeempresa",
            name="urlMinhasEntregas",
            field=models.CharField(
                default="https://app.lokalizei.com/track/?id={pedido}",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ger_entidadeendereco",
            name="Bairro",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ger_entidadeendereco",
            name="EnderecoExibicao",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ger_entidadeendereco",
            name="Numero",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="ger_entidadeendereco",
            name="PontoReferencia",
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name="ger_entidadeendereco",
            name="RestricaoEntrega",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ger_entidadeendereco",
            name="Sincronizado",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="ger_entidadeendereco",
            name="TelefoneEndereco1",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="ger_entidadeendereco",
            name="verSincronizador",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="ger_entidadetabelapreco",
            name="Sincronizado",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="ger_entidadetabelapreco",
            name="ValorMinimoPedido",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ger_entidadetabelapreco",
            name="verSincronizador",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="ger_entidadetransportadora",
            name="EDI_Integracao",
            field=models.CharField(default="001", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ger_entidadetransportadora",
            name="Sincronizado",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="ger_entidadetransportadora",
            name="Sincronizador_ver",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="ger_grupoentidade",
            name="GrupoPadrao",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="ger_grupoentidade",
            name="Sincronizado",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="ger_grupoentidade",
            name="Sincronizador_ver",
            field=models.CharField(max_length=12, null=True),
        ),
    ]
