# Generated by Django 4.1.4 on 2023-11-08 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0007_alter_ger_condicoespagamento_condicaopadrao_and_more"),
        (
            "ger_dadosgerais",
            "0006_ger_marcas_alteracao_dt_ger_marcas_cadastro_dt_and_more",
        ),
        ("ger_entidades", "0004_ger_categoriaentidade_alteracao_dt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_categoriaentidade",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_empresas.ger_empresas",
            ),
        ),
        migrations.AlterField(
            model_name="ger_entidade",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_empresas.ger_empresas",
            ),
        ),
        migrations.AlterField(
            model_name="ger_entidadecondicoespagamento",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_empresas.ger_empresas",
            ),
        ),
        migrations.AlterField(
            model_name="ger_entidadeempresa",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_empresas.ger_empresas",
            ),
        ),
        migrations.AlterField(
            model_name="ger_entidadeempresa",
            name="entidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_entidades.ger_entidade",
            ),
        ),
        migrations.AlterField(
            model_name="ger_entidadeendereco",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_empresas.ger_empresas",
            ),
        ),
        migrations.AlterField(
            model_name="ger_entidadeendereco",
            name="pais",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_dadosgerais.ger_pais",
            ),
        ),
        migrations.AlterField(
            model_name="ger_entidadetabelapreco",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_empresas.ger_empresas",
            ),
        ),
        migrations.AlterField(
            model_name="ger_entidadetransportadora",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_empresas.ger_empresas",
            ),
        ),
        migrations.AlterField(
            model_name="ger_grupoentidade",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_empresas.ger_empresas",
            ),
        ),
    ]
