# Generated by Django 4.1.4 on 2023-11-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_entidades", "0005_alter_ger_categoriaentidade_empresa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_entidade",
            name="ReceitaAtivo",
            field=models.CharField(default="V", max_length=1),
        ),
    ]
