# Generated by Django 4.1.4 on 2024-01-01 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_dadosgerais", "0008_alter_ger_distribuidor_table"),
        ("ger_entidades", "0007_ger_entidade_dataconfirmacaowp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_entidade",
            name="DataConfirmacaoWP",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ger_entidade",
            name="DataValidacaoWP",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ger_entidade",
            name="RespostaValidacaoWP",
            field=models.CharField(default="-", max_length=1),
        ),
        migrations.AddField(
            model_name="ger_entidade",
            name="TelefoneValidacaoWP",
            field=models.CharField(default="-", max_length=45),
        ),
        migrations.AddField(
            model_name="ger_entidade",
            name="vendedorValidacao",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_dadosgerais.ger_vendedores",
            ),
        ),
    ]
