# Generated by Django 4.1.4 on 2024-04-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_entidades", "0008_ger_entidade_dataconfirmacaowp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_entidade",
            name="DtAceiteOptin",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ger_entidade",
            name="StatusOptIN",
            field=models.CharField(
                choices=[
                    ("X", "Não fez opt-in"),
                    ("N", "Não Aceitou"),
                    ("P", "Pediu pra excluir dados"),
                    ("E", "Pediu pra enviar seus dados"),
                    ("S", "Aceitou opt-in"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ger_entidade",
            name="optinMensagemID",
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
