# Generated by Django 4.1.4 on 2024-04-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ger_entidades",
            "0009_ger_entidade_dtaceiteoptin_ger_entidade_statusoptin_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_entidade",
            name="optinMensagemID",
            field=models.IntegerField(null=True),
        ),
    ]
