# Generated by Django 4.1.4 on 2024-04-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_entidades", "0012_alter_ger_entidade_statusoptin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_entidade",
            name="StatusOptIN",
            field=models.CharField(
                choices=[
                    ("X", "Não fez opt-in"),
                    ("N", "Não Aceitou"),
                    ("P", "Pediu pra excluir dados"),
                    ("E", "Pediu pra enviar seus dados"),
                    ("S", "Aceitou opt-in"),
                ],
                default="X",
                max_length=1,
                null=True,
            ),
        ),
    ]
