# Generated by Django 4.1.4 on 2024-05-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_entidades", "0013_alter_ger_entidade_statusoptin"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_entidade",
            name="ultima_campanha_enviada",
            field=models.IntegerField(null=True),
        ),
    ]
