# Generated by Django 4.1.4 on 2024-06-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_entidades", "0014_ger_entidade_ultima_campanha_enviada"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_entidade",
            name="estagio_flow",
            field=models.IntegerField(default=0),
        ),
    ]
