# Generated by Django 4.1.4 on 2024-06-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_entidades", "0015_ger_entidade_estagio_flow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_entidade",
            name="estagio_flow",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
