# Generated by Django 4.1.4 on 2024-06-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_entidades", "0016_alter_ger_entidade_estagio_flow"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_entidade",
            name="cnpj_valido",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
