# Generated by Django 4.1.4 on 2024-07-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_entidades", "0017_ger_entidade_cnpj_valido"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_entidade",
            name="data_validacao",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ger_entidade",
            name="status_validacao",
            field=models.CharField(
                choices=[
                    ("validado", "Validado"),
                    ("nao_validado", "Não Validado"),
                    ("rejeitado", "Rejeitado"),
                ],
                default="nao_validado",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="ger_entidade",
            name="telefone_original",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="ger_entidade",
            name="telefone_validado",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
