# Generated by Django 4.1.4 on 2024-07-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_entidades", "0018_ger_entidade_data_validacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_entidade",
            name="lead_key_spl",
            field=models.CharField(max_length=80, null=True),
        ),
    ]
