# Generated by Django 4.1.4 on 2024-07-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_entidades", "0019_ger_entidade_lead_key_spl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_entidade",
            name="status_validacao",
            field=models.CharField(
                choices=[
                    ("validado", "Validado"),
                    ("nao_validado", "Não Validado"),
                    ("rejeitado", "Rejeitado"),
                ],
                default="nao_validado",
                max_length=25,
                null=True,
            ),
        ),
    ]
