# Generated by Django 4.1.4 on 2024-07-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_entidades", "0020_alter_ger_entidade_status_validacao"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="ger_entidade",
        #     name="keysearchmessage",
        #     field=models.CharField(max_length=100, null=True),
        # ),
    ]
