# Generated by Django 4.1.4 on 2024-07-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_entidades", "0021_ger_entidade_keysearchmessage"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="ger_entidade",
        #     name="keysearchmessagedate",
        #     field=models.DateTimeField(null=True),
        # ),
    ]
