# Generated by Django 4.1.4 on 2024-07-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_entidades", "0022_ger_entidade_keysearchmessagedate"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_entidade",
            name="keysearchmessage",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ger_entidade",
            name="keysearchmessagedate",
            field=models.DateTimeField(null=True),
        ),
    ]
