# Generated by Django 4.1.4 on 2024-11-17 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_entidades", "0023_ger_entidade_keysearchmessage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ger_entidade_tag",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("cod_entidade", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=50, null=True)),
                ("area", models.CharField(max_length=100, null=True)),
                ("regiao", models.CharField(max_length=100, null=True)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True, null=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True, null=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField(default=200)),
                (
                    "entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_entidades.ger_entidade",
                    ),
                ),
            ],
            options={
                "db_table": "ger_entidade_tag",
            },
        ),
        migrations.AddIndex(
            model_name="ger_entidade_tag",
            index=models.Index(
                fields=["entidade", "cod_entidade"],
                name="ger_entidad_entidad_bb4ab4_idx",
            ),
        ),
    ]
