# Generated by Django 4.1.4 on 2024-11-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_entidades", "0024_ger_entidade_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ger_entidade",
            name="Limite_de_credito",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ger_entidade",
            name="areceber",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="ger_entidade",
            name="saldo",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
