# Generated by Django 4.1.4 on 2024-11-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ger_entidades",
            "0025_ger_entidade_limite_de_credito_ger_entidade_areceber_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_entidade",
            name="Limite_de_credito",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ger_entidade",
            name="saldo",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=18, null=True
            ),
        ),
    ]
