# Generated by Django 4.1.4 on 2024-11-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_entidades", "0026_alter_ger_entidade_limite_de_credito_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_entidade",
            name="Bairro",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
