# Generated by Django 4.1.4 on 2024-11-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_entidades", "0027_alter_ger_entidade_bairro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_entidade",
            name="Complemento",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="ger_entidade",
            name="Endereco",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
