# Generated by Django 4.1.4 on 2024-11-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_entidades", "0028_alter_ger_entidade_complemento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_entidade",
            name="Limite_de_credito",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Limite de credito da entidade",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ger_entidade",
            name="saldo",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Saldo da entidade",
                max_digits=18,
                null=True,
            ),
        ),
    ]
