# Generated by Django 4.1.4 on 2024-11-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_entidades", "0029_alter_ger_entidade_limite_de_credito_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ger_entidade",
            index=models.Index(
                fields=["CliLatitude", "CliLongitude"],
                name="ger_entidad_CliLati_0c1313_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ger_entidade",
            index=models.Index(fields=["uf"], name="ger_entidad_uf_id_260c9a_idx"),
        ),
        migrations.AddIndex(
            model_name="ger_entidade",
            index=models.Index(
                fields=["cidade"], name="ger_entidad_cidade__ca8eaf_idx"
            ),
        ),
    ]
