# Generated by Django 4.1.4 on 2024-11-22 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0034_ger_empresas_template_envio_clinica_and_more"),
        ("ger_produtos", "0008_ger_produtos_quantidadeporcaixa"),
        ("ger_entidades", "0030_ger_entidade_ger_entidad_clilati_0c1313_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="rvd_entidade_recommendation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "relevancia",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "quantidade_media",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "quantidade_sugerida",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "sazonalidade",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "regional",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("big_six", models.BooleanField(default=False)),
                (
                    "valor_estimado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "valor_estimado_15",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "valor_estimado_30",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "valor_estimado_60",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "valor_estimado_90",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
                (
                    "entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_entidades.ger_entidade",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_produtos.ger_produtos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="rvd_entidade",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("categoria", models.CharField(max_length=100)),
                ("porte", models.CharField(max_length=50)),
                (
                    "potencial_regiao",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "potencial_cliente",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
                (
                    "entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_entidades.ger_entidade",
                    ),
                ),
            ],
        ),
    ]
