# Generated by Django 4.1.4 on 2024-11-22 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ger_entidades", "0031_rvd_entidade_recommendation_rvd_entidade"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="rvd_entidade",
            table="rvd_entidade",
        ),
        migrations.AlterModelTable(
            name="rvd_entidade_recommendation",
            table="rvd_entidade_recommendation",
        ),
    ]
