# Generated by Django 4.1.4 on 2024-12-02 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_produtos", "0008_ger_produtos_quantidadeporcaixa"),
        ("ger_entidades", "0032_alter_rvd_entidade_table_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="rvd_regionalproduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=100, unique=True)),
                ("produto_id", models.BigIntegerField()),
                ("popularity_score", models.FloatField(default=0.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Produto Regional",
                "verbose_name_plural": "Produtos Regionais",
                "db_table": "rvd_regionalproduct",
            },
        ),
        migrations.CreateModel(
            name="rvd_sazonalidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.PositiveSmallIntegerField()),
                ("fator", models.FloatField()),
                (
                    "produto_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_produtos.ger_produtos",
                    ),
                ),
            ],
            options={
                "db_table": "rvd_sazonalidade",
            },
        ),
        migrations.CreateModel(
            name="rvd_relevancialog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("peso_anterior", models.FloatField()),
                ("peso_atual", models.FloatField()),
                ("data_ajuste", models.DateTimeField(auto_now_add=True)),
                (
                    "produto_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_produtos.ger_produtos",
                    ),
                ),
            ],
            options={
                "db_table": "rvd_relevancialog",
            },
        ),
        migrations.CreateModel(
            name="rvd_entidade_feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aceito", models.BooleanField()),
                ("feedback", models.TextField(blank=True, null=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "entidade_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_entidades.ger_entidade",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_produtos.ger_produtos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback de Cliente",
                "verbose_name_plural": "Feedbacks de Clientes",
                "db_table": "rvd_entidade_feedback",
            },
        ),
    ]
