# Generated by Django 4.1.4 on 2024-12-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ger_entidades", "0033_rvd_regionalproduct_rvd_sazonalidade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rvd_entidade_recommendation",
            name="recommendation",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
