# Generated by Django 4.1.4 on 2024-12-15 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_dadosgerais", "0010_ger_dados_cep_bairro"),
        ("ger_entidades", "0034_rvd_entidade_recommendation_recommendation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_entidade",
            name="cidade",
            field=models.ForeignKey(
                help_text="Campo foreign key para a tabela cidade, aramazena o id da cidade vinculada",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ger_dadosgerais.ger_cidade",
            ),
        ),
        migrations.AlterField(
            model_name="ger_entidade",
            name="pais",
            field=models.ForeignKey(
                help_text="Campo foreign key para a tabela pais, aramazena o id do pais vinculado",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ger_dadosgerais.ger_pais",
            ),
        ),
        migrations.AlterField(
            model_name="ger_entidade",
            name="uf",
            field=models.ForeignKey(
                help_text="Campo foreign key para a tabela UF, aramazena o id da UF vinculada",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ger_dadosgerais.ger_uf",
            ),
        ),
    ]
