# Generated by Django 4.1.4 on 2024-12-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ger_entidades",
            "0035_alter_ger_entidade_cidade_alter_ger_entidade_pais_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ger_entidade",
            name="CNPJNumerico",
            field=models.CharField(
                help_text="Campo que armazena o CNPJ em formato numérico, sempre deve ser usado nas comparações de cnpj com somente números",
                max_length=20,
                null=True,
            ),
        ),
    ]
