# Generated by Django 4.1.4 on 2024-05-27 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ger_empresas", "0031_alter_ger_empresas_image_logo_empresa"),
    ]

    operations = [
        migrations.CreateModel(
            name="gateway_pagamento",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("gateway_name", models.CharField(max_length=100)),
                (
                    "gateway_type",
                    models.CharField(
                        choices=[
                            ("BB", "Banco do Brasil"),
                            ("MP", "Mercado Pago"),
                            ("SC", "Sicoob"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "certificados",
                    models.FileField(
                        null=True, upload_to="media/gateway_pagamentos/certificados/"
                    ),
                ),
                (
                    "certificados_senhas",
                    models.FileField(
                        null=True,
                        upload_to="media/gateway_pagamentos/certificados_senhas/",
                    ),
                ),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True, null=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True)),
                ("exclusao_dt", models.DateTimeField(null=True)),
                ("statusregistro_id", models.IntegerField(default=200)),
                (
                    "empresa",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
            ],
            options={
                "db_table": "gateway_pagamento",
            },
        ),
    ]
