# Generated by Django 4.1.4 on 2024-05-28 21:29

import boomerangue.apps.gateway_pagamento.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway_pagamento", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateway_pagamento",
            name="certificado_name",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="gateway_pagamento",
            name="certificados_senhas_name",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="gateway_pagamento",
            name="certificados",
            field=models.FileField(
                null=True,
                storage=boomerangue.apps.gateway_pagamento.models.WasabiStorage(),
                upload_to="certificados/",
            ),
        ),
        migrations.AlterField(
            model_name="gateway_pagamento",
            name="certificados_senhas",
            field=models.FileField(
                null=True,
                storage=boomerangue.apps.gateway_pagamento.models.WasabiStorage(),
                upload_to="certificados_senhas/",
            ),
        ),
    ]
