# Generated by Django 4.1.4 on 2024-05-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway_pagamento", "0002_gateway_pagamento_certificado_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateway_pagamento",
            name="certificados_senhas_url",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="gateway_pagamento",
            name="certificados_url",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
