# Generated by Django 4.1.4 on 2024-06-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gateway_pagamento",
            "0003_gateway_pagamento_certificados_senhas_url_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="gateway_pagamento",
            name="client_id",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="gateway_pagamento",
            name="client_secret",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="gateway_pagamento",
            name="dev_key",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="gateway_pagamento",
            name="pix_key",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
