# Generated by Django 4.1.4 on 2024-06-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway_pagamento", "0004_gateway_pagamento_client_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateway_pagamento",
            name="expiration_time",
            field=models.IntegerField(null=True),
        ),
    ]
