# Generated by Django 4.1.4 on 2023-11-07 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bot_canal", "0001_initial"),
        ("ger_empresas", "0006_rename_empresa_id_ger_empresa_b2b_empresa_and_more"),
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="bot_canalempresa",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "bcc_ativo",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não")], default="S", max_length=1
                    ),
                ),
                (
                    "key1",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Chave de configuração 1",
                    ),
                ),
                (
                    "key2",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Chave de configuração 2",
                    ),
                ),
                (
                    "key3",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Chave de configuração 3",
                    ),
                ),
                (
                    "key4",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Chave de configuração 4",
                    ),
                ),
                (
                    "limite_diario",
                    models.IntegerField(
                        default=100, verbose_name="Limite diário de mensagens"
                    ),
                ),
                (
                    "limite_semanal",
                    models.IntegerField(
                        default=500, verbose_name="Limite semanal de mensagens"
                    ),
                ),
                (
                    "taxa_crescimento_semanal",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="Taxa de crescimento semanal",
                    ),
                ),
                ("cadastro_dt", models.DateTimeField(auto_now=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True)),
                ("exclusao_dt", models.DateTimeField(blank=True, null=True)),
                ("statusregistro_id", models.IntegerField(default=200)),
                (
                    "bot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bot.bot",
                    ),
                ),
                (
                    "canal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bot_canal.bot_canal",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
            ],
            options={
                "db_table": "bot_canalempresa",
            },
        ),
    ]
