# Generated by Django 4.1.4 on 2024-11-20 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ger_empresas", "0034_ger_empresas_template_envio_clinica_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessageIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[("user", "User"), ("bot", "Bot")], max_length=10
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("tokens", models.IntegerField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ChatMessageIA",
            },
        ),
        migrations.CreateModel(
            name="CanalMessageIA",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ia_messages.chatmessageia",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ger_empresas.ger_empresas",
                    ),
                ),
            ],
            options={
                "db_table": "CanalMessageIA",
            },
        ),
    ]
