# Generated by Django 4.1.4 on 2024-11-20 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ia_messages", "0002_canalmessageia_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="canalmessageia",
            name="chat",
        ),
        migrations.AddField(
            model_name="chatmessageia",
            name="canal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ia_messages.canalmessageia",
            ),
        ),
    ]
