# Generated by Django 4.1.4 on 2024-11-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ia_messages", "0003_remove_canalmessageia_chat_chatmessageia_canal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessageia",
            name="message",
            field=models.TextField(db_collation="utf8mb4_unicode_ci"),
        ),
    ]
