# Generated by Django 4.1.4 on 2025-02-04 20:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="validacao_documentos",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=100, null=True)),
                ("data_nascimento", models.CharField(max_length=12, null=True)),
                ("cpf", models.CharField(max_length=14, null=True)),
                ("nome_mae", models.CharField(max_length=100, null=True)),
                ("nome_pai", models.CharField(max_length=100, null=True)),
                (
                    "sexo",
                    models.CharField(
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Feminino"),
                            ("N", "Não especificado"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("nacionalidade", models.CharField(max_length=70, null=True)),
                ("uf_nascimento", models.CharField(max_length=2, null=True)),
                ("cidade_nascimento", models.CharField(max_length=500, null=True)),
                ("passaporte", models.CharField(max_length=100, null=True)),
                ("rne_rnm", models.CharField(max_length=100, null=True)),
                (
                    "documento_identificacao",
                    models.CharField(max_length=100, null=True),
                ),
                ("orgao_expedidor", models.CharField(max_length=100, null=True)),
                ("uf_expedidor", models.CharField(max_length=2, null=True)),
                (
                    "documento_identificacao_estrangeiro",
                    models.CharField(max_length=100, null=True),
                ),
                ("reside_brasil", models.CharField(max_length=2, null=True)),
                ("tempo_residencia", models.CharField(max_length=50, null=True)),
                ("brasileiro_naturalizado", models.CharField(max_length=1, null=True)),
                ("documento_valido", models.CharField(max_length=1, null=True)),
                ("cadastro_dt", models.DateTimeField(auto_now_add=True)),
                ("alteracao_dt", models.DateTimeField(auto_now=True)),
                ("exclusao_dt", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "validacao_documentos",
            },
        ),
        migrations.AddIndex(
            model_name="validacao_documentos",
            index=models.Index(fields=["cpf"], name="cpf_verification"),
        ),
    ]
