# Generated by Django 4.1.4 on 2025-02-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validacao_documentos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="validacao_documentos",
            name="statusregistro_id",
            field=models.IntegerField(default=200),
        ),
    ]
