# Generated by Django 4.1.4 on 2025-02-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validacao_documentos", "0002_validacao_documentos_statusregistro_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validacao_documentos",
            name="data_nascimento",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
