# Generated by Django 4.1.4 on 2024-02-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="EDI_Integracao",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bot",
            name="alteracao_dt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="bot",
            name="bot",
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name="bot",
            name="bot_apelido",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="bot",
            name="bot_ativo",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="bot",
            name="bot_meio",
            field=models.CharField(
                choices=[
                    ("Comunica EVL", "Comunica EVL"),
                    ("Comunica WO", "Comunica WO"),
                    ("Comunica ZP", "Comunica ZP"),
                    ("Comunica WB", "Comunica WB"),
                    ("Comunica CO", "Comunica CO"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="bot_numero",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="bot",
            name="bot_passivo",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="bot",
            name="bot_tipo",
            field=models.CharField(
                choices=[
                    ("Conversational CO", "Conversational CO"),
                    ("Boomerangue BM", "Boomerangue BM"),
                    ("Mixto MX", "Mixto MX"),
                    ("Comunica", "Comunica"),
                    ("Bot", "Bot"),
                    ("Serviço", "Serviço"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="cadastro_dt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="bot",
            name="canal",
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name="bot",
            name="exclusao_dt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="bot",
            name="statusregistro_id",
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name="bot",
            name="url_webhook",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="bot",
            name="webhook_ativo",
            field=models.CharField(blank=True, default="N", max_length=45),
        ),
        migrations.AddField(
            model_name="bot",
            name="webhook_ativo_evento",
            field=models.CharField(blank=True, default="N", max_length=45),
        ),
        migrations.AlterModelTable(
            name="bot",
            table="Bot",
        ),
    ]
