# Generated by Django 4.1.4 on 2024-02-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_initial2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="bot_ativo",
            field=models.CharField(default="N", max_length=1, null=True),
        ),
        migrations.AlterModelTable(
            name="bot",
            table="bot",
        ),
    ]
