# Generated by Django 4.1.4 on 2024-02-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0003_alter_bot_bot_ativo_alter_bot_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="api_key",
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
