# Generated by Django 4.1.4 on 2024-03-12 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bot_provedor", "0006_bot_provedor_legenda_1_bot_provedor_legenda_2_and_more"),
        ("bot", "0004_bot_api_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="bot_provedor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="bot_provedor.bot_provedor",
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="legenda_1",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bot",
            name="legenda_2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bot",
            name="legenda_3",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bot",
            name="legenda_4",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
