# Generated by Django 4.1.4 on 2024-03-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0005_bot_bot_provedor_bot_legenda_1_bot_legenda_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="limite_diario",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="bot",
            name="limite_semanal",
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name="bot",
            name="taxa_crescimento",
            field=models.DecimalField(decimal_places=0, default=1.2, max_digits=65),
        ),
    ]
