# Generated by Django 4.1.4 on 2024-03-13 19:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0006_bot_limite_diario_bot_limite_semanal_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bot",
            name="taxa_crescimento",
        ),
    ]
