# Generated by Django 4.1.4 on 2024-03-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0007_remove_bot_taxa_crescimento"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="taxa_crescimento",
            field=models.DecimalField(decimal_places=0, default=1.2, max_digits=65),
        ),
    ]
