# Generated by Django 4.1.4 on 2024-03-13 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0010_alter_bot_taxa_crescimento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bot",
            name="taxa_crescimento",
        ),
    ]
