# Generated by Django 4.1.4 on 2024-03-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0012_bot_taxa_crescimento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="limite_diario",
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.AlterField(
            model_name="bot",
            name="limite_semanal",
            field=models.IntegerField(default=500, null=True),
        ),
        migrations.AlterField(
            model_name="bot",
            name="taxa_crescimento",
            field=models.DecimalField(
                decimal_places=2, default=1.2, max_digits=4, null=True
            ),
        ),
    ]
