# Generated by Django 4.1.4 on 2024-03-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0013_alter_bot_limite_diario_alter_bot_limite_semanal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="limite_diario",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="bot",
            name="limite_semanal",
            field=models.IntegerField(default=500),
        ),
    ]
