# Generated by Django 4.1.4 on 2024-04-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0015_alter_bot_limite_diario_alter_bot_limite_semanal"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="limite_envio_plataforma",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
