# Generated by Django 4.1.4 on 2024-04-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0016_bot_limite_envio_plataforma"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="bot",
        #     name="HorarioFimEnvio",
        #     field=models.IntegerField(default=19, null=True),
        # ),
        # migrations.AddField(
        #     model_name="bot",
        #     name="HorarioInicioEnvio",
        #     field=models.IntegerField(default=8, null=True),
        # ),
    ]
