# Generated by Django 4.1.4 on 2024-04-04 21:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0017_bot_horariofimenvio_bot_horarioinicioenvio"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="bot",
        #     name="HorarioFimEnvio",
        # ),
    ]
