# Generated by Django 4.1.4 on 2024-04-08 19:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0020_remove_bot_horariofimenvio_and_more"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="bot",
        #     name="HorarioFimEnvio",
        # ),
        # migrations.RemoveField(
        #     model_name="bot",
        #     name="HorarioInicioEnvio",
        # ),
    ]
