# Generated by Django 4.1.4 on 2024-04-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0022_bot_horariofimenvio_bot_horarioinicioenvio"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="ftp",
            field=models.CharField(default="no", max_length=3),
        ),
        migrations.AddField(
            model_name="bot",
            name="ftp_config",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="bot",
            name="bot_tipo",
            field=models.CharField(
                choices=[
                    ("Conversational CO", "Conversational CO"),
                    ("Boomerangue BM", "Boomerangue BM"),
                    ("Mixto MX", "Mixto MX"),
                    ("Comunica", "Comunica"),
                    ("Bot", "Bot"),
                    ("Serviço", "Serviço"),
                    ("Recrutador", "Recrutador"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
