# Generated by Django 4.1.4 on 2024-04-30 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0023_bot_ftp_bot_ftp_config_alter_bot_bot_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotActions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "type_action",
                    models.CharField(
                        choices=[("CA", "Call to action"), ("AP", "API")],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("description", models.CharField(max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("date_end", models.DateTimeField(null=True)),
                ("date_start", models.DateTimeField(auto_now_add=True)),
                ("rules", models.TextField(null=True)),
                ("order", models.CharField(max_length=3, null=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="bot.bot"
                    ),
                ),
            ],
            options={
                "db_table": "bot_actions",
            },
        ),
        migrations.CreateModel(
            name="BotActionSteps",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=50, null=True)),
                ("order", models.CharField(max_length=3, null=True)),
                (
                    "type_step",
                    models.CharField(
                        choices=[("CA", "Call to action"), ("AP", "API")],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("POST", "POST"),
                            ("GET", "GET"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                            ("PUT", "PUT"),
                        ],
                        max_length=6,
                        null=True,
                    ),
                ),
                ("url", models.CharField(max_length=400, null=True)),
                ("header", models.TextField(null=True)),
                ("payload", models.TextField(null=True)),
                ("rules_step", models.TextField(null=True)),
                ("next_rule_fail", models.IntegerField(null=True)),
                ("next_rule_ok", models.IntegerField(null=True)),
                ("number_fail_retries", models.IntegerField(null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "bot_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="bot.botactions"
                    ),
                ),
            ],
            options={
                "db_table": "bot_actions_steps",
            },
        ),
    ]
