# Generated by Django 4.1.4 on 2024-05-01 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0024_botactions_botactionsteps"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="botactionsteps",
            name="next_rule_fail",
        ),
        migrations.RemoveField(
            model_name="botactionsteps",
            name="next_rule_ok",
        ),
        migrations.RemoveField(
            model_name="botactionsteps",
            name="number_fail_retries",
        ),
        migrations.AddField(
            model_name="botactionsteps",
            name="next_step_on_failure",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="failure_steps",
                to="bot.botactionsteps",
            ),
        ),
        migrations.AddField(
            model_name="botactionsteps",
            name="next_step_on_success",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="success_steps",
                to="bot.botactionsteps",
            ),
        ),
        migrations.AddField(
            model_name="botactionsteps",
            name="retry_on_failure",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="botactions",
            name="order",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="botactionsteps",
            name="bot_action",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bot.botactions"
            ),
        ),
        migrations.AlterField(
            model_name="botactionsteps",
            name="header",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="botactionsteps",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="botactionsteps",
            name="order",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="botactionsteps",
            name="payload",
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name="BotActionTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trigger_phrase", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "bot_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bot.botactions"
                    ),
                ),
            ],
        ),
    ]
