# Generated by Django 4.1.4 on 2024-05-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0025_remove_botactionsteps_next_rule_fail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="call_to_actions",
            field=models.JSONField(default=dict),
        ),
    ]
