# Generated by Django 4.1.4 on 2024-09-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0026_bot_call_to_actions"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="bot_padrao",
            field=models.CharField(default="N", max_length=1, null=True),
        ),
    ]
