# Generated by Django 4.1.4 on 2023-10-05 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="bot_provedor",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "provedor",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="Nome do provedor",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não")],
                        default="N",
                        max_length=1,
                        verbose_name="Suporta Email?",
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não")],
                        default="S",
                        max_length=1,
                        verbose_name="Suporta WhatsApp?",
                    ),
                ),
                (
                    "sms",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não")],
                        default="N",
                        max_length=1,
                        verbose_name="Suporta SMS?",
                    ),
                ),
                (
                    "provedor_ativo",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não")],
                        default="S",
                        max_length=1,
                        verbose_name="Provedor Ativo?",
                    ),
                ),
                (
                    "cadastro_dt",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data e hora de criação do registro",
                    ),
                ),
                (
                    "alteracao_dt",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Data e hora da última modificação do registro",
                    ),
                ),
                (
                    "exclusao_dt",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Data e hora de exclusão do registro",
                    ),
                ),
                (
                    "statusregistro_id",
                    models.IntegerField(verbose_name="ID do status do registro"),
                ),
            ],
        ),
    ]
