# Generated by Django 4.1.4 on 2023-11-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_provedor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot_provedor",
            name="cadastro_dt",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data e hora de criação do registro"
            ),
        ),
        migrations.AlterField(
            model_name="bot_provedor",
            name="statusregistro_id",
            field=models.IntegerField(
                default=200, verbose_name="ID do status do registro"
            ),
        ),
    ]
