# Generated by Django 4.1.4 on 2023-11-06 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0005_ger_empresas_tipo"),
        ("bot_provedor", "0002_alter_bot_provedor_cadastro_dt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot_provedor",
            name="empresa_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ger_empresas.ger_empresas",
            ),
        ),
    ]
