# Generated by Django 4.1.4 on 2023-11-07 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot_provedor", "0003_bot_provedor_empresa_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bot_provedor",
            old_name="empresa_id",
            new_name="empresa",
        ),
        migrations.AlterModelTable(
            name="bot_provedor",
            table="bot_provedor",
        ),
    ]
