# Generated by Django 4.1.4 on 2023-11-08 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ger_empresas", "0007_alter_ger_condicoespagamento_condicaopadrao_and_more"),
        ("bot_provedor", "0004_rename_empresa_id_bot_provedor_empresa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot_provedor",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ger_empresas.ger_empresas",
            ),
        ),
    ]
