# Generated by Django 4.1.4 on 2024-03-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_provedor", "0005_alter_bot_provedor_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot_provedor",
            name="legenda_1",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bot_provedor",
            name="legenda_2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bot_provedor",
            name="legenda_3",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bot_provedor",
            name="legenda_4",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
