# Generated by Django 4.1.4 on 2024-03-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_provedor", "0006_bot_provedor_legenda_1_bot_provedor_legenda_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot_provedor",
            name="provedor_teste",
            field=models.CharField(
                choices=[("S", "Sim"), ("N", "Não")],
                default="N",
                max_length=1,
                null=True,
            ),
        ),
    ]
