# Generated by Django 4.1.4 on 2024-03-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_provedor", "0007_bot_provedor_provedor_teste"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot_provedor",
            name="cadastro_dt",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data e hora de criação do registro"
            ),
        ),
    ]
