# Generated by Django 4.1.4 on 2024-04-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_provedor", "0008_alter_bot_provedor_cadastro_dt"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot_provedor",
            name="IntervaloMininoMax",
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name="bot_provedor",
            name="IntervaloMininoMin",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="bot_provedor",
            name="LimiteDiario",
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name="bot_provedor",
            name="LimiteHora",
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name="bot_provedor",
            name="LimiteMinuto",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="bot_provedor",
            name="NroNovoIntervaloMininoMax",
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name="bot_provedor",
            name="NroNovoIntervaloMininoMin",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="bot_provedor",
            name="NroNovoLimiteDiario",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="bot_provedor",
            name="NroNovoLimiteHora",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="bot_provedor",
            name="NroNovoLimiteMinuto",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="bot_provedor",
            name="parametro_1",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="bot_provedor",
            name="parametro_2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="bot_provedor",
            name="parametro_3",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="bot_provedor",
            name="provedor_padrao",
            field=models.CharField(
                choices=[
                    ("WHAO", "Whatsapp Oficial"),
                    ("SNDP", "SendPulse"),
                    ("EVL", "Evolution"),
                    ("EVL17", "Evolution 1.7"),
                    ("EVLWO", "Evolution Oficial"),
                    ("ZAPI", "Zapi API"),
                    ("PCOM", "Plug Comunica"),
                    ("TWILI", "Twillio"),
                    ("360D", "360 Dialog"),
                    ("SMSD", "SMS Dev"),
                ],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bot_provedor",
            name="secret_1",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="bot_provedor",
            name="secret_2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="bot_provedor",
            name="secret_3",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
