# Generated by Django 4.1.4 on 2024-04-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_provedor", "0009_bot_provedor_intervalomininomax_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot_provedor",
            name="provedor_url_api",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
