# Generated by Django 4.1.4 on 2024-04-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_provedor", "0010_bot_provedor_provedor_url_api"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot_provedor",
            name="access_token",
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name="bot_provedor",
            name="access_token_expire",
            field=models.IntegerField(null=True),
        ),
    ]
