# Generated by Django 4.1.4 on 2024-04-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_provedor", "0011_bot_provedor_access_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot_provedor",
            name="provedor_padrao",
            field=models.CharField(
                choices=[
                    ("WHAO", "Whatsapp Oficial"),
                    ("SPL", "SendPulse"),
                    ("EVL", "Evolution"),
                    ("EVL17", "Evolution 1.7"),
                    ("EVLWO", "Evolution Oficial"),
                    ("ZAPI", "Zapi API"),
                    ("PCOM", "Plug Comunica"),
                    ("TWILI", "Twillio"),
                    ("360D", "360 Dialog"),
                    ("SMSD", "SMS Dev"),
                ],
                max_length=5,
                null=True,
            ),
        ),
    ]
