# Generated by Django 4.1.4 on 2024-04-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_provedor", "0012_alter_bot_provedor_provedor_padrao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot_provedor",
            name="access_token_expire",
            field=models.IntegerField(default=1, null=True),
        ),
    ]
