# Generated by Django 4.1.4 on 2024-04-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_provedor", "0013_alter_bot_provedor_access_token_expire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot_provedor",
            name="access_token",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
